### ISSUE TITLE
框架开启只读事物时kingshard无法处理，sql如下

### ISSUE THREAD

**Issue by lei40251** [flike/kingshard#106]
select @@session.tx_read_only

set session transaction read only

系统日志如下：
2015/12/24 09:26:48 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1193 (HY000): Unknown system variable 'transaction'" "hasHandled=false" conn_id=0
2015/12/24 09:26:48 - ERROR - conn.go:[289] - [server] "Run" "ERROR 1193 (HY000): Unknown system variable 'transaction'" "" conn_id=10028

2015/12/24 09:27:33 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1193 (HY000): Unknown system variable 'tx_read_only'" "hasHandled=false" conn_id=0
2015/12/24 09:27:33 - ERROR - conn.go:[289] - [server] "Run" "ERROR 1193 (HY000): Unknown system variable 'tx_read_only'" "" conn_id=10028

**Comment by flike** [comment]
命令行模式经过测试，是可以支持上述两条命令的

**Comment by mritd** [comment]
@lei40251 请问解决了么？我的也出现了同样的状况

**Comment by martianzhang** [comment]
kingshard中代码中指定的ServerVersion是5.6.20-miproxy，有些框架检查到这个版本之后就会发select @@session.tx_read_only; @lei40251 使用后端mysql可能是5.5版本的，当5.5版本的mysql接到这个请求时该变量不存在就会报如上错误，如果使用的5.6版本的mysql就没有这些的问题了。

临时解决办法有两个：
1. 升级mysql至5.6.5+版本
2. 修改代码const.go中的ServerVersion参数为5.5.xx-miproxy后重新编译。

后续可能考虑把这个参数设置成动态可配置的，如果不配置默认用5.6.20-miproxy

**Comment by mritd** [comment]
前段时间试了一下。。。降低 jar 包版本也可以；不过后面由于不支持存储过程放弃了。。。
