### ISSUE TITLE
有几个问题请教一下。

### ISSUE THREAD

**Issue by littleyang** [flike/kingshard#110]
1.多个schema怎么办呢？还是同样的一个配置文件么？
2.读写分离规则（slave)有没有更详细一点地文档呢？

**Comment by flike** [comment]
1. kingshard为了简化配置规则和方便使用，只支持了一个schema。如果一定要使用多个schema，只能部署多个kingshard实例。
2.读写分离规则：select在从库，其他在主库。当然你也可以强制读主库，通过/*master*/select xxxx 的方式。

**Comment by chenshangwei** [comment]
我测试了下 
/*master*/select * from.. limit 1; 无效
select /*master*/ * from.. limit 1; 有效
@flike 烦请作者确认
