### ISSUE TITLE
支持智能 id 分片方式

### ISSUE THREAD

**Issue by xiewenwei** [flike/kingshard#111]
智能 id 中带了分片信息，通常用比较长的整数作为 id（如 64位），id 由多段数据构成，分别是时间戳，分片信息和本地 id，分片 id 是基于另外的字段生成。
举个例子，假设有一种用户事件表 user_events(id bigint, user_id int, event_type int created_at datetime)
表通过 user_id hash 进行 shard 得到 shard_id，然后通过时间戳，shard_id  和一个自增数字生成 id。

智能 id 的好处是
1. 通过 id 可以获取 shard_id，id 保持有序，后生成的 id 值更大
2. 通过 user_id sharding，确保查单个 user 的数据时只需检索一个 shard

Pinterest 使用这种方式做 sharding，见 [Sharding Pinterest: How we scaled our MySQL fleet](https://engineering.pinterest.com/blog/sharding-pinterest-how-we-scaled-our-mysql-fleet)

Instagram 也使用这种方式 见 [Sharding ids at Instagram](http://instagram-engineering.tumblr.com/post/10853187575/sharding-ids-at-instagram)

**Comment by flike** [comment]
谢谢你的建议，我会仔细考虑一下这个方案的。

**Comment by xiewenwei** [comment]
我已经 fork 了一份代码，准备加上这个特性。最近刚刚在学 golang，可能还需要一点时间。我加好了给你发一个 pull request 哦。

**Comment by flike** [comment]
欢迎pr。:)
