### ISSUE TITLE
关于从库的配置的问题

### ISSUE THREAD

**Issue by littleyang** [flike/kingshard#115]
毕竟从库与主库还是有些差别的。比如说从库的最大连接数是500，而主库的最大连接数是1000的时候，在一个node里面，每个从库的最大连接数是默认配置的那个么？
另外，如果上面的结果就是那个max的值。能否将从库的配置某些属性设置为单独配置呢？或者算是个额外的需求吧。

**Comment by bigpyer** [comment]
第一个问题：是的
第二个问题：这样的需求应该不多，目前没有碰到，并且主从mysql 主机的型号一般都是相近的。

**Comment by littleyang** [comment]
@bigpyer 你说的毕竟是一种情况，如果能更灵活的话，岂不是更好么？
比如说一些云服务的rds，主从的性能就完全不一样的。

**Comment by flike** [comment]
单独配置使得配置文件的复杂度上升，这种需求感觉不高。
