### ISSUE TITLE
利用kignshard hash 长连接执行同一条插入语句时，会有一定概率报语法错误

### ISSUE THREAD

**Issue by wnself** [flike/kingshard#116]
shardKey是imei
固定插入语句：
INSERT INTO sr_instructions(imei,version,type,imsi,other_1,other_2,content,add_time)VALUES('{5f961c62-af7e-','V01',1,'9999999999999999','','','','2016-01-04 16:48:59');
偶尔的错误：
2015/12/31 08:40:22 - ERROR - conn_query.go:[65] - [server] "parse" "syntax error at position 169" "hasHandled=false|sql=INSERT INTO sr_instructions(imei,version,type,imsi,other_1,other_2,content,add_time)VALUES('{f6e4ac70-93d9-','V01',1,'9999999999999999','','','','2015-12-31 16:34:02');
表结构：
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for sr_instructions_0000
-- ----------------------------
DROP TABLE IF EXISTS `sr_instructions_0000`;
CREATE TABLE `sr_instructions_0000` (
  `imei` char(15) DEFAULT '0',
  `version` char(3) DEFAULT '0',
  `type` int(3) DEFAULT NULL,
  `imsi` char(19) DEFAULT '0',
  `other_1` varchar(100) DEFAULT '',
  `other_2` varchar(100) DEFAULT '0',
  `content` text,
  `add_time` datetime DEFAULT NULL,
  KEY `type` (`type`) USING BTREE,
  KEY `imei` (`imei`) USING BTREE,
  KEY `add_time` (`add_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
一共分了100个表
SELECT COUNT(*) FROM sr_instructions WHERE imei > '1'
结果为16707439

**Comment by flike** [comment]
能准确复现吗？

**Comment by wnself** [comment]
# server listen addr
addr : 0.0.0.0:9696

# server user and password
user :  kingshard
password : kingshard

#if set log_path, the sql log will write into log_path/sql.log,the system log
#will write into log_path/sys.log
log_path : /usr/local/kingshard/log

# log level[debug|info|warn|error],default error
log_level : debug
#if set log_sql(on|off) off,the sql log will not output
#log_sql: off 
#only log the query that take more than slow_log_time ms
#slow_log_time : 100
# only allow this ip list ip to connect kingshard
#allow_ips: 127.0.0.1

# node is an agenda for real remote mysql server.
nodes :
- 
    name : node1 

    # default max conns for mysql server
    max_conns_limit : 128

    # all mysql in a node must have the same user and password
    user :  kingshard 
    password : kingshard

    # master represents a real mysql master server 
    master : 192.168.1.194:3306

    # slave represents a real mysql salve server,and the number after '@' is 
    # read load weight of this slave.
    slave : 
    down_after_noalive : 32
- 
    name : node2 

    # default max conns for mysql server
    max_conns_limit : 128

    # all mysql in a node must have the same user and password
    user :  kingshard 
    password : kingshard

    # master represents a real mysql master server 
    master : 192.168.1.195:3306

    # slave represents a real mysql salve server 
    slave : 

    # down mysql after N seconds noalive
    # 0 will no down
    down_after_noalive: 32

# schema defines which db can be used by client and this db's sql will be executed in which nodes, the db is also the default database
schema :
    db : device
    nodes: [node1,node2]
    default: node1      
    shard:
    -   
        table: sr_instructions
        key: id
        nodes: [node1, node2]
        type: hash
        locations: [100,100]

    -   
#        table: test_shard_range
#        key: id
#        type: range
#        nodes: [node1, node2]
#        locations: [4,4]
#        table_row_limit: 10000

**Comment by wnself** [comment]
上面是陈的ks配置文件，问过他，key: id的事，他说默认用的是第一个字段，也就是imei。

**Comment by wnself** [comment]
现在iemi也char(15)类型

**Comment by flike** [comment]
table: sr_instructions
        key: id
        nodes: [node1, node2]
        type: hash
        locations: [100,100]

你的配置中分表字段是id，但你的SQL中表中并未包含该字段。这样是不可以的。请按照文档使用kingshard，否则会出现不可预知的错误。

**Comment by wnself** [comment]
如果要分的话，很可能是要用imei，但imei是char(15)，这样与"分表字段必须是整数"不符，有什么好的办法吗？

**Comment by flike** [comment]
你这个表没有主键吗？可以使用一个整数主键分表。后续我考虑支持字符串类型分表。
