### ISSUE TITLE
ks不支持一个mysql_query里执行多语句吗？

### ISSUE THREAD

**Issue by wnself** [flike/kingshard#117]
//Test code
#include <mysql.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <my_sys.h>
#include <string.h>

//0         1               2           3           4       5       6       7
//program   host            user        pass        db      port    sleep   statment
//argv[0]   192.168.1.196   kingshard   kingshard   device  9696    0     "INSERT INTO sr_instructions(imei,version,type,imsi,other_1,other_2,content,add_time)VALUES('%015d','V01',1,'%019d','','','','2016-01-05 10:55:58');"
struct s_ARGS
{
    int argc;
    char **argv;
};

void *function(void *args)
{
    printf("%lu:\tfunction\n", pthread_self());
    s_ARGS *aRGS = (s_ARGS*)args;
    int argc = aRGS->argc;
    char **argv = aRGS->argv;

    //    my_init();
    MYSQL mySQL;
    if(NULL == mysql_init(&mySQL))
    {
        printf("%lu:\t%s\n", pthread_self(), mysql_error(&mySQL));
        abort();
        return NULL;
    }
    printf("%lu:\tmysql_init ok!\n", pthread_self());

    //    if(mysql_library_init(0, NULL, NULL))
    //    {
    //        printf("%lu:\t%s\n", pthread_self(), mysql_error(&mySQL));
    //        abort();
    //        return NULL;
    //    }
    //    printf("%lu:\tmysql_library_init ok!\n", pthread_self());

    if(NULL == mysql_real_connect(&mySQL, argv[1], argv[2], argv[3], argv[4], atoi(argv[5]), NULL, CLIENT_MULTI_RESULTS|CLIENT_MULTI_STATEMENTS))
        //            if(NULL == mysql_real_connect(&mySQL, argv[1], argv[2], argv[3], argv[4], atoi(argv[5]), NULL, 0))
    {
        printf("%lu:\t%s\n", mysql_error(&mySQL));
        abort();
        return NULL;
    }
    printf("%lu:\tmysql_real_connect ok!\n", pthread_self());

    int secNo = 1;
    int errNo = 1;
    while(1)
    {
        char tmp[1024*1024] = "";
        //生成两条插入语句
        sprintf(tmp+strlen(tmp), argv[7], rand(), rand());
        sprintf(tmp+strlen(tmp), argv[7], rand(), rand());
        if(0 != mysql_query(&mySQL, tmp))
        {
            puts(tmp);
            printf("\033[31m%lu:\t%d\t%s\033[0m\n", pthread_self(), errNo++, mysql_error(&mySQL));
            abort();
        }
        else
        {
            secNo++;
            if(0 == secNo%100)
            {
                //                puts(tmp);
                printf("%lu:\t%d\tmysql_query ok!\n", pthread_self(), secNo);
            }
            MYSQL_RES *result = NULL;
            do
            {
                if(NULL != (result = mysql_store_result(&mySQL)))
                {
                    mysql_free_result(result);
                }
                else
                {
                    if(0 == mysql_field_count(&mySQL))
                    {
                        printf("%lld rows affected\n",
                               mysql_affected_rows(&mySQL));
                    }
                    else  /* some error occurred */
                    {
                        printf("Could not retrieve result set\n");
                        break;
                    }
                }
            }while(!mysql_next_result(&mySQL));
        }

        usleep(atoi(argv[6]));
    }

    mysql_close(&mySQL);
    mysql_library_end();
    return NULL;
}

int main(int argc, char*argv[])
{
    puts("main");
    if(8 != argc)
    {
        puts("program host user pass db port sleep statment");
        abort();
        return -1;
    }

    s_ARGS args;
    args.argc = argc;
    args.argv = argv;
    function(&args);
    //    pthread_t tmp;
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    if(0 != pthread_create(&tmp, NULL, function, (void *)&args))
    //    {
    //        perror("pthread_create");
    //        abort();
    //    }
    //    while(1)
    //    {
    //        sleep(1);
    //    }
    return 0;
}

MySQL 5.6.20
g++ MySQLClientO.cpp -I/usr/local/mysql/include/ -L/usr/local/mysql/lib/ -lmysqlclient

单数据库：
./a.out 192.168.1.196   ccc   ccc111111   smh  3306    0     "INSERT INTO sr_instructions(imei,version,type,imsi,other_1,other_2,content,add_time)VALUES('%015d','V01',1,'%019d','','','','2016-01-05 10:55:58');"
ks：
./a.out 192.168.1.196   kingshard   kingshard   device  9696    0     "INSERT INTO sr_instructions(imei,version,type,imsi,other_1,other_2,content,add_time)VALUES('%015d','V01',1,'%019d','','','','2016-01-05 10:55:58');"
报错：syntax error at position 172

[MySQLClientO.cpp.txt](https://github.com/flike/kingshard/files/78440/MySQLClientO.cpp.txt)

**Comment by flike** [comment]
请简化输入输出，保证能够重现。

**Comment by wnself** [comment]
function是为了多线程才独立出来的，代码里现在只有一个main线程，在function里 
   //生成两条插入语句
    sprintf(tmp+strlen(tmp), argv[7], rand(), rand());
    sprintf(tmp+strlen(tmp), argv[7], rand(), rand());
代表拼接了两个插入语句
