### ISSUE TITLE
关于分表方式的一点疑问

### ISSUE THREAD

**Issue by iyaozhen** [flike/kingshard#120]
有幸看到了 kingshard，决定研究、使用一下，但对分表策略那里有一些疑问。两种分表方式都是需要事先确定每个 node 的子表数（locations 字段），然后去各个 node 上面建立子表。但是数据是增长的，而且增长的很快（每天 3 亿条），这种业务场景一开始无法确定分表因子，而且需要在一个 node 上多建立一些子表或者增加 node，修改配置后，旧数据的查询应该会出现问题。

还有一个，我查阅之前的 issues 发现 ks 不支持批量 insert，这个会大大影响性能呀。特别是数据量很大的时候。

目前我是自己业务代码里面实现路由逻辑，baseTableName_yyyyMMdd_hashID 来分表（还没有支持分数据库），但需要数据查询方和数据插入方都实现路由逻辑，写死在代码里面，不利于维护，而且当业务量翻倍增长的时候无法很好的扩展。

抱歉说了那么多，不知道这种业务场景如何处理。

**Comment by flike** [comment]
有关数据增长很快的问题，如果要用kingshard并保持很好的性能。只能是每条建表basetable_yyyymmdd_xxxx，然后再利用kingshard的hash分表方式 。建表可以通过脚本实现。

批量插入是因为涉及到跨表操作，需要分布式事务保证一致性，所以kingshard目前没支持。后续打算通过非事务方式支持跨表更新（可以接受更新失败的风险的用户，可以使用该功能）。

**Comment by iyaozhen** [comment]
非常感谢这么快回复。

数据增长问题目前也就只能这么处理了。

希望 ks 能支持批量插入，一般来说还是不会失败的，能解释这个风险。

**Comment by iyaozhen** [comment]
又看了点资料发现，新增 node 以前的数据还能正确的查询得到是一致性hash中的单调性问题，不知道 ks 是否有支持的计划？

**Comment by flike** [comment]
这种情况建议分表的时候就分足够多的子表，当增加新node时，将部分子表copy过去。然后在kingshard里面改分表路由配置即可。

**Comment by yangwenmai** [comment]
后面你们是怎么批量插入处理的？没有用kingshard？

**Comment by iyaozhen** [comment]
@yangwenmai 我这边是业务代码里面实现了proxy的功能。插入数据的时候按照hash规则生成批量SQL
