### ISSUE TITLE
如何设置默认的chartype

### ISSUE THREAD

**Issue by luyaotang** [flike/kingshard#123]
因为在atlas中是支持默认建连接时会自动set names xx。目前需要连接池在重建是可以自动执行设置为gbk的。另外在使用altas时直接 show variables like '%server_id%',我就可以方便知道请求有没有被分配到不同的机器去，但目前配置好之后，发现这个指令是一直是写服务器的ID。有没有方便的方法来测试读写分离是否成功。

**Comment by flike** [comment]
1.有关字符集问题，kingshard默认字符集是utf8，如果想使用gbk的话，需要在发sql之前，执行一下set names gbk。不过你也可以使用kingshard的feature-charset分支，设置字符集，这个功能后续可能会加入到主分支中。
2.有关请求路由的问题，可以通过查看sql.log。

**Comment by luyaotang** [comment]
在评估使用kingshard的使用。因为程序有很多长连接，基本是在建立链接时设置字符集。如果我有1主2从，是我向kingshard发出现建立请求时，设置字符集，所有连接池中的连接都会修改？还是只有其中一个被修改到？如果只是一个会修改到那会比较影响使用。

**Comment by luyaotang** [comment]
在评估kingshard的使用。因为开发的程序有很多长连接，都是在建立链接时设置字符集。如果我有1主2从，是我向kingshard发出现建立请求时，设置字符集，是所有连接池中的连接都会修改？还是只有其中一个被修改到？如果只是一个会修改到那会比较影响使用。

**Comment by flike** [comment]
一个客户端只需要执行一次set names gbk。或者你用feature-charset分支，在配置中设置proxy_charset参数即可，不需要发set names gbk

**Comment by luyaotang** [comment]
好的。我测试下。

**Comment by flike** [comment]
字符集的功能已经合并到master分支了，现在不需要set names gbk了。：）
