### ISSUE TITLE
mysql/packetio.go ReadPacket 逻辑错误

### ISSUE THREAD

**Issue by xowenx** [flike/kingshard#128]
https://github.com/flike/kingshard/blob/master/mysql/packetio.go#L42-L78

`ReadPacket` 函数中
https://github.com/flike/kingshard/blob/master/mysql/packetio.go#L63
`io.ReadFull` 之前没有判断 `length` 是否大于 `MaxPayloadLen`

这意味着接下来
https://github.com/flike/kingshard/blob/master/mysql/packetio.go#L70-L76
这些逻辑会读到错误的数据

`ReadPacket` 在处理 `Packet` `length` 大于 `MaxPayloadLen` 应该会出错

**Comment by flike** [comment]
length := int(uint32(header[0]) | uint32(header[1])<<8 | uint32(header[2])<<16)
MaxPayloadLen 的值为 1<<24 - 1，length是不会大于MaxPayloadLen，最大是等于MaxPayloadLen
