### ISSUE TITLE
for jdbc/connector Handshake auth failure!

### ISSUE THREAD

**Issue by maxid** [flike/kingshard#13]
CalcPassword not match! detail:
2015/07/29 21:43:43 - INFO - server.go:[178] - [server] "NewServer" "Server running" "netProto=tcp|address=127.0.0.1:9696" conn_id=0
2015/07/29 21:43:50 - ERROR - conn.go:[221] - [ClientConn] "readHandshakeResponse" "error" "auth=[67 142 198 97 71 81 114 142 7 105 236 129 136 117 149 75 254 187 183 15]|checkAuth=[]|passworld=" conn_id=0
2015/07/29 21:43:50 - ERROR - conn.go:[96] - [server] "readHandshakeResponse" "ERROR 1045 (28000): Access denied for user '127.0.0.1:60394'@'kingshard' (using password: Yes)" "msg=read Handshake Response error" conn_id=10001
2015/07/29 21:43:50 - ERROR - server.go:[238] - [server] "onConn" "ERROR 1045 (28000): Access denied for user '127.0.0.1:60394'@'kingshard' (using password: Yes)" "" conn_id=0

**Comment by coolboyPT** [comment]
Did you fix this error? how do you do ? I also have such an error ~
