### ISSUE TITLE
提个小建议，能否整合wukong，实现分布式全文索引

### ISSUE THREAD

**Issue by munggruel** [flike/kingshard#131]
https://github.com/huichen/wukong
这个 golang 开发的 中文全文索引，支持配置制定字段，对 update 和 insert 执行字段 sql 语句 调用 全文索引 实时更新，然后 搜索时候 如果 是指定字段 可以 通过 全文索引 查到 指定 id，再分发sql

**Comment by flike** [comment]
这样做的意义是什么，还不太明白？

**Comment by munggruel** [comment]
mysql 全文索引不支持 非相关性以外的排序的，分布式排序 估计性能会 很差，所以必须用 sphinx 、lucence 等做排序，但是 sphinx 定制性差 ， lucence 一个庞大的 jvm容器让人望而生畏，在mysql proxy层面 实现 全文搜索 最合适了

**Comment by rfyiamcool** [comment]
@munggruel  推荐使用Elasticsearch ,在Mysql里做全文索引及插件扩展我们都有尝试过，最后还是使用elasticsearch解决.

**Comment by munggruel** [comment]
elasticsearch 性能 还是不太好，而且 引入java 意味着
1.一个庞大的jvm，一旦它运转起来 是一个庞大的黑盒
2.java代码 为了 解耦 ，代码冗余多，没有内聚设计
3.java 代码 跑benchmark 性能还可以，但是 一旦 实际应用 要慢的多，因为 java程序 太占内存，导致CPU cache 命中率下降，benchmark 总是执行同一段程序，所以还行，实际应用时候 要慢的多
4.java 代码 部署配置 非常繁杂，虽然开发压力小了，压力 其实都给了 运维

**Comment by yinheli** [comment]
@munggruel  哈, 这是对 java 的成见. 仅使用 RESTFul API, 另外官方也有多种 Client 供选择.

**Comment by munggruel** [comment]
如果对java没成见 可能就会去 用 Mycat了，也是 Mysql proxy，总得来讲 java 不是最优选择

**Comment by longxibendi** [comment]
mysql 5.6 fulltext 已经支持全文索引了
