### ISSUE TITLE
kingshard支持时间区间分表么？ 

### ISSUE THREAD

**Issue by rfyiamcool** [flike/kingshard#133]
这两天测试了kinghard大多数功能，hash跟range都很赞。  但我们这边的业务分表是基于时间区间的，可恨的是不是时间戳，而是datetime类型的.   过了下文档，貌似kingshard暂不支持time range分表是吧？

**Comment by rfyiamcool** [comment]
感谢陈菲同学 ! 

已经实现 [https://github.com/flike/kingshard/blob/master/doc/KingDoc/kingshard_date_sharding.md](url)

**Comment by darkz1984** [comment]
目前看到的按照年月日分表规则，表名要求必须是 table_name_YYYYMMDD 这样的，能否支持自定义使用年月日格式table_name_YYYY_MM_DD 或者是 table_name_YYYY-MM-DD ？
@rfyiamcool
