### ISSUE TITLE
安装错误了

### ISSUE THREAD

**Issue by 496080199** [flike/kingshard#141]
按照说明上make后就报错了，如下 麻烦看看是啥回事呢？

go build -ldflags "-X main.GitHash=`git rev-parse HEAD` -X main.BuildTime=`date '+%Y-%m-%d_%I:%M:%S%p'`" -o ./bin/kingshard ./cmd/kingshard
# github.com/flike/kingshard/cmd/kingshard
usage: 6l [options] main.6
  -1    use alternate profiling code
  -8    assume 64-bit addresses
  -B info
        define ELF NT_GNU_BUILD_ID note
  -C    check Go calls to C code
  -D addr
        data address
  -E sym
        entry symbol
  -I interp
        set ELF interp
  -L dir
        add dir to library path
  -H head
        header type
  -K    add stack underflow checks
  -O    print pc-line tables
  -Q    debug byte-register code gen
  -R rnd
        address rounding
  -S    check type signatures
  -T addr
        text address
  -V    print version and exit
  -W    disassemble input
  -X name value
        define string data
  -Z    clear stack frame on entry
  -a    disassemble output
  -c    dump call graph
  -d    disable dynamic executable
  -extld ld
        linker to run in external mode
  -extldflags ldflags
        flags for external linker
  -f    ignore version mismatch
  -g    disable go package data checks
  -installsuffix suffix
        pkg directory suffix
  -k sym
        set field tracking symbol
  -linkmode mode
        set link mode (internal, external, auto)
  -n    dump symbol table
  -o outfile
        set output file
  -r dir1:dir2:...
        set ELF dynamic linker search path
  -race
        enable race detector
  -s    disable symbol table
  -shared
        generate shared object (implies -linkmode external)
  -tmpdir dir
        leave temporary files in this directory
  -u    reject unsafe packages
  -v    print link trace
  -w    disable DWARF generation
make: *** [kingshard] 错误 2

**Comment by flike** [comment]
系统的版本，go版本分别是什么？可以去掉编译参数安装
`go build -o ./bin/kingshard ./cmd/kingshard`

**Comment by flike** [comment]
我使用你提供的命令，确实会编译报错。但我使用Makefile文件中的命令：`go build -ldflags "-X main.GitHash=`git rev-parse HEAD` -X main.BuildTime=`date '+%Y-%m-%d_%I:%M:%S%p'`" -o ./bin/kingshard ./cmd/kingshard`是可以正常编译的，你看看你的命令和这条命令的区别。

**Comment by 496080199** [comment]
昨天用 1.3-1.5 版本的go试了都不行，后来用 go 1.6编译成功

**Comment by flike** [comment]
恩，建议用Go1.6编译。

**Comment by 496080199** [comment]
readme写的是的go1.3版本以上，建议您在readme修正为1.6 谢谢

**Comment by flike** [comment]
好的。
