### ISSUE TITLE
使用limit做翻页查询时候，后台出现异常

### ISSUE THREAD

**Issue by phantasy1234** [flike/kingshard#142]
select * from table where uid = ** limit m,n  
当m超过count(*)的时候，后台报错

`2016/03/23 11:01:21 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: slice bounds out of range" "stack=goroutine 144627444 [running]:
github.com/flike/kingshard/proxy/server.func·002()
        /tmp/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f8
runtime.panic(0x65afa0, 0x9cddaa)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x106
github.com/flike/kingshard/proxy/server.(*ClientConn).limitSelectResult(0xc210529780, 0xc2103029b0, 0xc2101d7e70, 0x0, 0x0)
        /tmp/src/github.com/flike/kingshard/proxy/server/conn_select.go:431 +0x508
github.com/flike/kingshard/proxy/server.(*ClientConn).mergeSelectResult(0xc210529780, 0xc2100a5b60, 0x1, 0x1, 0xc2101d7e70, ...)
        /tmp/src/github.com/flike/kingshard/proxy/server/conn_select.go:152 +0xd5
github.com/flike/kingshard/proxy/server.(*ClientConn).handleSelect(0xc210529780, 0xc2101d7e70, 0x0, 0x0, 0x0, ...)
        /tmp/src/github.com/flike/kingshard/proxy/server/conn_select.go:127 +0x411
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc210529780, 0xc21040d2d1, 0x42, 0x0, 0x0)
        /tmp/src/github.com/flike/kingshard/proxy/server/conn_query.go:71 +0x92b
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc210529780, 0xc21040d2d1, 0x43, 0x43, 0x0, ...)
        /tmp/src/github.com/flike/kingshard/proxy/server/conn.go:312 +0x3fd
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc210529780)
        /tmp/src/github.com/flike/kingshard/proxy/server/conn.go:286 +0xa5
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc210001c60, 0x7f8c6991a480, 0xc2103cc9c8)
        /tmp/src/github.com/flike/kingshard/proxy/server/server.go:339 +0x22c
created by github.com/flike/kingshard/proxy/server.(*Server).Run
        /tmp/src/github.com/flike/kingshard/proxy/server/server.go:531 +0x141
|sql=select * from table where u_id = 2506 limit 1510, 20" conn_id=0
`

**Comment by flike** [comment]
好的，会尽快修复的。
