### ISSUE TITLE
反馈kingshard的limit问题

### ISSUE THREAD

**Issue by phantasy1234** [flike/kingshard#143]
我最近在mysql的slow log 发现很多这样的查询

`Query_time: 1.199735  Lock_time: 0.000064 Rows_sent: 7777  Rows_examined: 15588
SET timestamp=1459002386;
select item_id from t_user_like_0018 where u_id = 448237 and effective = 1 order by id desc;`

而我们在代码里的查询语句是这样的：
`select item_id from t_user_like_0018 where u_id = 448237 and effective = 1 order by id desc limit 0,20;`

很显然是kingshard的limit是自己处理的，这样的确是分表的情况下一种无奈的做法，但是就导致load了7777条结果

因为我们现在是通过u_id分表的，我不知道这种做法是否可行，在不垮节点的情况下（也就是查询条件里面带有分表字段的情况下），limit避免在kingshard这边完成

非常感谢！

**Comment by flike** [comment]
把全部数据load过来，是因为按照id排序了，这样如果不全部load数据排序会有问题。

**Comment by phantasy1234** [comment]
嗯，如果是跨节点的情况下肯定会有问题，不垮节点的情况下，也就是单节点查询时，应该不会有问题呀

**Comment by flike** [comment]
单节点跨子表一样会存在这样问题。

**Comment by phantasy1234** [comment]
哦，我没说清楚，应该是单节点单字段，也就是我的where条件里面已经带分表字段

**Comment by flike** [comment]
这样的话limit 会交给mysql去做，不会把数据全部load到kingshard中。

**Comment by phantasy1234** [comment]
我现在用u_id做分片字段
查询语句：
`select item_id from t_user_like_0018 where u_id = 448237 and effective = 1 order by id desc limit 0,20;`

理论上是单表的查询，但是在kingshard的slow-log里，把这个查询语句分解成
`select item_id from t_user_like_0018 where u_id = 448237 and effective = 1 order by id desc;`

**Comment by flike** [comment]
恩，明白了你的意思，这个地方我需要优化一下kingshard，如果是单表SQL，limit 需要下发到mysql。

**Comment by phantasy1234** [comment]
非常感谢

**Comment by sunnyfun888** [comment]
每个涉及到的分片取前20条，合并为一个集合后排序，分页，这样有问题吗

**Comment by sunnyfun888** [comment]
每个涉及到的分片取前20条，合并为一个集合后排序，分页，这样有问题吗

**Comment by sunnyfun888** [comment]
每个涉及到的分片取前20条，合并为一个集合后排序，分页，这样有问题吗

**Comment by sunnyfun888** [comment]
每个涉及到的分片取前20条，合并为一个集合后排序，分页，这样有问题吗

**Comment by sunnyfun888** [comment]
每个涉及到的分片取前20条，合并为一个集合后排序，分页，这样有问题吗

**Comment by flike** [comment]
有问题，某个记录里面的前20条，有可能整个结果集中是最小的。

**Comment by sunnyfun888** [comment]
我的意思是有限制地合并为一个集合后排序。假设分页为limit 0,20，如果涉及4个分片，每个分片取20条，合并后有80条，然后排序，分页。如果不是第一页，比如第二页，就把相关分片的第一、二页取出，合并后排序，分页。这样比没限制全load强吧。

**Comment by flike** [comment]
假设分页为limit 0,20,你这种方式是可以的。但如果是limit 20,40，这样的处理可能就有问题。

**Comment by smallrock** [comment]
请问，这个问题，现在的处理结果是什么？

**Comment by smallrock** [comment]
@flike

**Comment by smallrock** [comment]
@flike 好的，谢谢

**Comment by sunnyfun888** [comment]
如果请求到是limit 20,40，proxy将其变成limit 0,40转到分片，然后汇总后在proxy排序、分页。这样有问题？

**Comment by sunnyfun888** [comment]
如果请求到是limit 20,40，proxy将其变成limit 0,40转到分片，然后汇总后在proxy排序、分页。这样有问题？

**Comment by sunnyfun888** [comment]
如果请求到是limit 20,40，proxy将其变成limit 0,60转到分片，然后汇总后在proxy排序、分页。这样有问题？

**Comment by flike** [comment]
@sunnyfun888 ,这个主意不错。:)

**Comment by sunnyfun888** [comment]
如果在数据量太大的时候使用外排序的话，会更好，否则有内存耗尽的风险。

**Comment by flike** [comment]
已经按照@sunnyfun888的思路实现了。fixed

**Comment by imiskolee** [comment]
这个时候，其实需要的不是select语义，而是scan语义。
