### ISSUE TITLE
是否可以支持多维度分表，小表同步

### ISSUE THREAD

**Issue by kunchong21** [flike/kingshard#153]
1：例如：表a ｛字段1，字段2、。。。。｝
现在针对字段1进行分表  但有需求针对字段二进行查询  这时候就不能查了。是否可以在insert的时候针对不同分表规则来进行同时插入两张表 
2：因为里面已经实现分表跟非分表的join 是否可以实现小表（非分表）同步功能【同步操作两个表的操作】 这样在不同node可以关联查询。
有同样需求的同学？？

**Comment by bigpyer** [comment]
1.针对字段1进行分表，可以针对字段二进行查询，目前已经支持。
2.不同形式的分表join都比较难做，暂时不考虑了吧。

**Comment by flike** [comment]
正如@bigpyer所说，需求1已经支持。有关需求2，目前kingshard可以支持这种小表join查询，但小表同步需要用户自己去做。
