### ISSUE TITLE
开慢查询时无法记录错误的sql

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#154]
比如设置slow_log_time为100， 执行select * from table_not_exist，日志里只会说该表不存在，并不会记录该sql，只有slow_log_time关掉才行。

**Comment by bigpyer** [comment]
错误日志是记录在sys.log中的。

**Comment by wangcn** [comment]
错误信息是在sys.log里，但并没有出错是sql。这样我就不知道具体是为什么出错。

**Comment by bigpyer** [comment]
@flike  找个可以考虑加上吗？应该是这个地方可以记录一下https://github.com/flike/kingshard/blob/master/proxy/server/conn_query.go#L55

**Comment by flike** [comment]
@bigpyer , 我加一下。：）
