### ISSUE TITLE
kingshard 怎么做二级映射

### ISSUE THREAD

**Issue by munggruel** [flike/kingshard#155]
kingshard 怎么做二级映射
一个 论坛帖子，包括 回复，回复 会有评论
帖子主题 和 回复 会有 附件 

如果 topic reply floor attach 均 按 tid 分表
会导致 有些 tid 对应的表 reply 、 floor  、attach 过大 (因为有些帖子会很多回复和附件）

如果不按 tid分表，又会 太多 跨库 跨表查询

二级映射 怎么做，有人能举个 kingshard 配置例子说明下么

**Comment by flike** [comment]
将tid按照hash分表，每个子表数据应该会比较均匀。
