### ISSUE TITLE
查询时不支持force index(primary) 语法

### ISSUE THREAD

**Issue by phantasy1234** [flike/kingshard#158]
我设置了force index(primary) ，但是在转发请求时，force index(primary)被过滤掉了

**Comment by bigpyer** [comment]
1.是分表场景还是非分表场景?
2.提供下当时的操作结果、日志截图或者可以reduce的命令、建表等

**Comment by rajaluo** [comment]
请问kingshard对force index支持怎么样，我的sql好像也被过滤掉force index了

**Comment by rajaluo** [comment]
请问这个问题结论是什么，我也遇到了
