### ISSUE TITLE
source or input redirect execute sql infile cause hang up

### ISSUE THREAD

**Issue by martianzhang** [flike/kingshard#160]
## test.sql content
create table test (a int) engine=innodb;
LOCK TABLES `test` WRITE;
/*!40000 ALTER TABLE `test` DISABLE KEYS */;

## hangup reproduce command
mysql -uroot -p test -f < test.sql

## show processlist; get following ouput
| 902 | kingshard | localhost:35955 | kingshard | Query   |    0 | starting                        | show processlist                            |         0 |             0 |
| 903 | kingshard | localhost:35956 | NULL      | Sleep   |    8 |                                 | NULL                                        |         0 |             0 |
| 904 | kingshard | localhost:35957 | kingshard | Sleep   |   17 |                                 | NULL                                        |         0 |             0 |
| 905 | kingshard | localhost:35958 | kingshard | Sleep   |   17 |                                 | NULL                                        |         1 |             0 |
| 906 | kingshard | localhost:35959 | kingshard | Sleep   |   17 |                                 | NULL                                        |         0 |             0 |
| 907 | kingshard | localhost:35960 | kingshard | Sleep   |   16 |                                 | NULL                                        |         0 |             0 |
| 908 | kingshard | localhost:35961 | kingshard | Query   |   16 | Waiting for table metadata lock | /*!40000 ALTER TABLE `test` DISABLE KEYS */ |         0 |             0 |
| 909 | kingshard | localhost:35962 | NULL      | Sleep   |   56 |                                 | NULL                                        |         0 |             0 |
| 910 | kingshard | localhost:35963 | NULL      | Sleep   |   56 |                                 | NULL                                        |         0 |             0 |
+-----+-----------+-----------------+-----------+---------+------+---------------------------------+---------------------------------------------+-----------+---------------+

## mysql general log file output
2016-05-04T12:23:44.644017Z  906 Query  create table test (a int) engine=innodb
2016-05-04T12:23:45.166098Z  907 Init DB        kingshard
2016-05-04T12:23:45.188033Z  907 Query  LOCK TABLES `test` WRITE
2016-05-04T12:23:45.467035Z  908 Init DB        kingshard
2016-05-04T12:23:45.489100Z  908 Query  /*!40000 ALTER TABLE `test` DISABLE KEYS */

**Comment by martianzhang** [comment]
If all sql in test.sql are in one transaction, problem can be avoid.

**Comment by bigpyer** [comment]
a: create table test (a int) engine=innodb;
b: LOCK TABLES test WRITE;
c: /*!40000 ALTER TABLE test DISABLE KEYS */;

NOT IN TRANSACTION:
a,b and c will execute in three different backend mysql connections, so, b and c will complete for one write lock

IN TRANSACTION:
a,b and c will execute in the same backend mysql connection, b and c is not competitor, then the problem is can be avoid

so, if you have to use sql like this, make sure they are in one transaction.

**Comment by martianzhang** [comment]
It's better to make a swither, which can let queries use the same backend connection.

**Comment by flike** [comment]
@martianzhang ,This feature will make kingshard more and more complex. I want kingshard to be used simply.
