### ISSUE TITLE
兼容 ORM sql 语句格式

### ISSUE THREAD

**Issue by nqzhang** [flike/kingshard#165]
发现有问题额 clone的最新的代码
kingshard的log日志
select search_hash.id, search_hash.info_hash, search_hash.category, search_hash.data_hash, search_hash.name, search_hash.extension, search_hash.classified, search_hash.source_ip, search_hash.tagged, search_hash.length, search_hash.create_time, search_hash.last_seen, search_hash.requests, search_hash.comment, search_hash.creator from search_hash_0003 where search_hash.id in (95982)
2016/05/13 00:45:58 - ERROR - conn_select.go:[125] - [ClientConn] "handleSelect" "ERROR 1054 (42S22): Unknown column 'search_hash.id' in 'field list'" "" conn_id=10144

原始sql应该是这样的
select search_hash.id, search_hash.info_hash, search_hash.category, search_hash.data_hash, search_hash.name, search_hash.extension, search_hash.classified, search_hash.source_ip, search_hash.tagged, search_hash.length, search_hash.create_time, search_hash.last_seen, search_hash.requests, search_hash.comment, search_hash.creator from search_hash where search_hash.id in (95982)

**Comment by nqzhang** [comment]
程序是django的，但是django他的models.Manager 自带的就是这种语法
前面会把表名带进去........

**Comment by nqzhang** [comment]
django这边的报错是这样的

**Comment by flike** [comment]
明白，这个bug会尽快修复的。谢谢反馈。

**Comment by flike** [comment]
fixed.

**Comment by nqzhang** [comment]
还是一样的报错......

**Comment by nqzhang** [comment]
select search_hash.id, search_hash.info_hash, search_hash.category, search_hash.data_hash, search_hash.name, search_hash.extension, search_hash.classified, search_hash.source_ip, search_hash.tagged, search_hash.length, search_hash.create_time, search_hash.last_seen, search_hash.requests, search_hash.comment, search_hash.creator from search_hash_0003 where search_hash.id in (44090)

**Comment by nqzhang** [comment]
是clone的最新的代码
drwxr-xr-x 2 root root   151 May 14 11:46 backend
drwxr-xr-x 2 root root    22 May 14 11:47 bin
drwxr-xr-x 3 root root    22 May 14 11:46 cmd
drwxr-xr-x 2 root root    43 May 14 11:46 config
drwxr-xr-x 6 root root    53 May 14 11:46 core
-rwxr-xr-x 1 root root   517 May 14 11:46 dev.sh
drwxr-xr-x 4 root root    34 May 14 11:46 doc
drwxr-xr-x 2 root root    39 May 14 11:49 etc
-rw-r--r-- 1 root root   291 May 14 11:46 genver.sh
-rwxr-xr-x 1 root root   285 May 14 11:46 Makefile
drwxr-xr-x 2 root root  4096 May 14 11:46 mysql
drwxr-xr-x 4 root root    32 May 14 11:46 proxy
-rw-r--r-- 1 root root  2055 May 14 11:46 README.md
-rwxr-xr-x 1 root root  3736 May 14 11:46 README_ZH.md
drwxr-xr-x 2 root root   142 May 14 11:46 sqlparser
drwxr-xr-x 2 root root    47 May 14 11:46 sqltypes
-rw-r--r-- 1 root root 91737 May 14 11:47 y.output

**Comment by nqzhang** [comment]
配置文件

addr : 0.0.0.0:9696
user :  root
password : ******
log_level : debug
log_sql: on
nodes :
- 
    name : node1 
    max_conns_limit : 100
    user :  root
    password : ******
    master : 192.168.0.1:3306
    down_after_noalive : 32

schema :
    db : ssbc
    nodes: [node1]
    default: node1      
    shard:
    -   
        table: search_filelist
        key: info_hash
        nodes: [node1]
        type: hash
        locations: [4]

    -   
        table: search_hash
        key: info_hash
        type: hash
        nodes: [node1]
        locations: [4]

**Comment by flike** [comment]
```
mysql> select test_shard_hash.id,test_shard_hash.e  from test_shard_hash where test_shard_hash.id > 1;
+-----+-------+
| id  | e     |
+-----+-------+
|  32 | test1 |
|  48 | test1 |
|  56 | test1 |
|  64 | test1 |
|  72 | test1 |
|  80 | test1 |
| 640 | test1 |
| 720 | test1 |
| 800 | test1 |
|  17 | test1 |
|  10 | test1 |
|   3 | test1 |
|  13 | test1 |
|   7 | test1 |
+-----+-------+
14 rows in set (0.03 sec)
```
我在本地执行类似的SQL是可以的，你是否重新编译过代码？

**Comment by nqzhang** [comment]
是重新编译的

**Comment by nqzhang** [comment]
cd /www/ && mkdir kingshard && cd kingshard
git clone https://github.com/flike/kingshard.git src/github.com/flike/kingshard
cd src/github.com/flike/kingshard
source ./dev.sh
make

我是这样操作的  然后把src目录整个删了重新clone 的

**Comment by flike** [comment]
方便加个QQ吗？我的是：569732821。我帮你看看。

**Comment by nqzhang** [comment]
好了  谢谢  谢谢

**Comment by nqzhang** [comment]
又发现新的问题............
		 1126 Query	select search_hash_0003.id, search_hash_0003.info_hash, search_hash_0003.category, search_hash_0003.data_hash, search_hash_0003.name, search_hash_0003.extension, search_hash_0003.classified, search_hash_0003.source_ip, search_hash_0003.tagged, search_hash_0003.length, search_hash_0003.create_time, search_hash_0003.last_seen, search_hash_0003.requests, search_hash_0003.comment, search_hash_0003.creator from search_hash_0003 where id = 547557 order by search_hash.id asc

order 后面是不是也要拦截成 search_hash_0003

**Comment by huacnlee** [comment]
```sql
Unknown column 'orders.id' in 'order clause': SELECT  `orders`.* FROM `orders` ORDER BY `orders`.`id` ASC LIMIT 1
```
