### ISSUE TITLE
when DBA kill connection which in transaction, kingshard should tell client backend connection close.

### ISSUE THREAD

**Issue by martianzhang** [flike/kingshard#166]
MySQL [(none)]> begin;
Query OK, 0 rows affected (0.00 sec)

// in another session DBA kill transaction connections
// following transaction query should be told backend connection closed
// so that client program can catch this exception, don't send any left queries in this transaction blind.

MySQL [(none)]> select 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

----------------------

MySQL [(none)]> begin;
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> select 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

MySQL [(none)]> select 1;
ERROR 1105 (HY000): connection was bad
MySQL [(none)]> select 1;                                                                                
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    10002
Current database: *** NONE ***

+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

**Comment by flike** [comment]
Thank you for your feedback and pr, I'll check this problem later. :)

**Comment by flike** [comment]
done.
