### ISSUE TITLE
关于新增节点数据迁移的问题

### ISSUE THREAD

**Issue by nqzhang** [flike/kingshard#168]
我现在是单node 单mysql实例 里面分的表  有两个表都是使用的hash方式分的4个子表 
如果我新加一个node 在这个node新建4个子表
那么hash方式的分表会导致数据写入和读取出问题么

**Comment by flike** [comment]
会有问题，所以尽量在一开始分足够多的子表。避免rehash。
假如shardkey有如下：1，2，3，4，5，6，7，8.之前6会被route到table_0002，分成8张子表后会路由到table_0006.
