### ISSUE TITLE
插入emoj表情时，最终插入数据库会变成乱码

### ISSUE THREAD

**Issue by phantasy1234** [flike/kingshard#169]
我在配置文件设置了proxy_charset: utf8mb4,理论上所有的节点都支持😀 😬 😁 😂 😃 😄 😄💦 😌 😇 😉 😊 🙂 🙃 ☺️ 😊 😌 😍 😘这样的符号
但是发现程序发送到schema default的节点不会乱码，发送到其它node的全部会转为？
在控制台用insert into 直接插入又是好的

**Comment by flike** [comment]
fixed.
