### ISSUE TITLE
插入数据时insert error (1105, 'insert or replace must specify columns')

### ISSUE THREAD

**Issue by nqzhang** [flike/kingshard#172]
数据列都是指定了的
表格式如下
CREATE TABLE `search_filelist_0000` (
  `info_hash` varchar(40) NOT NULL,
  `file_list` longtext NOT NULL,
  PRIMARY KEY (`info_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;
其中info_hash为分表字段

直连数据库可以插入
INSERT INTO search_filelist VALUES('a2528f48516ee12ba3b99d0124af00888bd618c2','[{"path": "Rosetta Stone 4.5.5 + Crack.exe", "length": 29716954}]');
Query OK, 1 row affected (0.00 sec)

通过kingshard
 INSERT INTO search_filelist VALUES('a2528f48516ee12ba3b99d0124af00888bd618c2','[{"path": "Rosetta Stone 4.5.5 + Crack.exe", "length": 29716954}]');
ERROR 1105 (HY000): insert or replace must specify columns

kingshard日志
2016/05/22 04:59:09 - ERROR - conn.go:[290] - [server] "Run" "insert or replace must specify columns" "" conn_id=10031

**Comment by nqzhang** [comment]
并且它基本上是成功一条或者两条 就会这样失败一次

**Comment by flike** [comment]
1.目前kingshard不支持非整型的分表字段。
2.kingshard要求，分表时insert必须带上字段名。

**Comment by nqzhang** [comment]
好吧，后面没有加字段名字，解决了
 谢谢
