### ISSUE TITLE
hash分表下做count查询时，如果带了limit，会返回空结果集。

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#174]
比如comment表，按文章id做hash分表，执行select count(1) from comment where article_id = xxx limit 1时，无返回;去掉limit则正常。

暂时只试了hash分表，尚不清楚其他分表模式下是否正常。

版本是6ef162720d420714e77828bd3020a65881c65b66

**Comment by flike** [comment]
谢谢反馈，我会尽快确认这个问题。

**Comment by flike** [comment]
fixed
