### ISSUE TITLE
采用hash分表时，能否增加一个选项，表明hash key是整形？

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#178]
php的pdo中除非在bindValue时指定整形，转义后都会对值加上引号。然后kingshard会将其作为字符串计算hash。
能否在配置强制指定分表字段的类型？

**Comment by flike** [comment]
目前只支持整型分表，后续我会考虑字符串分表，那时候才会修复你说的问题。所以目前只能靠bindValue制定类型。

**Comment by kylidboy** [comment]
hash的算法是什么？

**Comment by xluohome** [comment]
@wangcn  可以看  https://github.com/flike/kingshard/tree/feature-hash 分支，  支持 where id=1  与 where id="1" 时  id  hash 值一样。

**Comment by flike** [comment]
support
