### ISSUE TITLE
无法通过mysql命令行连接控制台 提示 No database selected

### ISSUE THREAD

**Issue by gloomyzerg** [flike/kingshard#179]
重新启动kingshard后可以正常连接,应用接入后就报错 No database selected

kingshard 大量报错  sys.log日志如下

2016/06/08 12:53:07 - ERROR - conn.go:[337] - [ClientConn] "dispatch" "command 9 not supported now" "" conn_id=0
2016/06/08 12:53:07 - ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): command 9 not supported now" "" conn_id=10001
2016/06/08 12:53:07 - ERROR - conn.go:[337] - [ClientConn] "dispatch" "command 9 not supported now" "" conn_id=0
2016/06/08 12:53:07 - ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): command 9 not supported now" "" conn_id=10001
2016/06/08 12:53:07 - ERROR - conn.go:[337] - [ClientConn] "dispatch" "command 9 not supported now" "" conn_id=0
2016/06/08 12:53:07 - ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): command 9 not supported now" "" conn_id=10001
2016/06/08 12:53:07 - ERROR - conn.go:[337] - [ClientConn] "dispatch" "command 9 not supported now" "" conn_id=0
2016/06/08 12:53:07 - ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): command 9 not supported now" "" conn_id=10001
2016/06/08 12:53:07 - ERROR - conn.go:[337] - [ClientConn] "dispatch" "command 9 not supported now" "" conn_id=0
2016/06/08 12:53:07 - ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): command 9 not supported now" "" conn_id=10001
2016/06/08 12:53:07 - ERROR - conn.go:[337] - [ClientConn] "dispatch" "command 9 not supported now" "" conn_id=0
2016/06/08 12:53:07 - ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): command 9 not supported now" "" conn_id=10001

**Comment by gloomyzerg** [comment]
No database selected 问题已找到
配置文件 未设置默认db 设置后正常
日志依然报错  运行一段时间后 kingshard 停止服务

**Comment by bigpyer** [comment]
1.配置文件需要设置默认db。
2.这个的报错应该是你通过某种客户端工具连接的ks，目前ks不支持这个命令(mysqladmin status)。

**Comment by gloomyzerg** [comment]
我使用的是PHP 的PDO 连接
command 9   具体的命令是? mysqladmin status 这个吗?

**Comment by flike** [comment]
解决了吗?

**Comment by gloomyzerg** [comment]
解决了  找到那个命令了  
程序上使用了 PDO::ATTR_SERVER_INFO  来获取服务器状态了 
还有一个问题就是 slave 里面配置的 mysql实例必须全部正常才能启动  而且是有一个正常就可以
是这样设定的吗

**Comment by flike** [comment]
@gloomyzerg 启动的时候要求全部正常，不正常说明配置有问题（实现策略而已）。但运行的时候slave宕机是不影响服务的。

**Comment by gloomyzerg** [comment]
@flike 明白了  因为我们有多台mysql实例  kingshard是用docker来实现自动伸缩的  所以有时启动更多kingshard的时候不能保证所有slave都正常工作 
这个我看到控制台的动态上下线的命令了 我再想其他办法来实现动态增减吧
谢谢你的帮助

**Comment by flike** [comment]
不客气。@gloomyzerg
