### ISSUE TITLE
error with show full fields from 

### ISSUE THREAD

**Issue by zsounder** [flike/kingshard#180]
Query with "SHOW FULL FIELDS FROM TABLE_NAME", will produce error : "ERROR 1146 (42S02): Table 'TABLE_NAME' doesn't exist". Not Use mysql_select_db.

**Comment by flike** [comment]
没有选择DB吧

**Comment by zsounder** [comment]
try it your self, no problem with  insert and select, i'm trying to fix it.

**Comment by flike** [comment]
send 'use db' before send "SHOW FULL FIELDS FROM TABLE_NAME"

**Comment by sysmate** [comment]
SHOW FULL FIELDS AND SHOW FULL COLUMNS doesn't work for me, i tried with and without use db statement before.

**Comment by flike** [comment]
fixed
