### ISSUE TITLE
当查询条件中in的元素过多，导致大量慢查询

### ISSUE THREAD

**Issue by phantasy1234** [flike/kingshard#183]
当查询条件中带有有分表字段 in的查询时，kingshard会根据分表字段 路由到对应的表，但是查询条件不会做修改被下发到对应的table，举个例子：
shard key：u_id
shard table count :1000
sql:select * from table where u_id in (ids)
proxy：select * from table[1-n] where u_id in (ids)
最终会根据ids下发到对应的table ，但是如果说这个ids的数量达到一定量值时，在单表的查询会比较慢，但是一旦下发到多张表后，就会出现大量慢查询，而且是同时发生的，mysql 的cpu会出现陡增，我建议是kingshard 下发sql时能够根据分区重新分配id，将大量的ids的in查询拆解成若干个小量的ids的in查询

**Comment by flike** [comment]
fixed
