### ISSUE TITLE
分表的表与未分表的表join报错

### ISSUE THREAD

**Issue by Jacklli** [flike/kingshard#191]
mysql> select * from test;
+------+
| id   |
+------+
|    2 |
|    3 |
+------+
2 rows in set (0.00 sec)

mysql> select * from test1;
+------+
| id   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql> select test.id,test1.id from test join test1 on (test.id=test1.id);
ERROR 1054 (42S22): Unknown column 'test.id' in 'on clause'
mysql> select test.id,test1.id from test join test1;
+------+------+
| id   | id   |
+------+------+
|    2 |    1 |
|    3 |    1 |
+------+------+
2 rows in set (0.06 sec)

以下是分表信息：
mysql> admin server(opt,k,v) values('show','schema','config');
+-----------+-------+---------+------+--------------+-----------+---------------+
| DB        | Table | Type    | Key  | Nodes_List   | Locations | TableRowLimit |
+-----------+-------+---------+------+--------------+-----------+---------------+
| kingshard |       | default |      | node1        |           | 0             |
| kingshard | test  | hash    | id   | node1, node2 | 4, 4      | 0             |
+-----------+-------+---------+------+--------------+-----------+---------------+

**Comment by flike** [comment]
把on改成where试试。

**Comment by flike** [comment]
改写成：`select test.id,test1.id from test as a join test1 as b on a.id=b.id;`就可以支持
目前kingsharad支持的join操作必须满足以下两个条件：
1. from后面必须跟分表名。
2. on操作需要用as 后的字符，比如类似于on a.id=b.id

**Comment by Jacklli** [comment]
能否把第1点限制取消呢？如果做到不写分表名就能直接join就棒棒哒了。
另外，现网应用有很多代码的别名后面没有as关键字，能否支持不写as的别名模式呢（SQL标准支持的）。

**Comment by flike** [comment]
:),正在想办法改进这一点（昨天完成了部分功能）。目前用的话，只能按照上面两点要求来。
