### ISSUE TITLE
如何在只有一个node时不指定range或date_range

### ISSUE THREAD

**Issue by charmfocus** [flike/kingshard#192]
因在单独一台服务器上使用kingshard,只有一个node，如果按日期分表，可能后期程序会不断的新建子表，这时配置文件中的range就不正确了，能否不需要配置range让其自动识别？或所有子表都分到其中一个node上，并不需要后期不断修改其配置？

**Comment by flike** [comment]
我觉得按时间分表，你一次把一年的相关配置都写好，然后一年变更一次配置，这种频率应该可以接受吧。

**Comment by charmfocus** [comment]
那就是预分配了，但在使用SELECT * FROM xxx 时，会发现有未创建的表如“xxx_201612”不存在，这应该是查询自动按配置上的range进行查询所有配置好的表了，但配置好的表可能并不存在。解决这个我需要手工创建所有的range中配置好的表

**Comment by flike** [comment]
是的。你可以先建好表。
