### ISSUE TITLE
select查询对And/Or的优先级处理有些问题，导致结果出错

### ISSUE THREAD

**Issue by jianjunliu** [flike/kingshard#196]
假如有这样一张表：
mysql> select * from test_shard_hash;
+----+------+-------+
| id | name | price |
+----+------+-------+
|  1 | abc  |   1.1 |
|  2 | abc  |   1.2 |
+----+------+-------+
将这张表按id%2切分为两个分片（t_0000,t_0001）。id=1的记录在t_0001， id=2的记录在t_0000

执行以下查询：
select * from test_shard_hash where id=2 or name='a' and id=1;   
ks返回结果为0， 但正确的应该返回 
|  2 | abc  |   1.2 |

经过抓包显示， kingshard只往t_0001这个分片发了select请求。所以导致这个问题。

**Comment by flike** [comment]
是的。这需要支持优先级，目前分表的情况下，where后面的条件尽量简单。

**Comment by flike** [comment]
fixed. :)
