### ISSUE TITLE
hash模式，select用orderby的话，每个片单独排序，合并后不排序的问题

### ISSUE THREAD

**Issue by harrybi** [flike/kingshard#201]

**Comment by flike** [comment]
好，我有空确认一下这个问题。谢谢反馈。

**Comment by harrybi** [comment]
我测了下，SQLDB中用decimal的时候，由于kingshard中转换为byte，所以在sort的时候用指针地址比较的，造成排序不准确，请问下这个decimal一定要转成byte吗？

**Comment by flike** [comment]
你可以研究一下，最好能够提个pr，fix掉。谢谢

**Comment by flike** [comment]
fixed
