### ISSUE TITLE
分表规则的几点疑问

### ISSUE THREAD

**Issue by maodanp** [flike/kingshard#202]
打算迁移原有的mysql，有几点疑问想确认下：
1. 对于`auto_increment`的`id`，是否不能使用该字段作为分表规则？或者说分表规则的字段是否必须要显式的通过`INSERT`语句给出？
2. 对于`RANGE`模式，如果数据超过了 `table_row_limit` * `子表个数` ；那数据还会存储么？还是报错提示？ 
3. 对于通过[管理端命令修改配置](https://github.com/flike/kingshard/blob/master/doc/KingDoc/admin_command_introduce.md)，原先配置文件应该还是静态的，没有改动。管理端命令修改配置是否是临时的？是否能更新**配置文件**？

**Comment by flike** [comment]
1.是的。
2.会报错，需要使用者保证表存在。
3.调研`admin server(opt,k,v) values('save','proxy','config')`保存配置。
