### ISSUE TITLE
sql 重组bug

### ISSUE THREAD

**Issue by mars79668** [flike/kingshard#205]
sql 重组后 字段名都没有使用 `` 符号 ，这样会在 字段名含有特殊字符时报错，例如  源sql 语句
select `a-b`,`c-d` from test; 重组后变为
select a-b,c-d from test_2016;  应该是  select `a-b`,`c-d` from `test_2016`;

**Comment by flike** [comment]
建议不要用特殊字符，支持这个特性对SQL解析改动比较大。
