### ISSUE TITLE
多用户支持

### ISSUE THREAD

**Issue by weiwei99** [flike/kingshard#206]
我们对不同上游业务来访问数据库分配了不同的用户，但是kingshard只支持配置一份用户密码，这样我们使用时就需要启动多实例，请问是否考虑在一个实例里支持配置多用户？

**Comment by flike** [comment]
多个用户权限全部相同，访问的库和表是否相同？能否详细描述一下使用场景

**Comment by weiwei99** [comment]
通过给不同的上游分配不同的用户名，可以做到更精细的控制，例如访问控制，审计，性能跟踪等

**Comment by ly188128934** [comment]
请问有计划什么时候支持多用户么。我们现在微服务环境，每个服务配置一个数据库用户，一个环境就要起几十个kingshard进程。

**Comment by boddiguo** [comment]
我们也在调研mysql proxy，发现kingshard缺少多用户的支持，现在公司的系统也是微服务化，已经有很多数据库和schema，需要多个用户来做到权限控制。
