### ISSUE TITLE
遇到如下错误，当重启kingshard后此错误就没有了

### ISSUE THREAD

**Issue by jefjin** [flike/kingshard#209]
ERROR - conn.go:[334] - [ClientConn] "dispatch" "command 17 not supported now" "" conn_id=0
2016/07/19 18:47:08 - ERROR - conn.go:[287] - [server] "Run" "ERROR 1105 (HY000): command 17 not supported now" "" conn_id=10009

**Comment by flike** [comment]
如何重现？负责没法定位问题

**Comment by martianzhang** [comment]
command 17对应的是COM_CHANGE_USER.
用mysqltest工具跑一下change_user这个test case可以复现。
对应C的API函数是mysql_change_user。
