### ISSUE TITLE
格式化的sql语句报错

### ISSUE THREAD

**Issue by yunkaiyueming** [flike/kingshard#210]
我使用KingShard的按年分表时候，分表的执行没有格式化的sql语句是可以正常查询的，执行了格式化的就报“ERROR 1146 (42S02): Table 'xx' doesn't exist”，没有分表的执行格式化的sql语句也是正常的，这是什么问题？

**Comment by flike** [comment]
SQL是什么？只有结论定位问题比较困难。

**Comment by yunkaiyueming** [comment]
没有格式化的sql: select vip1 from `data_user_loss_copy` where date = '2016-07-18';
格式化的：select vip1
from `data_user_loss_copy` 
where date = '2016-07-18';

**Comment by gavenwangcn** [comment]
见 问题 230

**Comment by flike** [comment]
fixed

**Comment by yunkaiyueming** [comment]
good job
