### ISSUE TITLE
更新 分表字段 的值后 数据不会迁移

### ISSUE THREAD

**Issue by munggruel** [flike/kingshard#213]
比如：帖子有附件，因为 上传附件的时候 没有 帖子 id（因为帖子没提交）统一设置为0，而 附件也是按照 帖子 tid 分表的，这样 提交 帖子时候 需要 帖子包含的 所有附件 aid  附件的 tid 设置为 当前获得的 帖子insertID，但是 直接 update 附件的 tid 为 insertID 不行，因为 tid是 附件的分表字段，更新后 数据并不会迁移，怎么解决

**Comment by flike** [comment]
是的。不能更新分表字段。
