### ISSUE TITLE
能否引入LRU,建立sql buffer cache，解决CPU瓶颈

### ISSUE THREAD

**Issue by Gilbert2189** [flike/kingshard#217]
给每条sql生产一个 md5(sql)，第一次解析记录好路由规则存放于sql buffer cache,下次可以先从buffer cache里找md5(sql)的路由规则，可以减轻CPU的压力

**Comment by forestkeeper** [comment]
这个实现上最大的问题，恐怕在于执行的sql和jdbc里面prepare的sql不同：
- 协议执行的sql：select * from user where id = 12345
- jdbc缓存的sql: select * from user where id = ?

上面那句sql 不同的参数会变成不同的缓存

**Comment by Gilbert2189** [comment]
@forestkeeper 分表方案不支持prepare, 非sharding的表的prepare会发送到默认节点，总之也需要重新解析路由规则，引入sql buffer 实际上也是能带来好处的。

**Comment by flike** [comment]
sql buffer cache这种机制，感觉效果不会很好。因为真正的SQL完全相同的情况还是比较少的。命中率低会是个很大的问题。

**Comment by Skycrab** [comment]
做到准确还需要根据delete,update语句判断缓存是否过期，proxy是不适合做这些的。就是mysql buffer cache生产环境下也是很少用的，olap的还可以考虑，oltp的应该很少开启的。

**Comment by Gilbert2189** [comment]
@Skycrab 我说buffer cache和你讲的概念并不同，与delete,update没啥关系，并不是要去cache查询数据，而是cache sql build plan，对于命中率是否高的问题，我只能说这取决于系统本身，任何系统都有可能频繁访问热点数据，那么频繁sql也是有可能的。我说的就是OLTP

**Comment by Skycrab** [comment]
额，我看错了，O(∩_∩)O
