### ISSUE TITLE
需要增加检测功能

### ISSUE THREAD

**Issue by jefjin** [flike/kingshard#218]
搭建kingshard集群，在3台kingshard机器前面挡一层LVS，但是LVS本身有机制会去定时探测比如9696端口是否正常，这是的协议肯定不是sql的这种协议，会导致一堆的"readHandshakeResponse" "connection was bad"，群主是否考虑在kingshard上面再开一个监听端口，用来给外围设备检测用的？

**Comment by bigpyer** [comment]
可以提供一个检测命令，你用这个命令来来判断kingshard是否存活
admin server(opt,k,v) values('show','proxy','status')
online:存活、offline:扑街

**Comment by flike** [comment]
@bigpyer 已经着手做这件事了。

**Comment by jefjin** [comment]
LVS一般是端口探测，端口可达就认为活着，我感觉提供命令不太适合LVS机制

**Comment by flike** [comment]
@jefjin @bigpyer 的好处就是可以平滑上线、下线kingshard。不光是探测。@jefjin 你的一个pr有很多功能，合并代码难度大啊。建议你联系我帮你开一个分支，然后把pr先合并到分支上，然后完善相应的文档（比如range模式下增加偏移参数，所有文档都要补全的），这样我才可以轻轻松松的合并代码，谢谢！

**Comment by simpleton** [comment]
想咨询一下，这个问题是否有方法解决呢？

**Comment by season89** [comment]
@simpleton  FYI
[ks配合lvs或者haproxy](https://github.com/flike/kingshard/blob/master/doc/KingDoc/how_to_use_lvs.md)

**Comment by simpleton** [comment]
@season89 多谢，我的问题和这个可能还稍有不通。我在使用阿里云，他的slb针对tcp转发必须有一个健康检查，会定时的ping这个端口。导致有大量错误log产生，issue如下：
ref #318

**Comment by season89** [comment]
@simpleton  slb应该可以定制化检测脚本，不然后端mysql也会报错的。

**Comment by jxmingyin** [comment]
@flike 这个问题貌似还存在吧，ks+lvs后，ks报出error日志#218
应该也是lb模块对端口健康扫描造成的log
