### ISSUE TITLE
需要ignore掉broken pipe signal，不然会导致kingshard exit

### ISSUE THREAD

**Issue by jefjin** [flike/kingshard#227]
可以将main.go对signal的处理改成如下：

sc := make(chan os.Signal, 1)
	signal.Notify(sc,
		syscall.SIGINT,
		syscall.SIGTERM,
		syscall.SIGQUIT,
		syscall.SIGPIPE)

	go func() {
		for {
			select {
			case sig := <-sc:
				if sig == syscall.SIGINT || sig == syscall.SIGTERM || sig == syscall.SIGQUIT {
					golog.Info("main", "main", "Got signal", 0, "signal", sig)
					golog.GlobalSysLogger.Close()
					golog.GlobalSqlLogger.Close()
					svr.Close()
					monitor_svr.Close()
					return
				}

				if sig == syscall.SIGPIPE {
					golog.Info("main", "main", "Ignore broken pipe signal", 0)
				}
			}
		}
	}()

**Comment by flike** [comment]
现在kingshard并没有在Notify中监听syscall.SIGPIPE，所以不会响应该信号。所以也不会由于SIGPIPE而退出。是不是你自己改代码了？

**Comment by jefjin** [comment]
就是因为代码都没有监听syscall.SIGPIPE. 一旦kingshrad收到PIPE，那默认行为就是退出。所以要加上PIPE的监听并且ignore掉

**Comment by flike** [comment]
我测试了一下，kill -13 进程号。kingshard并不会退出，如何重现你的问题？13是SIG_PIPE

**Comment by jefjin** [comment]
估计你又kill -13模拟不出来，我们在测试大并发的时候，当网络有问题的时候就会出现此问题，并导致退出。

**Comment by foobar** [comment]
从golang1.6的文档上看, SIGPIPE处理不会导致默认的退出行为,  但FD 1和2有特殊处理. 
```
On Unix-like systems, when a write to os.Stdout or os.Stderr
 (more precisely, an os.File opened for file descriptor 1 or 2)
 fails due to a broken pipe error, the program will raise a SIGPIPE 
signal. By default this will cause the program to exit; this may
 be changed by calling the os/signal Notify function for syscall.SIGPIPE.
 A write to a broken pipe on a file descriptor other 1 or 2 will simply 
return syscall.EPIPE (possibly wrapped in os.PathError and/or 
os.SyscallError) to the caller. The old behavior of raising an 
uncatchable SIGPIPE signal after 10 consecutive writes to a 
broken pipe no longer occurs.
```

**Comment by flike** [comment]
@foobar ,那有解决办法吗？

**Comment by foobar** [comment]
@jefjin 能不能提供一个可重现场景的代码? 或者在signal handler里面打印出stack trace, 定位哪里产生的signal.

**Comment by jefjin** [comment]
一般是对方socket调用了close，这是kingshard还是往这个socket里面write，一般在linux上开发server，不管用c、c++等，这个signal pipe都是过滤掉的。

**Comment by foobar** [comment]
你说的linux server 上的行为是确定的,  内核需要保证SIGPIPE的确实处理方式是terminate, 但是golang自己会处理SIGPIPE.
Ian Lance Taylor在这个post里面解释的很清楚:   https://groups.google.com/forum/#!topic/golang-nuts/6zdU7zX6MvE

**Comment by jefjin** [comment]
现实看下来并不是如此，但是加上signal pipe的拦截，但目前为止没有发现此种情况的出现. 我怀疑是不是某个点golang本身对处理sigpipe存在着问题？？？建议在main中加上这个，有益无害，保证kingshard的稳定性，然后再深入研究一下golang的内部机制.

**Comment by foobar** [comment]
如果你的golang版本没有问题, 能想到的可能性就是你在write到stdout/stderr的file descriptor (1/2).

**Comment by jefjin** [comment]
golang是1.6的，应该没有问题. 有可能是你说的问题。anyway，加上保护是必须的.

**Comment by jefjin** [comment]
因为有可能会用nohup命令启动kingshard作为守护进程处理，然后把输出redirect了.

**Comment by flike** [comment]
能重现吗？

**Comment by jefjin** [comment]
偶见的. 并且出现的时候在log中你是看不出任何异常的，抓不到callstack，类似于直接调用了os.Exit

**Comment by flike** [comment]
fixed
