### ISSUE TITLE
分表 SQL 不在一行 多个分隔符 解析错误

### ISSUE THREAD

**Issue by gavenwangcn** [flike/kingshard#230]
如：SQL
 select * 
 from product_consult
 where consultid >0 and custnum >1000
 groupBy custnum
 orderBy consultnum
 limit 0,100
等 解析product_consult 为分表的时候
conn_preshard.go  里面确认到分表查询错误。
解决方法
修改 hack.go  的
func IsSqlSep(r rune) bool { 
	return r == ' ' || r == ',' || r == '\t' || r == '/' 
 } 
改成
func IsSqlSep(r rune) bool { 
  return r == ' ' || r == ',' || r == '\t' || r == '\n' || r == '\v' || r == '\r' || r == '\f' || r == 0x85 || r == 0xA0 || r == '/'
 }

**Comment by flike** [comment]
r=0x85和0xA0 分别对应什么？参照acciis码没看到。

**Comment by flike** [comment]
fixed

**Comment by yunkaiyueming** [comment]
good job
