### ISSUE TITLE
Save the configuration file path

### ISSUE THREAD

**Issue by johnripperdec** [flike/kingshard#233]
![z 6_x8v l_ cctmh av59s](https://cloud.githubusercontent.com/assets/15044314/17654567/fbac7ff2-62d6-11e6-976d-8ae14ae98df9.png)
my config path:
 /opt/soft/kingshard/src/github.com/flike/kingshard/etc/ks.yaml
kingshard admin command :
admin server(opt,k,v) values('save','proxy','config')
load config path:
/opt/soft/kingshard/src/github.com/flike/kingshard/bin/etc/ks.yaml

**Comment by bigpyer** [comment]
i will check it soon at noon.
