### ISSUE TITLE
SHOW FULL FIELDS / COLUMNS doesn't work

### ISSUE THREAD

**Issue by sysmate** [flike/kingshard#238]
Hi,

SHOW FULL FIELDS and SHOW FULL COLUMNS doesn't work for me, i tried with and without USE DATABASE statement before. Tried different MySQL clients and still the same problem.
I am using Yii Framework which needs those commands to cache table informations. 

There was already another Issue about this problem but it didn't solve it and it is already closed.
#180

regards

**Comment by flike** [comment]
OK, I'll fix this bug as soon as possible.

**Comment by sysmate** [comment]
Many Thanks. If u need some more Informations just ask me.

**Comment by flike** [comment]
I try this command from a cli, and it can get the right result.

```
mysql> /*node2*/show full columns from test_shard_hash_0007;
+-------+-----------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Field | Type                  | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
+-------+-----------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| id    | bigint(64) unsigned   | NULL               | NO   | PRI | NULL    |       | select,insert,update,references |         |
| str   | varchar(100)          | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| f     | double                | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| e     | enum('test1','test2') | utf8_general_ci    | YES  |     | NULL    |       | select,insert,update,references |         |
| u     | tinyint(3) unsigned   | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| i     | tinyint(4)            | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
+-------+-----------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
6 rows in set (0.01 sec)
```

**Comment by sysmate** [comment]
Hi, this way it works if  i use the shard information like u did ( _000X ). But 
"show full columns from test_shard_hash"  without shard informations doesn`t work. 
In that case transparent proxy usage is not possible with some frameworks.

**Comment by flike** [comment]
ok, I got it. Can you tell which framework will send these SQLs ?

**Comment by sysmate** [comment]
I use Yii 1.1.16 and afaik newer versions like Yii 2.X or Laravel Framwork do the same to build a schema cache.

SHOW FULL COLUMNS FROM MyTable
SHOW CREATE TABLE MyTable

**Comment by flike** [comment]
supported

**Comment by sysmate** [comment]
Hei, thx for implementing this feature, but it still doesn't work.
I tried it in MySQL Console with "use testdb" and without "use" to avoid framework issues.

mysql> SHOW FULL COLUMNS FROM testdb.testtable;
ERROR 1146 (42S02): Table 'testdb.testtable' doesn't exist
mysql> SHOW FULL COLUMNS FROM testtable;
ERROR 1146 (42S02): Table 'testdb.testtable' doesn't exist

mysql> use testdb;
mysql> SHOW FULL COLUMNS FROM testtable;
ERROR 1146 (42S02): Table 'testtable' doesn't exist
mysql> SHOW FULL COLUMNS FROM testdb.testtable;
ERROR 1146 (42S02): Table 'testdb.testtable' doesn't exist

**Comment by flike** [comment]
does this table(testdb.testtable) exist?

**Comment by sysmate** [comment]
Sure it exists and if i use a sharded table like SHOW FULL COLUMNS FROM testtable_0001 it works perfect.

**Comment by flike** [comment]
show me the SQL Log

**Comment by ruihuowayking** [comment]
try  
show full  columns from testdb.testtable;

Please use lowercase

**Comment by flike** [comment]
fix
