### ISSUE TITLE
使用beego orm发送查询插入等sql，不认分表，提示表不存在

### ISSUE THREAD

**Issue by parchk** [flike/kingshard#242]
![qq 20160830125508](https://cloud.githubusercontent.com/assets/12369932/18076638/52624ade-6eb2-11e6-9eac-d5a69c184815.png)
[http://git.oschina.net/uploads/images/2016/0830/125620_accb399a_389570.png](url)

用beego orm 查询语句，直连是没有问题的，加了proxy做分表之后，认不出分表。例如表test_hash_0,test_hash_1会提示库名.test_hash表不存在。
用mysql终端查询是没有问题的，可以认到分表，说明配置是对的。
kingshard的sys.log日志
2016/08/30 12:56:59 - ERROR - conn.go:[287] - [server] "Run" "prepare error ERROR 1146 (42S02): Table 'ysj.test_hash' doesn't exist" "" conn_id=10001

**Comment by flike** [comment]
prepare不支持分表的情形。

**Comment by lcp0578** [comment]
@flike 感谢您提供这个Proxy，希望把不适用的情景也写到readme里面，我也找了好久问题，在命令行没问题，用了框架就不行了

**Comment by eastfisher** [comment]
@lcp0578 这个估计得靠社区共同努力了, 毕竟大家使用场景不完全一样.

**Comment by lcp0578** [comment]
@eastfisher 嗯嗯，好
