### ISSUE TITLE
SQL转发问题，SQL语句只要开头带/**/ select xxx; 就会转发到主库上进行查询。

### ISSUE THREAD

**Issue by zhengzhang2040** [flike/kingshard#243]
试了2个版本，2016.08.09 和2016.08.30 的两个版本，发现问题是：SQL的开头只要带/* */ 就会转发到主库上进行查询。 如：/*node1*/ select 1; 或者 /**/ select 1; 就都只往主库转发。

**Comment by flike** [comment]
fixed
