### ISSUE TITLE
按日分表查询出错

### ISSUE THREAD

**Issue by BakerWang** [flike/kingshard#248]
环境：
![image](https://cloud.githubusercontent.com/assets/9738358/18374282/2e37dcea-767e-11e6-9740-2fd84333635e.png)
表结构：
![image](https://cloud.githubusercontent.com/assets/9738358/18374296/4d921286-767e-11e6-9b94-2ac5923125f7.png)
表数据：
![image](https://cloud.githubusercontent.com/assets/9738358/18374330/8be6e548-767e-11e6-8185-132871717333.png)
ks.yaml配置：
![image](https://cloud.githubusercontent.com/assets/9738358/18374320/734fe02a-767e-11e6-9c0f-b4598e0750b3.png)
报错信息：
![image](https://cloud.githubusercontent.com/assets/9738358/18374336/9b27bb68-767e-11e6-9bb4-898ab308c987.png)

**Comment by leohdr** [comment]
包含timestamp字段的都会有这个错误

**Comment by leohdr** [comment]
问题在mysql/resultset.go第70、71行
			case MYSQL_TYPE_TIMESTAMP:
				data[i], err = strconv.ParseInt(string(v), 10, 64)

**Comment by flike** [comment]
修改了一下，再试试。

**Comment by BakerWang** [comment]
可以了
