### ISSUE TITLE
make出错

### ISSUE THREAD

**Issue by saga1015** [flike/kingshard#249]
flike，你好，编译的时候报如下错误
go tool yacc -o ./sqlparser/sql.go ./sqlparser/sql.y
gofmt -w ./sqlparser/sql.go
go build -o ./bin/kingshard ./cmd/kingshard
go tool: no such tool "6g"
make: *** [kingshard] 错误 3
这个错误该如何解决呢

**Comment by flike** [comment]
按照这个文档操作没问题的。https://github.com/flike/kingshard/blob/master/doc/KingDoc/kingshard_install_document.md
