### ISSUE TITLE
当前最新版本当表中包含timestamp字段时报错：strconv.ParseInt: parsing "2013-04-08 19:52:47": invalid syntax 

### ISSUE THREAD

**Issue by leohdr** [flike/kingshard#250]
2016/09/11 17:01:21 - ERROR - conn_query.go:[58] - [server] "preHandleShard" "strconv.ParseInt: parsing "2013-04-08 19:52:47": invalid syntax" "sql=SELECT *
FROM `pre_coupon_users`
LIMIT 50|hasHandled=false" conn_id=0
2016/09/11 17:01:21 - ERROR - conn.go:[287] - [server] "Run" "strconv.ParseInt: parsing "2013-04-08 19:52:47": invalid syntax" "" conn_id=10009

**Comment by leohdr** [comment]
问题在mysql/resultset.go第70、71行
			case MYSQL_TYPE_TIMESTAMP:
				data[i], err = strconv.ParseInt(string(v), 10, 64)

**Comment by flike** [comment]
修改了一下，再试试。
