### ISSUE TITLE
多数据源问题

### ISSUE THREAD

**Issue by BakerWang** [flike/kingshard#251]
![image](https://cloud.githubusercontent.com/assets/9738358/18424125/040f026e-78df-11e6-8bba-1af02d114876.png)
目前所有的node对应的db是同一个，由于业务隔离，应用中有多个数据源，多个数据源的db名称不一样，是不是不支持

**Comment by flike** [comment]
分表的DB只能有一个，也就是说分表只能放在该DB。但不分表的DB，不限制。
