### ISSUE TITLE
thinkphp5连接kingshard,执行SHOW COLUMNS FROM `xxx` 出错

### ISSUE THREAD

**Issue by ruihuowayking** [flike/kingshard#253]
thinkphp5连接kingshard,运行出错:

> SQLSTATE[HY000]: General error: 1105 parse sql "SHOW COLUMNS FROM `admin_auth_group_access`" error

指定node也一样

>SQLSTATE[HY000]: General error: 1105 parse sql "/\*node1\*/SHOW COLUMNS FROM `admin_auth_group_access`" error

kingshard日志如下:

>2016/09/18 17:52:31 - INFO - server.go:[279] - [server] "NewServer" "Server running" "netProto=tcp|address=0.0.0.0:9696" conn_id=0
>2016/09/18 17:52:44 - ERROR - conn.go:[287] - [server] "Run" "parse sql "SHOW COLUMNS FROM `admin_auth_group_access`" error" "" conn_id=10001
>2016/09/18 17:55:10 - ERROR - conn.go:[287] - [server] "Run" "parse sql "/\*node1\*/SHOW COLUMNS FROM `admin_auth_group_access`" error" "" conn_id=10002

thinkphp错误日志如下:

>public function getFields($tableName) {
		$this->initConnect(true);
		list($tableName) = explode(' ', $tableName);
		if (strpos($tableName, '.')) {
			$tableName = str_replace('.', '`.`', $tableName);
		}
		$sql = 'SHOW COLUMNS FROM `' . $tableName . '`';
		// 调试开始
		$this->debug(true);
		$pdo = $this->linkID->query($sql);
		// 调试结束
		$this->debug(false, $sql);
		$result = $pdo->fetchAll(PDO::FETCH_ASSOC);
		$info = [];
		if ($result) {
			foreach ($result as $key => $val) {
				$val = array_change_key_case($val);
				$info[$val['field']] = [
					'name' => $val['field'],

错误行
at PDO->query('SHOW COLUMN...') in Mysql.php line 57

直接在kingshard命令行执行SHOW COLUMNS FROM `admin_auth_group_access` 返回正常,跟直连mysql返回一致.

盼解答

**Comment by flike** [comment]
会尽快修复的。:)

**Comment by ruihuowayking** [comment]
THX

**Comment by ruihuowayking** [comment]
今天做了个简单实验,用最新TP5.1框架,一句最简单的select语句执行,结果让我很不理解.

1:数据库内容[mysql5.6]本表没有做分片
![s](https://cloud.githubusercontent.com/assets/11738943/19023146/5eefea96-8919-11e6-9570-9b737883332d.jpg)
2:php程序代码
![w](https://cloud.githubusercontent.com/assets/11738943/19023110/a754b2ae-8918-11e6-8784-ad95eea36789.png)

3:直连MYSQL返回结果
![y](https://cloud.githubusercontent.com/assets/11738943/19023165/ea2b768e-8919-11e6-8b1a-539fc5b57e68.png)


4:连接kingshard之后返回结果
![n](https://cloud.githubusercontent.com/assets/11738943/19023169/02ebdbc8-891a-11e6-8d3e-239e3b429b8b.png)


这是什么原因呢?

**Comment by flike** [comment]
supported

**Comment by ruihuowayking** [comment]
问题找到:  不是kingshard的问题，是tp的pdo驱动问题.修改/think/db/Connection.php的114行PDO::ATTR_EMULATE_PREPARES => false, j将false修改为true即可解决。
