### ISSUE TITLE
使用python oursql报oursql.ProgrammingError: (1105, 'unsupported flag 1', None)

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#255]
简单的select即报错，kingshard端的错误信息是ERROR - conn.go:[290] - [server] "Run" "ERROR 1105 (HY000): unsupported flag 1"．直连db则正常．

linux
go versoin:1.7
kingshard version: a15fd20
oursql version: 0.9.2
python version:2.7

**Comment by flike** [comment]
应该是不支持该SQL，你可以定位一下SQL，然后告诉我。谢谢。

**Comment by wangcn** [comment]
任意select，比如select @@tx_isolation

**Comment by flike** [comment]
在命令行发select @@tx_isolation，kingshard可以支持的，我试过了。可能是python框架发送其他SQL导致的。

**Comment by wangcn** [comment]
# -*- coding: utf-8 -*-

import oursql

def main():
    conn = oursql.connect(host, user, passwd, db, port=port_to_kingshard)
    curs = conn.cursor(oursql.DictCursor)
    curs.execute('select @@tx_isolation')
    print curs.fetchone()

if __name__ == '__main__':
    main()

**Comment by wangcn** [comment]
应该不会是额外的sql．抓包也没有看到额外的查询．

**Comment by martianzhang** [comment]
应该是对Prepare， Execute的处理有问题。抓了一下mysql的全日志，如下：
2338349 Connect kingshard@127.0.0.1 on kingshard
2338349 Prepare select @@tx_isolation           
2338349 Execute select @@tx_isolation           
2338349 Close stmt                              
2338349 Quit

**Comment by martianzhang** [comment]
目前Kingshard的prepare statement API对STMT_ATTR_CURSOR_TYPE只支持CURSOR_TYPE_NO_CURSOR（对应flag为0）一种。
oursql调用时设置了STMT_ATTR_CURSOR_TYPE默认为CURSOR_TYPE_READ_ONLY（对应flag为1）
所以为报上那个错误'unsupported flag 1'

**临时解决办法：**
curs.execute('select @@tx_isolation', plain_query=True)

参考链接：
https://dev.mysql.com/doc/internals/en/com-stmt-execute.html
http://dev.mysql.com/doc/refman/5.7/en/mysql-stmt-attr-set.html
https://pythonhosted.org/oursql/tutorial.html
https://github.com/python-oursql/oursql/blob/master/oursqlx/compat.c

**Comment by flike** [comment]
👍
