### ISSUE TITLE
`begin` and `start transaction` in kingshard will not cause `Implicit Commit`

### ISSUE THREAD

**Issue by martianzhang** [flike/kingshard#263]
Beginning a transaction causes any pending transaction to be committed.
In kingshard if mysql.SERVER_STATUS_IN_TRANS > 0 will not send `begin` command to backend.
When i use following query to implicit commit last transaction will cause a long running transaction.
```
begin;
select 1;
begin;
....
begin;
```
Reflink: http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by martianzhang** [comment]
handleBegin() function change like this
```
 func (c *ClientConn) handleBegin() error {
+       for _, co := range c.txConns {
+               if e := co.Begin(); e != nil {
+                       return c.writeError(e)
+               }
+       }
        c.status |= mysql.SERVER_STATUS_IN_TRANS
        return c.writeOK(nil)
 }
```

**Comment by flike** [comment]
Thank you, I will re-examine these code.

**Comment by flike** [comment]
done
