### ISSUE TITLE
请问如何热加载配置文件

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#270]
我看到＂配置文件变更后，热加载，即kingshard reload可以处理部分配置文件的变更 #85＂这个issue已关闭，但没有找到相关文档．

**Comment by flike** [comment]
直接调用API

**Comment by wangcn** [comment]
是源码里的api还是管理API。我在文档里没有找到，能不能说得更详细些？

**Comment by flike** [comment]
管理API

**Comment by wangcn** [comment]
文档里没看到。比如我在配置里新加了分表配置，怎么不重启而直接reload？

**Comment by bigpyer** [comment]
通过管理api改变运行时配置，而不是reload的方式
