### ISSUE TITLE
PDO连接Mysql无法正常使用事务

### ISSUE THREAD

**Issue by chenzi2015** [flike/kingshard#271]
问题描述：我现在用的PHP的框架开发，使用PDO操作连接MySql数据库，目前遇到一个问题就是开始事务无法指定节点，加了“/*node1*/”后感觉也没有起到作用。

1、通过PDO类进行事务操作，[相关介绍](http://php.net/manual/zh/book.pdo.php)，这种方式无法使用/*node1*/”指定节点

2、通过SQL提交事务，但是这种方式ROLLBACK并没有回滚INSERT的内容。
/*node1*/BEGIN
/*node1*/INSERT INTO `table1`...
/*node1*/INSERT INTO `table2`... 
/*node1*/ROLLBACK

**Comment by martianzhang** [comment]
PDO貌似走的是prepare statement,如果是这样的话走的是COM_STMT_PREPARE， COM_STMT_EXECUTE这种命令类型。
目前对于/*master*/ /*nodeN*/这些HINT的提取只对COM_Query命令类型的请求生效。

**Comment by flike** [comment]
是的。非分片情况下，用事务应该是支持prepare statement。
