### ISSUE TITLE
关于连接池回收 连接状态的问题

### ISSUE THREAD

**Issue by xuewindy** [flike/kingshard#274]
你好 想问问关于连接池的一个问题，当我拉取一个连接 并执行set time_zone="+00:00" 时连接的session状态就会被改变，那么当释放这个连接时。下次其他动作拉拉取到的连接这个状态还是被改变的么？
还是当我出现这种情况时 不会把连接回收 而是直接关闭呢

**Comment by bigpyer** [comment]
1.连接不具备时区这个状态，所以再取到的时候，应该不是被改变的。
2.set time_zone="+00:00"设置了之后mysql端就会生效，不是一个连接状态，你可以试一下，我没有用过这个命令，不是太确定。

**Comment by flike** [comment]
下次不一定能取到同一个连接，除非开启了事务。

**Comment by xuewindy** [comment]
昨天看了 源码  这个kingsshard 本身是不支持除了autocommit 和names之外的状态的
这样对日常业务影响大么

**Comment by flike** [comment]
不算大。

**Comment by xuewindy** [comment]
。。。这地方做的感觉很随缘啊 ，，， 还有一部分我看到源码，hack 部分用字符串 和slice 主要是了节省内存吧 不过这样转后  变量本身就是个引用了感觉 不能再 采用 var a string = b 这样的值传递操作了是吧》
