### ISSUE TITLE
分表情况下 group by 错误

### ISSUE THREAD

**Issue by ruihuowayking** [flike/kingshard#277]
直连没问题,分表情况下以下语句执行错误
select DATE_FORMAT(from_unixtime(create_time),'%Y%m')  months,count(id)  count from `pay_log` where create_rid=4 and status=1 group by months

提示months字段不存在,怎么解决?

问题出在 group by months,这个months 不存在

**Comment by flike** [comment]
是的。group by必须是存在的表字段，后续看看如何支持这种feature。

**Comment by ruihuowayking** [comment]
好的,谢谢.目前用另一种查询方式代替这种获取按月统计了.希望能尽早支持,这个比较有用.

**Comment by flike** [comment]
好的，不客气。
