### ISSUE TITLE
不支持SET @@session.autocommit = ON

### ISSUE THREAD

**Issue by qzlaobi** [flike/kingshard#278]
> ERROR - conn_query.go:[68] - [server] "parse" "syntax error at position 30 near on" "hasHandled=false|sql=SET @@session.autocommit = ON" conn_id=0

SET @@session.autocommit = 1的话没问题

**Comment by martianzhang** [comment]
@qzlaobi   能顺便说一下您使用的编程语言和mysql驱动的版本是什么呢？比较好奇是哪种语言默认用“SET @@session.autocommit = ON”。

这里报的“syntax error”应该是sql.y对这种ON字符串不加引号形式的没做处理

再转换一下形式set @@session.autocommit="ON"，就会报ERROR 1105 (HY000): set autocommit error，这种错误是handleSet中没对"ON","OFF"做处理。

**Comment by qzlaobi** [comment]
@martianzhang 谢谢您的回复
用的是python2和mysql-connector 2.1.4

**Comment by martianzhang** [comment]
的确Connector/Python 2.1.4用了如下方法设置开启事务

> def autocommit(self, value):
        """Toggle autocommit"""
        switch = 'ON' if value else 'OFF'
        self.cmd_query("SET @@session.autocommit = {0}".format(switch))
        self._autocommit = value

**Comment by martianzhang** [comment]
`
diff --git a/proxy/server/conn_set.go b/proxy/server/conn_set.go
index 7eee990..87b9441 100644
--- a/proxy/server/conn_set.go
+++ b/proxy/server/conn_set.go
@@ -76,12 +76,10 @@ func (c *ClientConn) handleSet(stmt *sqlparser.Set, sql string) (err error) {
 }              
                
 func (c *ClientConn) handleSetAutoCommit(val sqlparser.ValExpr) error {
-       value, ok := val.(sqlparser.NumVal)
-       if !ok {        
-               return fmt.Errorf("set autocommit error")
-       }       
-       switch value[0] {
-       case '1':
+       flag := sqlparser.String(val)
+       flag = strings.Trim(flag, "'`\"")
+       switch strings.ToUpper(flag) {
+       case `1`, `ON`:
                c.status |= mysql.SERVER_STATUS_AUTOCOMMIT
                if c.status&mysql.SERVER_STATUS_IN_TRANS > 0 {
                        c.status &= ^mysql.SERVER_STATUS_IN_TRANS
@@ -95,10 +93,10 @@ func (c *ClientConn) handleSetAutoCommit(val sqlparser.ValExpr) error {
                        co.Close()
                }
                c.txConns = make(map[*backend.Node]*backend.BackendConn)
-       case '0':
+       case `0`, `OFF`:
                c.status &= ^mysql.SERVER_STATUS_AUTOCOMMIT
        default:
-               return fmt.Errorf("invalid autocommit flag %s", value)
+               return fmt.Errorf("invalid autocommit flag %s", flag)
        }
 
        return c.writeOK(nil)
diff --git a/sqlparser/sql.y b/sqlparser/sql.y
index 1c4535f..0103778 100644
--- a/sqlparser/sql.y
+++ b/sqlparser/sql.y
@@ -1068,7 +1068,11 @@ update_list:
 update_expression:
   column_name '=' value_expression
   {
-    $$ = &UpdateExpr{Name: $1, Expr: $3} 
+    $$ = &UpdateExpr{Name: $1, Expr: $3}
+  }
+| column_name '=' ON
+  {
+    $$ = &UpdateExpr{Name: $1, Expr: StrVal("ON")}
   }
 
 exists_opt:
`

**Comment by flike** [comment]
bugfix-autocommit分支，@martianzhang，麻烦pr一下，谢谢！

**Comment by flike** [comment]
fixed
