### ISSUE TITLE
请问ｃｈａｒｓｅｔ会从哪些地方取值？

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#286]
在两套环境中都没有配proxy_charset
执行SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';时，一个环境的character_set_client是utf8mb4，另一个是utf8.

**Comment by martianzhang** [comment]
是用同一个客户端连接的么？
使用的是MySQL自带的客户端还是其他的什么工具呢？

建议proxy_charset配置与数据库字符集相同，最新版本如不配置默认是UTF8

**Comment by wangcn** [comment]
mysql自带客户端

**Comment by martianzhang** [comment]
mysql自带客户端可以使用如下命令查看一下是否连接的时候是否有隐含指定默认字符集
`mysql --help | grep ^default-character-set`
