### ISSUE TITLE
分表情况下不支持 EXPLAIN 

### ISSUE THREAD

**Issue by xluohome** [flike/kingshard#287]
报错提示如下： 
ERROR - conn_query.go:[58] - [server] "preHandleShard" "ERROR 1146 (42S02): Table 'devdb.pre_forum_post' doesn't exist" "sql=/*node1*/EXPLAIN  select * from pre_forum_post  where   tid =1370627|hasHandled=false" conn_id=0

2016/12/07 11:34:29 - ERROR - conn.go:[283] - [server] "Run" "ERROR 1146 (42S02): Table 'devdb.pre_forum_post' doesn't exist" "" conn_id=10013

pre_forum_post    根据 tid  分表；

ks版本：

  __   _                  __                   __
   / /__(_)___  ____ ______/ /_  ____ __________/ /
  / //_/ / __ \/ __ \/ ___/ __ \ / __\/ ___/ __  /
 / ,< / / / / / /_/ (__  ) / / / /_/ / /  / /_/ /
/_/|_/_/_/ /_/\__, /____/_/ /_/\__,_/_/   \__,_/
             /____/
Git commit:2016-11-25 17:28:28 +0800 @2f21f25
Build time:2016-12-06 16:13:52 +0800 by go version go1.7.3 linux/amd64

**Comment by flike** [comment]
这种情况下，不会解析pre_forum_post 包含的分表。需要你把具体的分表带上。
