### ISSUE TITLE
假如 post 表 以 tid 作为 hash 分表 ，更新 tid 导致不成功；

### ISSUE THREAD

**Issue by xluohome** [flike/kingshard#289]
假如  post 表 以 tid 字段作为 hash 分表（tid 非主键），    如果 对  tid 字段值 进行  update ； 

结果 不会有效果， 

应该 把这个 update 改成 一条 insert 语句  ， 在hash 对应的表里面 insert 这条数据；

**Comment by imiskolee** [comment]
不赞同这个特性。

因为这个特性涉及到数据迁移。也就意味着kingshard需要侵入数据。这里引出两个问题：

1.  数据安全性。
2.  分布式操作的事务性。

**Comment by xluohome** [comment]
ks 在 insert sql  时如果 有多个 tid 时 也是 改写成多条insert sql 的哦，  同理， 更新 update  应该也是改写成 多条 update sql  和 insert sql

**Comment by xluohome** [comment]
如果没有这个特性支持，  也就失去了（限制）用除主键以外的字段值作为hash 的实际使用价值。

**Comment by bigpyer** [comment]
分表字段不应该被更新的，只可以当做检索条件。
