### ISSUE TITLE
[NFR] 支持或部分支持DDL

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#291]
文档中说分512个表，但表的创建和以后的schema change如果没有DDL的支持对于DBA来说简直是噩梦。

**Comment by flike** [comment]
写个脚本搞定这个事情，应该不是噩梦吧？

**Comment by miao606** [comment]
一个库100多个表，每个表1024个，不说多8台服务器。一次release有10个schema change，你觉得容易？

**Comment by bigpyer** [comment]
@miao606  1.你举得例子比较极端，分表并非所有的表都要分 2.分表ddl的创建我了解到的公司都可以通过脚本或者运维平台解决，这件事请并没有太多讨论的地方
