### ISSUE TITLE
[NFR] 性能优化（简单说说我遇到的情况）

### ISSUE THREAD

**Issue by mia0x75** [flike/kingshard#293]
这个话题太大，不知道从和说起。简单描述我的例子

SysBench服务器：S1（一台） -> Kingshard服务器：K1（一台） -> MySQL服务器：M1/M2（两台）

S1：48 Cores
K1：48 Cores
M1：192 Cores
M2：192 Cores

测试大概15w-18w/秒查询次数。

问题：
1、200线程做压力测试，S1 CPU很低，M1/M2也不足10%，但K1在80%左右。
2、稳定性测试48小时，在不到24小时的时候，KS异常退出，不知道怎么查

另外我开发环境因流量非常低（普通PC机），这个持续上月的时间也很稳定。

**Comment by guobingithub** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
