### ISSUE TITLE
分表时  update  replace 函数无法定位到分表导致错误

### ISSUE THREAD

**Issue by xluohome** [flike/kingshard#294]
forum_post  是通过 tid 分表，  执行如下sql：
UPDATE forum_post SET message=replace(message,'#tj#','#PPT#') WHERE `tid`='1371001' AND first=1

报错如下：
(0) 'array ( 0 => \'HY000\', 1 => 1105, 2 => \'syntax error at position 42 near replace\', )'

**Comment by flike** [comment]
目前不支持字符串分表。

**Comment by xluohome** [comment]
@flike 这个之前已经讨论过不支持  UPDATE forum_post SET message=replace(message,'#tj#','#PPT#')，

应该考虑一下支持分表的 update replace
