### ISSUE TITLE
JDBC executeUpdate返回的值疑问

### ISSUE THREAD

**Issue by unext-ops** [flike/kingshard#299]
JDBC: 5.1.35
mysql: 5.6.22

sql: update TABLE set a=xx where b=xx;

直连mysql无论是否有字段更新都是返回1，不存在返回0
通过ks有字段更新返回1，没有更新和不存在的话返回0

请教下这个差异是JDBC的使用姿势不正确吗？还是正常现象？

**Comment by flike** [comment]
直连有更新的话，肯定会返回更新行数吧？

**Comment by unext-ope-system** [comment]
executeUpdate返回的不是行数
希望ks能和直连返回的值相同

**Comment by flike** [comment]
能详细描述一下复现的case么？我复现了才能修复。

**Comment by martianzhang** [comment]
JDBC 5.1.35的README有如下说明
`
To update data in the database, use the executeUpdate(String
   SQL) method. This method returns the number of rows matched                                                                                                                                                 
   by the update statement, not the number of rows that were 
   modified.
`
...
`
you can retrieve the affected rows count by
   calling getUpdateCount() on the Statement instance.
`

UPDATE请求返回的如下信息是在OK包的info里面，这个信息ks并未返回给客户端，导致JDBC的executeUpdate返回与直连不同。
`Rows matched: 1  Changed: 0  Warnings: 0`

**Comment by unext-ope-system** [comment]
测试的代码，测试表就两个字段id,n
```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class TestJdbc5 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String driver = "com.mysql.jdbc.Driver";
		String url = "jdbc:mysql://10.105.102.150:3306/test?useUnicode=true&characterEncoding=utf8";
		String user = "test";
		String password = "test";

		Connection conn = null;

		try {
			conn = DriverManager.getConnection(url, user, password);
			Statement stmt = conn.createStatement();

			int res = stmt.executeUpdate("update test01 set n='" + "b" + "' where id=1");
			System.out.println(res);

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
```
非常感谢 @martianzhang 解答

**Comment by liule** [comment]
@flike 此问题是否已经复现并解决？

**Comment by flike** [comment]
@liule 目前还没有。

**Comment by flike** [comment]
在命令行中，如果update未更新行，会返回0的。我测试过。
```
mysql> select * from stu;
Empty set (0.00 sec)

mysql> update stu set fileid=12 where path="hello";
Query OK, 0 rows affected (0.00 sec)
Rows matched: 0  Changed: 0  Warnings: 0
```

**Comment by qzlaobi** [comment]
@flike 感谢确认

期望是未更新，但是有匹配到行
返回和直连一样
Rows matched: 1  Changed: 0  Warnings: 0

**Comment by flike** [comment]
能否列一下命令行对应的case？

**Comment by qzlaobi** [comment]
不好意思 我描述错误了
是使用JDBC的executeUpdate才有这个问题
mysql的client命令行无法复现
根据martianzhang描述的是UPDATE请求返回的如下信息是在OK包的info里面，这个信息ks并未返回给客户端，导致JDBC的executeUpdate返回与直连不同。
Rows matched: 1 Changed: 0 Warnings: 0

**Comment by flike** [comment]
我目前还未见到过matched匹配了，但未更新的case。
kingshard里面其实将affected row信息返回给客户端了。

**Comment by flike** [comment]
推荐调用mysql_affected_rows函数，获取受影响的行数。
