### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by sandeepone** [flike/kingshard#30]
First thank you for such a wonderful piece of software. I would like to know, is it production ready? 

It would be helpful for me and many others if you could provide some benchmarks as well. 

How good it is compared to Atlas and Fabric?

**Comment by flike** [comment]
Now kingshard is ready for production, As far as I know, some start-up companies are trying to use kingshard in the production environment.Bendmarks of kingshard are coming soon.Thank you for you attention.

**Comment by sandeepone** [comment]
Thank you.
