### ISSUE TITLE
pull request #297 引入“ERROR 1046 (3D000): No database selected”

### ISSUE THREAD

**Issue by martianzhang** [flike/kingshard#300]
pull request 297合并之后产生如下类型错误日志
2016/12/21 12:33:53 - ERROR - conn_query.go:[58] - [server] "preHandleShard" "ERROR 1046 (3D000): No database selected" "sql=select USER()|hasHandled=false" conn_id=0
2016/12/21 12:33:53 - ERROR - conn.go:[280] - [server] "Run" "ERROR 1046 (3D000): No database selected" "" conn_id=10002

配置
- max_conns_limit : 2（为方便复现）

复现方法
- 第一个连接use db_exist后直接退出
- 使用mysql客户端再新建一个连接就会有如上报错

**Comment by flike** [comment]
fixed
