### ISSUE TITLE
[Question] Does kingshard route all reading request to slaves?

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#306]
I use the master-slave mode for mysql. I found all of the reading requests had been routed to slaves. 
If I wanna sending a few requests to the master, how could I write the config file?

**Comment by bigpyer** [comment]
1.write master's ip:port in the slave config item
2./*master*/ + sql, then this sql will be routed to master

**Comment by simpleton** [comment]
@bigpyer Thanks a lot.
