### ISSUE TITLE
mysql客户端在查询数据的时候ctrl＋c中断查询会导致kingshard服务器退出

### ISSUE THREAD

**Issue by coreycui** [flike/kingshard#308]
^C2017/01/10 16:10:30 - INFO - main.go:[128] - [main] "main" "Got signal" "signal=interrupt" conn_id=0

**Comment by flike** [comment]
在客户端ctrl＋c中断并不会导致服务端的kingshard中断。
kingshard会响应SIGINT,SIGTERM,SIGQUIT这三个信号，平滑退出。在部署kingshard机器上应避免产生这三个信号，以免造成kingshard非正常退出！后台运行kingshard建议使用supervisor工具
