### ISSUE TITLE
抄袭

### ISSUE THREAD

**Issue by yuandunlong** [flike/kingshard#31]
大量代码涉嫌抄袭，还不标出源代码出处，悲哀！

**Comment by yuandunlong** [comment]
https://github.com/siddontang/mixer

**Comment by flike** [comment]
相关的License早已经在doc/License/ 下面了。如果这也算抄袭的话，那很多国内开源项目都是抄袭。

**Comment by flike** [comment]
作者和mixer作者也算是朋友。况且我开源这个项目之前，就已经联系过mixer作者了。

**Comment by flike** [comment]
同时附上mit协议说明：
http://www.ruanyifeng.com/blog/2011/05/how_to_choose_free_software_licenses.html
谢谢关注。
