### ISSUE TITLE
数据库中int类型字段，负值时查询结果出错

### ISSUE THREAD

**Issue by ycybaby** [flike/kingshard#310]
下面两处解析成Uint16和Uint32后，丢失符号，导致最后的int64值变成正的大值，需要中间先转为int16和int32，再转成int64：
		case MYSQL_TYPE_SHORT, MYSQL_TYPE_YEAR:
			if isUnsigned {
				data[i] = uint64(binary.LittleEndian.Uint16(p[pos : pos+2]))
			} else {
				data[i] = int64((binary.LittleEndian.Uint16(p[pos : pos+2])))
			}
			pos += 2
			continue

		case MYSQL_TYPE_INT24, MYSQL_TYPE_LONG:
			if isUnsigned {
				data[i] = uint64(binary.LittleEndian.Uint32(p[pos : pos+4]))
			} else {
				data[i] = int64(binary.LittleEndian.Uint32(p[pos : pos+4]))
			}
			pos += 4

**Comment by flike** [comment]
ok，我尽快确认

**Comment by flike** [comment]
已经修复，能否提供个test case 给我，我验证一下。
