### ISSUE TITLE
ERROR - conn.go:[280] - [server] "Run" "command *sqlparser.Set not supported now"

### ISSUE THREAD

**Issue by premier815** [flike/kingshard#311]
你好，我的项目使用了laravel框架。
kingshard版本：
Git commit:2017-01-15 10:26:49 +0800 @3b7060c
Build time:2017-01-23 17:13:48 +0800 by go version go1.7.4 linux/amd64
我使用的是 unshard.yaml
配置如下:

addr : 0.0.0.0:3306
user :  kingshard
password : kingshard
web_addr : 0.0.0.0:9797
web_user : admin
web_password : admin
log_path : /var/log/flike/
log_level : debug
log_sql: on
slow_log_time : 2
allow_ips: 192.168.0.110
proxy_charset: utf8
nodes :
-
    name : node1
    max_conns_limit : 32
    user :  root
    password : 123456
    master : 192.168.0.111:3306
    slave : 192.168.0.112:3306
    down_after_noalive : 120

schema :
    nodes: [node1]
    default: node1
    shard:
    -

其中 192.168.0.110是运行项目的web服务器，kingshard运作在上面，0.111是主库，0.112是从库。  
访问项目报如下错误：  
ERROR - conn.go:[280] - [server] "Run" "command *sqlparser.Set not supported now" "" conn_id=10001

对应的set语句是：set names 'utf8' collate 'utf8_unicode_ci'

**Comment by flike** [comment]
去掉引号，set names utf8 collate utf8_unicode_ci，试试看

**Comment by premier815** [comment]
还是报同样的错误:
 string(38) "set names utf8 collate utf8_unicode_ci"
Whoops, looks like something went wrong.

1/1
PDOException in MySqlConnector.php line 40:
SQLSTATE[HY000]: General error: 1105 command *sqlparser.Set not supported now
............

**Comment by flike** [comment]
ok，我尽快确认并跟进。

**Comment by flike** [comment]
请更新到最新代码，该命令已经支持了。

**Comment by Sentiger** [comment]
使用的larvel框架，直接使用pdo是可以运行的
![image](https://user-images.githubusercontent.com/6236245/96951369-ec254600-151e-11eb-892c-bd6847015660.png)

![image](https://user-images.githubusercontent.com/6236245/96951396-ff381600-151e-11eb-929d-cf36aa845d34.png)

**Comment by xchenhao** [comment]
> 使用 gorm https://github.com/go-gorm/gorm 查询 KingShard 以下 SQL 会报错: `command *sqlparser.SimpleSelect not supported now`
> 
> ```go
> var result struct {
>     Found bool `sql:"found"`
> }
> 
> db := gorm.Open('<kingshard dsn>')
> err := db.Raw('SELECT EXISTS(SELECT 1 FROM demo_table FROM WHERE id = 111 LIMIT) AS found').Scan(&result).Err
> if err != nil {
>     log.Fatal(err)
> }
> fmt.Println(result)
> ```
> 
> 查询 MySQL 是正常的

@flike
