### ISSUE TITLE
make时报错，

### ISSUE THREAD

**Issue by xfei6868** [flike/kingshard#32]
报错的详细信息如下：
go build -o bin/kingshard ./cmd/kingshard
load cmd/cgo: package cmd/cgo: open /home/work/.jumbo/lib/go/src/cmd/cgo: errno 530
make: *** [kingshard] Error 1

**Comment by flike** [comment]
你这个报错和kingshard没关系，安装步骤请参考文档进行。

**Comment by xfei6868** [comment]
嗯 这个错误的确是我的错误，同时碰到一个内外网ip兼容的问题。另外写个issues
