### ISSUE TITLE
读写分离路由错误

### ISSUE THREAD

**Issue by chenbo515** [flike/kingshard#322]
配置master,slave节点后,使用Jetbrain DataGrip管理工具打开数据表,默认会发送以下SQL
SET net_write_timeout=600
SET SQL_SELECT_LIMIT=502
SELECT t.* FROM xxx  t
kingshard日志显示前两句SET命令只被路由到master节点,SELECT命令被路由到slave节点,导致查询结果出错

**Comment by flike** [comment]
用/*master*/注释强制到master上读

**Comment by chenbo515** [comment]
谢谢
