### ISSUE TITLE
kingshard的稳定性怎么样？需要做HA双机热备吗？

### ISSUE THREAD

**Issue by zhangyc310** [flike/kingshard#324]
## 1.稳定性
除去硬件故障，kingshard软件自身的稳定性怎么样？需要做HA双机热备吗？
还是，kingshard自己是肯定不会出问题的？

同理请教一下，Nginx把请求转发给后台的duo台apache服务器，这个Nginx自己需要做热备吗？

## 2.热备
kingshard自己可以用于轻度的热备吗？因为mysql还是比较容易挂的。。。

**Comment by flike** [comment]
1. LVS+kingshard，可以保证kingshard层的高可用。

2.kingshard可以保证一主多从，从库宕机不受影响。

**Comment by fuxiangduan** [comment]
那 mysql server 元信息只能放在配置文件里吗，有没有存zk的方案，或者有什么方法可以动态更新
