### ISSUE TITLE
设置 127.0.0.1 后在局域网不能使用10.46.127.52 这样的ip访问 错误号：111

### ISSUE THREAD

**Issue by xfei6868** [flike/kingshard#33]
配置 addr : 127.0.0.1:8808  后
使用 mysqlclient 访问  10.46.127.52:8808 输入密码后，报错。错误码111

同样
addr : 10.46.127.52:8808 配置后，外部可以通过10.46.127.52连接成功了。
但是在本机使用 127.0.0.1 输入密码后同样是 111 的错误码

**Comment by sandeepone** [comment]
IMO Kingshard doesn't check password, it simply routes the query to the destination server with Kingshard config defined user/password

**Comment by flike** [comment]
set the config item addr to :0.0.0.0:9696
