### ISSUE TITLE
无法实现shard

### ISSUE THREAD

**Issue by cuipy** [flike/kingshard#331]
个人经验：
本人有十年的java开发经验，对数据库也很熟悉，linux也非常娴熟。
对于kingshard以前没有接触过，今天刚做实现准备学习学习。
go语言我没用过，今天为了用KingShard安装了一个go，调试一下应该没问题，helloworld程序可以编译执行。go version也输出了版本号。

配置kingShard的步骤：
0 准备虚拟机环境
在VMWare中创建3个CentOS虚拟机
版本为CentOS6.5
ip分别为：192.168.1.95 (KingShard)  192.168.1.96(node1)  192.168.1.97(node2)  

96和97上分别采用yum方式安装了mysql5.5，并设置用户名 root  密码：111111  
分别创建了数据库kingshard，
在node1下创建表t_test，包括一个主键id和testname字符串，总共就两个字段
node2下也这么创建的。

1 下载了go安装后，在/etc/profile下配置了环境变量：GOROOT  GOPATH  ，将$GOROOT/bin加入到PATH中。
测试go version和编译HelloWorld都没问题。
2 获取了KingShard的源代码
go get -u -v github.com/flike/kingshard 
3 编译
进入到KingShard的路径下执行  
source  dev.sh  
make

4 配置etc/ks.yaml

关键部分的配置
schema :
    nodes: [node1,node2]
    default: node1
    shard:
    -
        db : kingshard
        table: t_test
        key: id
        nodes: [node1, node2]
        type: hash
        locations: [1,1]

5 创建数据表
t_test_0000在node1下的kingshard库下；
t_test_0001在node2下的kingshard库下；

6 启动kingShard
bin/kingshard  -config  etc/ks.yaml

**问题出现了**：
使用sqlYog查看192.168.1.95:9696端口，应该看到的是一个数据表：t_test。
可事实上看到的是t_test_0000   
对其修改内容后，直接反映在t_test_0000上，无论添加多少数据，都只写t_test_0000表上。

**请问，这样的问题如何解决呢？**

**Comment by season89** [comment]
1.日志打印的是分表的rewrite sql，没毛病
2.表t_test的分区键是id，确认下每条sql的id字段值是否相同或者没区分开？
3.可以参照https://github.com/flike/kingshard/blob/master/doc/KingDoc/how_to_use_kingshard.md，进行hash分表实验
4.ks已经应用到几十家公司了，估计这不是个问题，可以多看下文档和测试样例

**Comment by cuipy** [comment]
1 没问题就好，我个人也感觉这里没问题。。。事实上我觉得哪儿都没有问题，毕竟我把个人经验给您说了您也能理解，我不应该犯特别低级的错误。
2 这个t_test表的id我也没有配置错，每个表都是id int not null auto_increment，而且我是新创建的表，都是空的，因此不存在数值相同的问题。而且，我还怕auto_increment造成问题，我也尝试了bigint类型和非auto_increment的设置。
3 这篇文章挺容易理解的，我整体操作linux，看这个不费劲。
4 我也觉得不是ks存在这么低级的错误，肯定是我疏忽了哪儿了。

**Comment by cuipy** [comment]
继续试验中，还是解决不了。
就这么简单的几个配置，我咋可能弄错呢。
我在windows下、linux下、家里的环境和公司的环境，各种环境都做了试验，结果都不行。
甚至我安装了LiteIDE自己调试，不过我不懂go语言，准备自学一下，好好看看具体问题是怎么回事。
我是不相信KingShard存在这个低级问题，肯定是我自己哪儿弄错了。我还是读读源代码吧。

**Comment by flike** [comment]
@cuipy ，你按照hash分表，id奇偶分别会插入到t_test_0000t_test_0001上，你可以对照SQL LOG看看。

**Comment by cuipy** [comment]
@flike 问题是现在通过kingshard看到的是default node中的那几个表，如t_test_0000；而不是一个t_test表。

**Comment by flike** [comment]
@cuipy 是这样的，不影响使用。

**Comment by cuipy** [comment]
我终于明白了，您这个代理就是这样的，看起来是没有合并成一个表，但用起来没问题，直接select查询也能查到。

**Comment by cuipy** [comment]
可以close了。
感觉您应该说明一下，在sqlyog等客户端工具中是看不到那个合并后的表的。
