### ISSUE TITLE
出现了KingShard启动很慢的问题

### ISSUE THREAD

**Issue by cuipy** [flike/kingshard#332]
这个问题很奇怪。
我分别在家和公司的两台计算机配置的VMWare+CentOS6.5的环境，安装的MySQL5.5,这些都一样，但公司的KingShard启动速度特别慢，大概一到两分钟才启动好，在家里的就是瞬间启动成功。启动后执行命令查看：

admin SERVER(opt,k,v) VALUES('show','proxy','config');
Key           Value         
------------  --------------
Addr          0.0.0.0:9696  
User          root          
LogPath                     
LogLevel      debug         
LogSql        on            
SlowLogTime   0             
Nodes_Count   2             
Nodes_List    node1,node2   
ClientConns   2             
ClientQPS     0             
ErrLogTotal   4             
SlowLogTotal  5             

admin SERVER(opt,k,v) VALUES('show','node','config');
Node    Address             Type    State   LastPing                       MaxConn  IdleConn  
------  ------------------  ------  ------  -----------------------------  -------  ----------
node1   192.168.6.115:3306  master  up      2017-05-05 10:13:52 +0800 CST  32       8         
node2   192.168.6.116:3306  master  up      2017-05-05 10:14:02 +0800 CST  32       8         

admin SERVER(opt,k,v) VALUES('show','schema','config');
DB         Table            Type     Key     Nodes_List    Locations  TableRowLimit  
---------  ---------------  -------  ------  ------------  ---------  ---------------
                            default          node1                    0              
kingshard  test_shard_hash  hash     id      node1, node2  4, 4       0              

似乎也配置成功了。

请问，这个启动速度慢的问题是怎么回事儿呢？

**Comment by flike** [comment]
启动慢可能是kingshard到后端db的网络连接问题。

**Comment by cuipy** [comment]
会否是因为我之前配置了mysql的master-id的问题？我之前在这两台虚拟机的MySQL上做了master/Slave，分别设置了master-id=1 和 master-id=2  ，然后还配置master的bin-log。
不过我为了做KingShard，将这些配置都注释了。

**Comment by cuipy** [comment]
flike，按说不是您说的那个问题，因为您看一下ping数据。
 ping 192.168.6.115
PING 192.168.6.115 (192.168.6.115) 56(84) bytes of data.
64 bytes from 192.168.6.115: icmp_seq=1 ttl=64 time=1.92 ms
64 bytes from 192.168.6.115: icmp_seq=2 ttl=64 time=0.247 ms
64 bytes from 192.168.6.115: icmp_seq=3 ttl=64 time=0.253 ms
64 bytes from 192.168.6.115: icmp_seq=4 ttl=64 time=0.263 ms
64 bytes from 192.168.6.115: icmp_seq=5 ttl=64 time=0.530 ms
64 bytes from 192.168.6.115: icmp_seq=6 ttl=64 time=0.184 ms
64 bytes from 192.168.6.115: icmp_seq=7 ttl=64 time=0.276 ms

这个似乎网络质量还不错，因为就是一台windows系统上的两个虚拟CentOS6.5。

**Comment by cuipy** [comment]
问题已经解决。
解决办法：在my.cnf的[mysqld]中加上skip-name-resolve的设置。
原因：通过192.168.*.*的局域网地址访问mysql的时候，会涉及到dns的访问，增加这个就不走dns服务了。至于为什么会走dns，我还不清楚。毕竟没有flike那样对数据库的深入理解。

**Comment by linux-mac** [comment]
这是 mysql 的事情，与 ks 无关

**Comment by cuipy** [comment]
是啊，我知道不是ks的问题，开始分析问题的时候不知道怎么回事，就问到这里了，解决后发现其实是mysql的问题。
