### ISSUE TITLE
调用db.close(conn)收到回复：ERROR 1105 (HY000): command 17 not supported now

### ISSUE THREAD

**Issue by ChengjinWu** [flike/kingshard#334]
如果有时间，请帮我看下这个问题。

python版本：Python2.7.11
用到的库：mysql-connector-python-2.1.6-py2.7-winx64.msi

代码如下：
`#! /usr/bin/env python
# -*- coding: utf-8 -*-
#date: 2013/12/27

import mysql.connector
import mysql.connector.pooling
from mysql.connector import errorcode
import sys

dbconfig = {
    "database": "app_news_test",
    "user": "spider",
    "password": "optaim",
    "host": "192.168.99.168",
    "port": 4000,
    "charset": 'utf8'
}
class DbHelper():
    def __init__(self):
        self.connPool = None
    def getConn(self):
        if self.connPool is None:
            self.connPool = mysql.connector.pooling.MySQLConnectionPool(pool_name = "mypool",
                                                                    pool_size = 8,
                                                                    **dbconfig)
        try:
            conn = self.connPool.get_connection()
        except mysql.connector.Error as err:
            if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
                print "something is wrong with your username or password"
            elif err.errno == errorcode.ER_BAD_DB_ERROR:
                print("Database does not exists")
            else:
                print err
            sys.exit(0)
        return conn

    def execute(self, conn, sql, params=()):
        try:
            cursor = conn.cursor(buffered=True)
            cursor.execute(sql, params)
        except Exception as e:
            raise e
        return cursor
    def close(self, conn):
        try:
            conn.close()
        except  Exception as e:
            print e
            print("Close db error!")

    def commit(self, conn):
        try:
            conn.commit()
        except Exception as e:
            print e

if __name__ == "__main__":
    db = DbHelper()
    conn = db.getConn()

    print '结束'
    db.close(conn)
    print '结束'`

**Comment by season89** [comment]
在self.connPool = mysql.connector.pooling.MySQLConnectionPool(pool_name = "mypool",
pool_size = 8,
**dbconfig)可以添加一个参数pool_reset_session=False即可。

**Comment by ChengjinWu** [comment]
It works！Thank you very much！

但是有个疑问：这样不删除session，session会不会一直存在服务器端，影响服务器性能。

**Comment by season89** [comment]
1.mysql connector的连接池调用close并不会关闭连接，只是将连接归还到pool中。
2.连接池或者长连接是db中常见的方案，只要在系统真正不需要连接时进行关闭即可，并不会影响ks的性能。

**Comment by ChengjinWu** [comment]
明白了，谢谢。
