### ISSUE TITLE
增加或减少node，如何迁移数据从而实现平滑扩容或缩容？

### ISSUE THREAD

**Issue by kingluo** [flike/kingshard#335]
例如hash路由规则，新增一个node，那么要手工扫全表然后计算每一行的hash值，从而决定该行是否迁入新node？
但是这个过程中也会不断有新数据入库，难道要不断重复上述过程，然后在某个时刻，将所有node设置为read only，再重复一次上述过程才能完成迁移数据？
但是设置所有node为read only，集群就有一段时间不能用了。
另外，kingshard本身更改路由配置（nodes配置），可以实现类似nginx那样的reload热更新吗？还是要restart？但是restart也会导致一小段时间，集群不能对外工作。

总而言之，作者可否提供一个完整的平滑扩容实例的文章给大家参考？

**Comment by flike** [comment]
恩，后续我增加一篇。目前部分配置支持热加载。详见管理端命令。
