### ISSUE TITLE
unshard.yaml配置的中slave从机如果宕机，服务会起不来

### ISSUE THREAD

**Issue by luyaotang** [flike/kingshard#340]
如果配置文件unshard.yaml中配置的从机如果宕机了，会使的服务直接起不来。很影响使用。因为有时候从机有问题，没来的及处理，此时正好又重启了ks，直接就导致ks无法启动。

**Comment by flike** [comment]
这种概率很小吧。你这时候可以把从机配置先去掉，就可以启动了。

**Comment by luyaotang** [comment]
关键是对运维的压力很大啊。从运维的角度来看，有些服务系统有些机制会自动重启某些服务，Reset环境。但此时我的从机宕机了，整个服务就起不来，有问题啊，这时候整个网站都连不上数据库了。在我看来，本来就是应该从机宕机了，我还可先让压力走主先，腾出时间来维护从机。不应该从机有问题，服务就直接起不来。

**Comment by luyaotang** [comment]
希望版主可以从运维的角度想想，而不是初次部署。

**Comment by flike** [comment]
明白，我觉得重启服务，你可以弄个配置只有主库，然后启动起来，再尝试将从库添加进来。

**Comment by season89** [comment]
@luyaotang  ks作为一个分库分表、db路由的核心组件，提供了供运维使用的功能，我理解这个问题是可以从运维工具、运维平台调用这个接口来解决的问题。
