### ISSUE TITLE
一共有1024张分表t_0000,t_0001,t_0002...t_1024，分在8个库中，每个库128张表，但是每个库的名字不一样，请问如何配置

### ISSUE THREAD

**Issue by feilongyang** [flike/kingshard#343]
我的物理DB拓扑图为：
db_0001
    t_0000,t_0001,t_0002,...,t_0127
db_0002
    t_0128,t_0001,t_0002,...,t_0255
db_0003
    t_0256,t_0001,t_0002,...,t_0383
db_0004
    t_0384,t_0001,t_0002,...,t_0511
db_0005
    t_0512,t_0001,t_0002,...,t_0639
db_0006
    t_0640,t_0001,t_0002,...,t_0767
db_0007
    t_0768,t_0001,t_0002,...,t_0895
db_0008
    t_0896,t_0001,t_0002,...,t_1023

每个DB的名字都不一样db_0001---db_0008
表的名字为t_0000---t_1023
请问如何指定schema的配置呢？非常感谢！

**Comment by season89** [comment]
You can reference "kingshard/etc/ks.yaml", add table in corresponding databases。

**Comment by alaxcc** [comment]
配置文件的目的都是为了可复用吧，比如每个库里分表多少张

我觉得你这个得修改源代码自定义开发了。。。
