### ISSUE TITLE
如果结果集过大，proxy的内存是否会存在很大压力？

### ISSUE THREAD

**Issue by kingluo** [flike/kingshard#344]
kingshard是接收完backend的response后再转发给client的（如果跨节点，转发前还会做整合），如果resultset特别大，例如全表返回，而kingshard对内存没有任何限制，那岂不是撑爆内存了？
可否做一些策略，例如：
* 不跨节点时，流式返回，也就是收到一个rowdata就返回一个
* 跨节点需要收完了整合，那么如果数据量太大，就直接返回错误给client，或者写临时文件暂存

不知道mysql本身（直连mysql）如何处理这类情况。

同理，如果请求包含的数据太大，例如insert提供的values过多，那是否应该限制一下呢？

**Comment by wangbin579** [comment]
比较好的方案是通过tcp stream来规避内存炸裂问题

**Comment by flike** [comment]
@kingluo ，这个问题确实可以这么解决。后续我会优化一下的。谢谢反馈。
