### ISSUE TITLE
Documentation and architecture diagrams in english?

### ISSUE THREAD

**Issue by pm-kartik-sura** [flike/kingshard#35]
Hi Team,

The package looks promising. I would like to get the architecture and usage docs in English.

**Comment by flike** [comment]
yeah, I've been aware of this problem. I will write the docs in English at weekend. Thank you for your attention. :)

**Comment by flike** [comment]
@pm-kartik-sura ,I add a  usage doc. :)

**Comment by sandeepone** [comment]
:+1:

**Comment by flike** [comment]
@sandeepone  :)
