### ISSUE TITLE
!!!!!! not in 查询 同一张子表内的数据不可见

### ISSUE THREAD

**Issue by Tieger** [flike/kingshard#351]
使用 not in 后 同一张表内的其他数据不可见.

mysql> select role_uuid, name from role_0072; 
+----------------------------------+--------------------------------------------------+
| role_uuid                        | name                                             |
+----------------------------------+--------------------------------------------------+
| fc7e6501d6cc4742989497d4681498b9 | 好尴尬                                           |
| 0a4ab0e5864c44d196598c945624cc9d | 少林大和尚阿为什么名字可以这么长                 |
+----------------------------------+--------------------------------------------------+
2 rows in set (0.00 sec)

mysql> 
mysql> SELECT role_uuid, name FROM role WHERE `role_uuid` NOT IN ("0a4ab0e5864c44d196598c945624cc9d") AND `name` LIKE "%好%";
+----------------------------------+--------+
| role_uuid                        | name   |
+----------------------------------+--------+
| 4869318850ce4d48806da26eef2cd3ce | 还好   |
+----------------------------------+--------+

**Comment by flike** [comment]
fixed
