### ISSUE TITLE
kingshard中配置两个DB的分表，结果第二个Db的分表报找不到

### ISSUE THREAD

**Issue by xiaojia1001** [flike/kingshard#356]
kingshard中配置两个DB的表，结果第二个Db的表报找不到，错误信息如下：

 ERROR - conn_query.go:[58] - [server] "preHandleShard" "ERROR 1146 (42S02): Table 'bee_app_shard.bbs_msg' doesn't exist" "sql=insert into `bbs_msg`(`site_id`,`board_id`,`discuss_id`,`bbs_id`,`feed_type`,`feed_id`,`user_id`,`user_org_id`,`task_status`,`is_read`,`created_at`) values(72112,50000106,0,50002009,'bbs',2420,62051318,54672,0,0,1501238266176)|hasHandled=false" conn_id=0

配置文件部分内容如下：
# node is an agenda for real remote mysql server.
nodes :
- 
    name : node1 

    # default max conns for mysql server
    max_conns_limit : 128

    # all mysql in a node must have the same user and password
    user :  root 
    password : quanshi

    # master represents a real mysql master server 
    master : 10.255.0.80:3306

    # slave represents a real mysql salve server,and the number after '@' is 
    # read load weight of this slave.
    #slave : 192.168.59.101:3307@2,192.168.59.101:3307@3
    down_after_noalive : 32

# schema defines sharding rules, the db is the sharding table database.
schema :
    nodes: [node1]
    default: node1      
    shard:
    -   
        db : taskserver
        table: manifest
        key: mf_id
        nodes: [node1]
        type: range
        locations: [3]
        table_row_base: 50000000
        table_row_limit: 500000
    -
        #分表使用的db
        db : bee_app_shard
        #分表名字
        table: bbs_msg
        #分表字段
        key: user_id
        #分表分布的node
        nodes: [node1]
        #分表类型
        type: hash
        #子表个数分布，表示node1有4个子表，
        #node2有4个子表。
        locations: [10]

**Comment by flike** [comment]
第二个分表配置应该是没有生效

**Comment by xiaojia1001** [comment]
那如何让第二个分表配置生效呢？是kingshard的已知bug吗？

**Comment by flike** [comment]
不是

**Comment by huadaonan** [comment]
如何解决呢
