### ISSUE TITLE
关于性能的问题

### ISSUE THREAD

**Issue by Vortexxxx** [flike/kingshard#358]
架构如下：

kingshard server 8核

master-db 12核
slave-db * 2  12核

尝试性的在项目引入kingshard之后发现性能大幅下降，上面所有的机器负载都没有超过5的

通过sql日志看到有大量比较慢的查询（超过5000ms），但是复制这些语句直接登录kingshard的接口执行查询发现并不慢，数据库的慢查询也没有记录到此类语句

机器都是在内网，Proxy的服务器负载也不高，实在不明白啥情况，求指点

**Comment by flike** [comment]
应该是程序问题吧。在kingshard命令行不慢，基本可以排除kingshard到mysql的性能没问题。

**Comment by Vortexxxx** [comment]
之前提的sql日志有大量超过5000ms的查询是通过kingshard的日志看到的
