### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by matjazmav** [flike/kingshard#361]
This project shows potencial, but without good documentation it is hard to use it. I would love to see EN documentation on configuration and maybe few examples or blog posts with simple guides.

**Comment by flike** [comment]
https://github.com/flike/kingshard/blob/master/doc/KingDoc/how_to_use_kingshard_EN.md

**Comment by matjazmav** [comment]
Well, for example what does it mean `locations: [4,4]` where can I learn that?

**Comment by flike** [comment]
means in the first node has 4 sub-tables, and in the second node has four sub-tables
