### ISSUE TITLE
关于kingshard连接池中连接不断丢失的问题

### ISSUE THREAD

**Issue by xiaojia1001** [flike/kingshard#362]
问题：在非分表情况下事务内的SQL预处理，用完连接后没有释放会连接池，导致连接没有关闭，最终连接池中无连接可用

分析：看了连接相关的代码，基本锁定conn_stmt.go 79行获取连接的方式不对，个人认为用c.GetBackendConn()而不是n.GetMasterConn()， 麻烦帮忙确认下

func (c *ClientConn) handleStmtPrepare(sql string) error {
	if c.schema == nil {
		return mysql.NewDefaultError(mysql.ER_NO_DB_ERROR)
	}

	s := new(Stmt)

	sql = strings.TrimRight(sql, ";")

	var err error
	s.s, err = sqlparser.Parse(sql)
	if err != nil {
		return fmt.Errorf(`parse sql "%s" error`, sql)
	}

	s.sql = sql

	defaultRule := c.schema.rule.DefaultRule

	n := c.proxy.GetNode(defaultRule.Nodes[0])

	co, err := n.GetMasterConn()
	defer c.closeConn(co, false)
	if err != nil {
		return fmt.Errorf("prepare error %s", err)
	}

	err = co.UseDB(c.db)
	if err != nil {
		//reset the database to null
		c.db = ""
		return fmt.Errorf("prepare error %s", err)
	}

	t, err := co.Prepare(sql)
	if err != nil {
		return fmt.Errorf("prepare error %s", err)
	}
	s.params = t.ParamNum()
	s.columns = t.ColumnNum()

	s.id = c.stmtId
	c.stmtId++

	if err = c.writePrepare(s); err != nil {
		return err
	}

	s.ResetParams()
	c.stmts[s.id] = s

	err = co.ClosePrepare(t.GetId())
	if err != nil {
		return err
	}

	return nil
}

**Comment by flike** [comment]
1.用GetMasterConn函数表示只在master上取连接。prepare实现这么做的原因是实现简单。你说的事务连接未释放指的是这个地方吗：

```
func (c *ClientConn) closeConn(conn *backend.BackendConn, rollback bool) {
	if c.isInTransaction() {
		return
	}

	if rollback {
		conn.Rollback()
	}

	conn.Close()
}
```

**Comment by xiaojia1001** [comment]
嗯，如果handleStmtPrepare在事务中执行，那么这个closeConn方法里就不会释放事务，会等到commit时从txConns里释放。但handleStmtPrepare里获取连接时并没有向txConns里存放（如果在事务中），所以这里连接就会释放不掉

**Comment by xiaojia1001** [comment]
嗯，如果handleStmtPrepare在事务中执行，那么这个closeConn方法里就不会释放连接，会等到commit时从txConns里释放。但handleStmtPrepare里获取连接时并没有向txConns里存放（如果在事务中），所以这里连接就会释放不掉

**Comment by flike** [comment]
是的。仔细想了一下，不能直接调用GetMasterConn或GetSlaveConn函数，因为如果处于事务中调用这两个函数，都会导致conn泄露。所以，我把代码中其他两处也修改了一下。如果不对之处，还请指正。谢谢反馈。:)
