### ISSUE TITLE
kingshard实现多租户的可能性

### ISSUE THREAD

**Issue by Septemberd** [flike/kingshard#364]
我看到kingshard有hash和range方式来进行分表分库，我想用ks来实现多租户的数据隔离。是否会考虑可以来实现多租户的数据隔离访问？如果可以在ks这层实现，那就对应用层开发人员透明，不需要关注租户。
第一种：schema级别的隔离，比如有个order分表，在这一层识别租户身份，不同的租户访问自己的order表。
第二种：通过表字段tenant_id隔离，在这一层识别当前访问租户，带上tenant_id作为条件.

**Comment by ltt1987** [comment]
理论上肯定是可以的，不过可能需要自己修改源代码来实现了。

**Comment by flike** [comment]
已经实现。

**Comment by Hanson** [comment]
@flike 是如何实现呢？还没看到相关的文档介绍

**Comment by wimmerX** [comment]
@Hanson @Septemberd 两位找到相关文档了么？如果有，可否分享我一下，谢谢啦

**Comment by wimmerX** [comment]
@Septemberd @Hanson 两位有找到相关的文档么？有的话，可以分享给我一份么？谢谢啦

**Comment by Hanson** [comment]
@wimmerX 没有也没用 kingshard，已经不再维护了
