### ISSUE TITLE
thinkphp5 使用join联合查询报错

### ISSUE THREAD

**Issue by langjitianya123** [flike/kingshard#368]
thinkphp5项目中使用kingshard后，分表和普通表join联合查询的时候报错，SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xungen_dist.clan_stemma' doesn't exist。数据库中.clan_stemma表是确实存在的，这是哪里出错呢？

**Comment by qifenshu** [comment]
好像在哪里喵到不支持这种情况的join，不过不是很确定。

**Comment by flike** [comment]
分表和join的非分表必须在一个node上。
