### ISSUE TITLE
除了事务，还有那些方法可以让前端多个请求使用同一个后端连接?

### ISSUE THREAD

**Issue by wangcn** [flike/kingshard#372]
目前在使用阿里云的drds，它的分布式事务的使用方法是：
set autocommit=0;
select last_txc_xid();
begin;
//business code
commit;
关键在于头两行，因为执行在事务前，没有和后面的事务使用同一个后端连接，导致分布式事务失败。

有没有办法解决？

**Comment by wangcn** [comment]
能不能遇到set autocommit=0;就保证使用同一个后端连接？

**Comment by flike** [comment]
可以。
