### ISSUE TITLE
kingshard能不能只分库不分表，该如何配置?

### ISSUE THREAD

**Issue by zhonglushu** [flike/kingshard#375]
现在有一个场景是需要创建很多张表，而且数量是不确定的，但是每张表的数据量有限，所以不需要分表，kingshard能不能将表分配到不同的数据库，同时又不对表进行拆分，需要怎么配置呢？

**Comment by zhonglushu** [comment]
有些大表需要分表，有些不需要分表，该如何配置？

**Comment by flike** [comment]
不分表必须放在default node下面。分表的话需要配置规则。

**Comment by zhonglushu** [comment]
那样的话只能定制了
