### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by szjeffluo** [flike/kingshard#377]
crash stack is:

github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc4206b3dd0)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c2d40, 0xa18c00)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc42013c0e0, 0xf, 0xc42013c090, 0x7, 0xc42013c0b0, 0xb, 0x0, 0x0, 0x0, ...)
        /usr/local/kingshard/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc420188090, 0xc4201ba0c0, 0xc4201ba060, 0x1, 0xc420702a70, 0xc4206b3a80)
        /usr/local/kingshard/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc420188090, 0x30, 0xc4204f1260, 0x0)
        /usr/local/kingshard/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc420188090, 0xc42018e370, 0x0, 0xc42005cc00)
        /usr/local/kingshard/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc4201860e0, 0x80f740, 0x5d9601, 0xc4204f1260)
        /usr/local/kingshard/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc42065a900, 0xc4201860e0, 0xc4204f1200, 0x0, 0xc4204f1260, 0x1)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).getShardConns(0xc42065a900, 0xc420531500, 0xc420405ea0, 0x9ee0e0, 0xc420405e30, 0xc420405ea0)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn_query.go:183 +0x2ff
github.com/flike/kingshard/proxy/server.(*ClientConn).handleExec(0xc42065a900, 0x9ee0e0, 0xc420405e30, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn_query.go:355 +0xbc
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc42065a900, 0xc4200a08c1, 0xda, 0x0, 0x0)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn_query.go:76 +0x75e
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc42065a900, 0xc4200a08c0, 0xdb, 0xdb, 0x0, 0x0)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc42065a900)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc420068800, 0x9f2fa0, 0xc4200761c8)
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
        /usr/local/kingshard/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e

**Comment by flike** [comment]
fixed
