### ISSUE TITLE
sysbench1.0.6压测kingshard，运行oltp_update_index.lua，crash

### ISSUE THREAD

**Issue by lkjx82** [flike/kingshard#383]
运行：
`sysbench /usr/share/sysbench/oltp_update_index.lua --db-driver=mysql --mysql-host=[kingshard ip] --mysql-port=9696 --mysql-db=tst --mysql-user=kingshard --mysql-password=kingshard --table_size=5000000 --tables=10 --threads=300 --time=60 --report-interval=10  run`

kingshard 会crash
`
2017/10/16 15:09:27 - ERROR - conn.go:[263] - [ClientConn] "Run" "runtime error: index out of range" "stack=goroutine 3014 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).Run.func1(0xc4213ef2c0)
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/conn.go:259 +0xf5
panic(0x7c3d60, 0xa19c40)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/proxy/server.(*ClientConn).bindStmtArgs(0xc4213ef2c0, 0xc4212b82d0, 0xc4205e36aa, 0x1, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/conn_stmt.go:350 +0x10ca
github.com/flike/kingshard/proxy/server.(*ClientConn).handleStmtExecute(0xc4213ef2c0, 0xc4205e36a1, 0x13, 0x13, 0x0, 0x0)
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/conn_stmt.go:233 +0x1d2
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc4213ef2c0, 0xc4205e36a0, 0x14, 0x14, 0x0, 0x0)
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/conn.go:316 +0x5a9
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc4213ef2c0)
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f3fa0, 0xc420654620)
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
	/home/lbh/kingshard/src/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
" conn_id=0
`

**Comment by lkjx82** [comment]
sysbench 老的lua测试脚本没问题，如**/usr/local/sysbench/db/oltp.lua**
原因是1.0.6的测试脚本里，跑的是一次prepare，一次bind，重复多次stmt_execute。用php写脚本同样的测试方法，会出现同样的问题。
原因是COM_EXECUTE报文格式解析的时候，Null-Bitmap后面的一个byte为0时，表示是否传递field类型给服务器。重复执行stmt_execute 时，stmt的参数不为0的情况下，bindStmtArgs函数内会从len=0的paramTypes中取元素，导致服务器crash。

可以在Stmt struct中增加一个字段，缓存上次的字段类型，当报文里没有包含字段类型时，从缓存中取。可以解决问题

**Comment by flike** [comment]
分表不支持prepare操作。
