### ISSUE TITLE
sysbench1.0.6压测kingshard，运行oltp_read_only.lua，

### ISSUE THREAD

**Issue by lkjx82** [flike/kingshard#384]
`
sysbench /usr/share/sysbench/oltp_read_only.lua --db-driver=mysql --mysql-host=[kingshard ip] --mysql-port=9696 --mysql-db=tst --mysql-user=kingshard --mysql-password=kingshard --table_size=5000000 --tables=10 --threads=300 --time=60 --report-interval=10 run
`

kingshard 报错
`
 ERROR - conn.go:[280] - [server] "Run" "prepare error ERROR 1295 (HY000): This command is not supported in the prepared statement protocol yet" "" conn_id=11184
`

sysbench 提示错误
`MySQL error: 1105 "prepare error ERROR 1295 (HY000): This command is not supported in the prepared statement protocol yet"
FATAL: `thread_init' function failed: /usr/share/sysbench/oltp_common.lua:273: SQL API error`

sysbench 里的lua对应行为：
`
 stmt.begin = con:prepare("BEGIN")
`

**Comment by jzdxeb** [comment]
`--skip-trx=on`
