### ISSUE TITLE
commiter

### ISSUE THREAD

**Issue by kobehaha** [flike/kingshard#385]
如果成为你们的提交者呢,有什么要求吗

**Comment by kobehaha** [comment]
## 建议考虑增加一些功能

1 增加master-slave delay 监听，当delay大于一个值slave考虑从服务列表中踢掉,当小于一个值可以自动恢复,我用 lvs + perl脚本可以实现,不过还是建议考虑在代码中处理可能更改一些。这样会体验可能会更好一些

2 自动识别Master-slave,. 现在程序配置master , slave 后，当线性的更改master----> slave ， 而slave变为新的master 这种情况需要重启服务. 我的想法来源于我们生产环境下mha的使用情况. 如果这样处理mha 和kingsharding 无限接的组合

这只是我一些场景下的思考，小建议，谢谢

**Comment by flike** [comment]
@kobehaha ，非常感谢你的建议。成为commiter，先从bugfix或小的feature开始。有意者直接联系我就行（加Q或邮件）。
第一点确实可以实现，但第二点切主就没那么容易，因为涉及到数据完整性。

**Comment by kobehaha** [comment]
@flike 关于第二点.我的意思是Ksharding程序可以和mha结合.数据完整性切换和数据恢复用mha来做，并不耦合,然后Ksharding程序增加检测配置中mysql列表的状态,获取他们的salve_status状态就可以重新获取slave,也可以获取新的master. 这样ksharding在master切换过程中不可用,当mha切换完成,ksharding获取新的主从状态，又从新服务.

mha 略看 https://github.com/yoshinorim/mha4mysql-manager/wiki/Overview
详情可以查看 https://github.com/yoshinorim/mha4mysql-manager/wiki

个人认为这丰富了系统特性也增强了系统可用性

**Comment by kobehaha** [comment]
@flike 关于第一点. 方便把你的QQ发到我邮箱zhangzhiyuan218@gmail.com吗

**Comment by flike** [comment]
569732821
