### ISSUE TITLE
checkMaster失败导致主节点不恢复问题

### ISSUE THREAD

**Issue by htner** [flike/kingshard#387]
node.go checkMaster() 函数 
1. 96行 判断如果n.master为空将不再检查,直接返回 
2. 106行 n.UpMaster(db.addr)可能会将n.master设置为空

那是否连接主节点的网络抖动后，可能会出现再也不能恢复的情况？

补充相关日志:
2017/10/18 20:42:08 - ERROR - node.go:[102] - [Node] "checkMaster" "Ping" "db.Addr=starmaker-live.cczpbf5hc2kb.us-west-2.rds.amazonaws.com:3306|error=connection was bad" conn_id=0
2017/10/18 20:44:32 - ERROR - node.go:[254] - [Node] "UpMaster" "dial tcp 34.210.172.35:3306: getsockopt: connection timed out" "" **conn_id=0**
2017/10/18 20:44:48 - ERROR - node.go:[97] - [Node] "checkMaster" "Master is no alive" "" conn_id=0

**Comment by wfxiang08** [comment]
@flike 我刚刚也发了一个pull request, 结果发现你已经改了。不过咱两的侧重点有点点不一样，你看看
https://github.com/flike/kingshard/pull/388

不过你修改的比较简洁。
