### ISSUE TITLE
 ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "

### ISSUE THREAD

**Issue by luyaotang** [flike/kingshard#389]
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsshoptrade" AND valid = 1" conn_id=0
2017/10/23 00:37:17 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:37:17 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:37:17 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188276 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc420229dd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0x8, 0xc42006ba00, 0xc420147a40)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0x8, 0xc420147ab0, 0x5f0a47)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0xc42003cc20, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc42003cc20, 0xc420147b18, 0x5f052e)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc4201c8480, 0xc420090380, 0x0, 0xe, 0xc42006c901, 0x73)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc4201c8480, 0xc42006c901, 0x73, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc4201c8480, 0xc42006c901, 0x73, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc4201c8480, 0xc42006c900, 0x74, 0x74, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc4201c8480)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc4203b4188)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsshopmch" AND valid = 1" conn_id=0
2017/10/23 00:37:17 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188275 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc4202dbdd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0x8, 0xc42006ba00, 0xc42020fa40)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0x8, 0xc42020fab0, 0x5f0a47)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0xc4201ab6c0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc4201ab6c0, 0xc42020fb18, 0x5f052e)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc4201c83c0, 0xc420090380, 0x0, 0xe, 0xc4201cae81, 0x76)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc4201c83c0, 0xc4201cae81, 0x76, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc4201c83c0, 0xc4201cae81, 0x76, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc4201c83c0, 0xc4201cae80, 0x77, 0x77, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc4201c83c0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc4203b4178)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsgasoiluser" AND valid = 1" conn_id=0
2017/10/23 00:37:17 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:37:17 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188253 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc4202d9dd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0x8, 0xc42006ba00, 0xc420368a40)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0x8, 0xc420368ab0, 0x5f0a47)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0xc42026e2c0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc42026e2c0, 0xc420368b18, 0x5f052e)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc4203caf00, 0xc420090380, 0x0, 0xe, 0xc4203c4301, 0x75)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc4203caf00, 0xc4203c4301, 0x75, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc4203caf00, 0xc4203c4301, 0x75, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc4203caf00, 0xc4203c4300, 0x76, 0x76, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc4203caf00)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc420530120)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsgasoilmch" AND valid = 1" conn_id=0
2017/10/23 00:37:17 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:37:17 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188263 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc42022fdd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0x8, 0xc42006ba00, 0xc42020fa40)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0x8, 0xc42020fab0, 0x5f0a47)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0xc4201ab940, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc4201ab940, 0xc42020fb18, 0x5f052e)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc420113140, 0xc420090380, 0x0, 0xe, 0xc4201cb101, 0x72)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc420113140, 0xc4201cb101, 0x72, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc420113140, 0xc4201cb101, 0x72, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc420113140, 0xc4201cb100, 0x73, 0x73, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc420113140)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc4201d0110)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsgasoil" AND valid = 1" conn_id=0
2017/10/23 00:37:17 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:37:17 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188264 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc42033bdd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0x8, 0xc42006ba00, 0xc420369a40)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0x8, 0xc420369ab0, 0x5f0a47)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0xc42003cda0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc42003cda0, 0xc420369b18, 0x5f052e)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc420113200, 0xc420090380, 0x0, 0xe, 0xc42006ca81, 0x75)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc420113200, 0xc42006ca81, 0x75, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc420113200, 0xc42006ca81, 0x75, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc420113200, 0xc42006ca80, 0x76, 0x76, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc420113200)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc4201d0118)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsgasrefund" AND valid = 1" conn_id=0
2017/10/23 00:37:26 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=719392
2017/10/23 00:37:26 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:37:27 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=24842090
2017/10/23 00:37:27 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:37:43 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=291805
2017/10/23 00:37:43 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:37:44 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:37:44 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188298 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc42022ddd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0x8, 0xc42006ba00, 0xc420142a40)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0x8, 0xc420142ab0, 0x5f0a47)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0xc42026e9c0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc42026e9c0, 0xc420142b18, 0x5f052e)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc4203cb080, 0xc420090380, 0x0, 0xe, 0xc4203c4501, 0x75)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:116 +0x2bb
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc4203cb080, 0xc4203c4501, 0x75, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc4203cb080, 0xc4203c4501, 0x75, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc4203cb080, 0xc4203c4500, 0x76, 0x76, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc4203cb080)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc420530188)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
|sql=SELECT/*master*/ value_start, value_last FROM system_variable WHERE mainkey = "Statisticsshoptrade" AND valid = 1" conn_id=0
2017/10/23 00:37:47 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=719395
2017/10/23 00:37:47 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:38:22 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=24842163
2017/10/23 00:38:22 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:38:31 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=291806
2017/10/23 00:38:31 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:38:44 - ERROR - db.go:[313] - [db.go] "GetConnFromIdle" "Get conn in default" "" conn_id=0
2017/10/23 00:38:44 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 7188335 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc420339dd0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x1f0
panic(0x7c3d60, 0xa18c00)
/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/flike/kingshard/backend.(*Conn).Connect(0x0, 0xc420107de0, 0x11, 0xc420011f80, 0xd, 0xc420107d40, 0x11, 0x0, 0x0, 0x0, ...)
/usr/lib/go/src/github.com/flike/kingshard/backend/backend_conn.go:57 +0x2b
github.com/flike/kingshard/backend.(*DB).GetConnFromIdle(0xc4200d6360, 0xc420067ce0, 0xc420067c80, 0xc420112900, 0xc4204abd40, 0x19)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:314 +0x3f8
github.com/flike/kingshard/backend.(*DB).PopConn(0xc4200d6360, 0xc4202be180, 0xc420339aa8, 0x5f0430)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:255 +0x15a
github.com/flike/kingshard/backend.(*DB).GetConn(0xc4200d6360, 0x19, 0x19, 0xc4202be180)
/usr/lib/go/src/github.com/flike/kingshard/backend/db.go:363 +0x2f
github.com/flike/kingshard/backend.(*Node).GetMasterConn(0xc420090380, 0xc420200db0, 0xc420090380, 0xa418a0)
/usr/lib/go/src/github.com/flike/kingshard/backend/node.go:73 +0x6b
github.com/flike/kingshard/proxy/server.(*ClientConn).getBackendConn(0xc420112900, 0xc420090380, 0x0, 0x19, 0xc420084281, 0x120)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:127 +0x31f
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc420112900, 0xc420084281, 0x120, 0x0, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:95 +0x28a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc420112900, 0xc420084281, 0x120, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xfb
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc420112900, 0xc420084280, 0x121, 0x121, 0x0, 0x0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:306 +0x4f4
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc420112900)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x93
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc42000ac00, 0x9f2fa0, 0xc4201d00a0)
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x326
created by github.com/flike/kingshard/proxy/server.(*Server).Run
/usr/lib/go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x15e
2017/10/23 00:38:47 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=24842187
2017/10/23 00:38:47 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:38:48 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=719398
2017/10/23 00:38:48 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:39:02 - ERROR - conn.go:[280] - [server] "Run" "ERROR 1062 (23000): Duplicate entry 'oj9Drw9GaRbgmbFtqj9fBaX2jNTA' for key 'openid'" "" conn_id=24842222
2017/10/23 00:39:03 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=291808
2017/10/23 00:39:03 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:39:06 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=719399
2017/10/23 00:39:06 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:39:44 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=24842305
2017/10/23 00:39:44 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:39:51 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=291810
2017/10/23 00:39:51 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:40:07 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=24842385
2017/10/23 00:40:07 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0
2017/10/23 00:40:09 - ERROR - conn.go:[106] - [server] "readHandshakeResponse" "connection was bad" "msg=read Handshake Response error" conn_id=719402
2017/10/23 00:40:09 - ERROR - server.go:[357] - [server] "onConn" "connection was bad" "" conn_id=0

**Comment by luyaotang** [comment]
此前是一直工作正常的，某天连接报错如上。ks用的是现在最新版本。

**Comment by flike** [comment]
我尽快跟进。
