### ISSUE TITLE
db 连接数限制

### ISSUE THREAD

**Issue by jzdxeb** [flike/kingshard#393]
请顺在`GetConnFromIdle`中default 是新建 connection 
这样client连接数不就不可控了吗？

**Comment by flyingrass** [comment]
我们测试的结果也确定了，实际上有新的请求过来时，不会受限于max_conns_limit的设置，还是会新建连接并转发请求到MySQL上，只是超过max_conns_limit设置的连接在请求完成后会立即销毁。

**Comment by flike** [comment]
是的，当时考虑到尽量保证业务正常。后续考虑还是使用之前的方式，一直阻塞，直到有可用连接。

**Comment by flike** [comment]
已修改
