### ISSUE TITLE
请问一下，目前有在生产环境使用的案例吗？

### ISSUE THREAD

**Issue by xgfone** [flike/kingshard#397]
公司使用一个新项目，肯定会有这方面的考虑，尤其是数据库方面的。

----------------------

Update：

如果是单纯的App，出了BUG，也没太大的问题，但数据库不一样，一旦出了问题，造成的影响会很大的。所以不得不有个考虑，望理解！

**Comment by flike** [comment]
之前统计过，大概有20+公司在使用。详细的名单参考 ：https://github.com/flike/kingshard/issues/148
