### ISSUE TITLE
通过kingshard查看的数据库table和直接登入节点查看数据库table不一致

### ISSUE THREAD

**Issue by gibbsqi** [flike/kingshard#407]
hi, flike
测试环境如下：
有四台测试机。一台安装有kingshard，两台安装mysql(作为kingshard的两个节点，都只有主，没有从)。还有另外一台当成客户端测试机(安装有sysbench性能测试工具)。

通过sysbench在sbtest数据库(事先在两个节点上都创建好了sbtest数据库)下创建了10个table。

查询表的时候，发现通过kingshard查询sbtest数据库的表，两个节点都有10个表，如下图：
![kingshard_node](https://user-images.githubusercontent.com/34825300/34332046-4cacf09a-e967-11e7-8152-fc41531e9b76.png)

分别登入两台node服务器，node1的sbtest数据库有10个表，但是node2的sbtest数据库是空的。
(实际上也是node1的sbtest数据库有10个表，node2的sbtest数据库中没有表)

登入node1的查询结果：
![kingshard_node1](https://user-images.githubusercontent.com/34825300/34332067-98226406-e967-11e7-9fc3-d7c100c54d76.png)

登入node2的查询结果：
![kingshard_node2](https://user-images.githubusercontent.com/34825300/34332072-a77455d6-e967-11e7-8890-b4f21104cccd.png)

配置kingshard环境是，node1是default node。

mysql版本：5.7.19

**Comment by gibbsqi** [comment]
另外再咨询一下，kingshard如何实现主从复制的，如何配置？

我在主mysql服务器上的数据库中创建了一张表，往里面插入了数据，但是从服务器上没看到对应的更新

**Comment by flike** [comment]
kingshard目前只会默认显示default node上的表结构。如果需要查看其它node，请通过注释方式。例如:
`/*node2*/ show database`
kingshard不负责主从复制。

**Comment by gibbsqi** [comment]
谢谢你的回复，后来我是使用了mysql的主从复制来实现的

**Comment by gibbsqi** [comment]
另外，还是前面的服务器框架，一台kingshard，一台主mysql，一台从mysql，另外是安装了sysbench的服务器。
测试性能数据时，发现读写数据都是访问主服务器。
![kingshard_oltp](https://user-images.githubusercontent.com/34825300/34476342-e143438a-efca-11e7-9e6d-625682485746.png)

这是什么情况导致的？

配置文件如下：
![config1](https://user-images.githubusercontent.com/34825300/34476587-08ac11de-efcd-11e7-9f94-b1787f2f80d9.png)

**Comment by gibbsqi** [comment]
主服务器和从服务器设置了相同的mysql登入用户名和密码。

准备样本数据时，从服务器有从主服务器同步更新数据

**Comment by flike** [comment]
应该是开启了事务
