### ISSUE TITLE
分表与全局表做join出错

### ISSUE THREAD

**Issue by ittuotuo** [flike/kingshard#411]
test_global 在node1 kingshard schema内
test_shard_hash 是hash分表，0000-0003在node1 kingshard,0004-0007在node2 kingshard
两表做join操作
"select test_shard_hash.id,test_global.id from test_shard_hash as a  join test_global as b on a.id=b.id;"
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 1: Unknown column 'test_shard_hash_0000.id' in 'field list'

**Comment by ittuotuo** [comment]
node1:
"/*node2*/show tables;"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------------------+
| Tables_in_kingshard  |
+----------------------+
| test_shard_hash_0004 |
| test_shard_hash_0005 |
| test_shard_hash_0006 |
| test_shard_hash_0007 |
+----------------------+
"/*node1*/show tables;"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------------------+
| Tables_in_kingshard  |
+----------------------+
| test_global          |
| test_shard_hash_0000 |
| test_shard_hash_0001 |
| test_shard_hash_0002 |
| test_shard_hash_0003 |
+----------------------+
"/*node1*/show create table test_global;"
mysql: [Warning] Using a password on the command line interface can be insecure.
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test_global | CREATE TABLE `test_global` (
  `id` bigint(64) unsigned NOT NULL,
  `hash_id` bigint(64) unsigned NOT NULL,
  `str` varchar(256) DEFAULT NULL,
  `f` double DEFAULT NULL,
  `e` enum('test1','test2','test3','test4','test5','test6','test7','test8','test9','test10') DEFAULT NULL,
  `u` tinyint(3) unsigned DEFAULT NULL,
  `i` tinyint(4) DEFAULT NULL,
  `ni` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by ittuotuo** [comment]
问题已查明，实际上join想用还是比较麻烦，因为kingshard没有全局表的功能。。

**Comment by dscxieyong** [comment]
所以join功能目前无法支持是吗
