### ISSUE TITLE
plan have no criteria 错误

### ISSUE THREAD

**Issue by bbsyaya** [flike/kingshard#412]
在centos7.0 上使用的 kingshard的，运行一段时间后 经常出现
2018/02/01 07:34:06 - ERROR - router.go:[331] - [Route] "BuildSelectPlan" "plan have no criteria" "" conn_id=0
2018/02/01 07:34:06 - ERROR - conn.go:[280] - [server] "Run" "plan have no criteria" "" conn_id=10037
2018/02/01 07:34:51 - ERROR - router.go:[331] - [Route] "BuildSelectPlan" "plan have no criteria" "" conn_id=0
2018/02/01 07:34:51 - ERROR - conn.go:[280] - [server] "Run" "plan have no criteria" "" conn_id=10037

**Comment by flike** [comment]
这个意思就是该表没有设置路由规则。需要设置一下路由规则，或者将其放入默认db
