### ISSUE TITLE
怎样在一个配置里连接多个db？

### ISSUE THREAD

**Issue by jueljust** [flike/kingshard#413]
我有一组配置如下, 企图在一个kingshard里管理两个物理机的分片，但配置不对
报

    ERROR - main.go:[102] - [main] "main" "schema must have a node" "" conn_id=0

不知道是配置问题 还是kingshard不支持 麻烦大家帮我看一下
具体配置如下

	# server listen addr
	addr : 0.0.0.0:9898

	# server user and password
	user :  kingshard
	password : kingshard

	# the web api server
	web_addr : 0.0.0.0:9999
	#HTTP Basic Auth
	web_user : admin
	web_password : admin

	# if set log_path, the sql log will write into log_path/sql.log,the system log
	# will write into log_path/sys.log
	log_path : /path/to/log

	# log level[debug|info|warn|error],default error
	log_level : error

	# if set log_sql(on|off) off,the sql log will not output
	log_sql: off

	# only log the query that take more than slow_log_time ms
	#slow_log_time : 100

	# the path of blacklist sql file
	# all these sqls in the file will been forbidden by kingshard
	#blacklist_sql_file: /Users/flike/blacklist

	# only allow this ip list ip to connect kingshard
	allow_ips : 127.0.0.1

	# the charset of kingshard, if you don't set this item
	# the default charset of kingshard is utf8.
	proxy_charset: utf8

	# node is an agenda for real remote mysql server.
	nodes :
	-
		name : config_log

		# default max conns for mysql server
		max_conns_limit : 32

		# all mysql in a node must have the same user and password
		user :  "user"
		password : "pass"

		# master represents a real mysql master server
		master : config_log:3306

		# slave represents a real mysql salve server,and the number after '@' is
		# read load weight of this slave.
		#slave : 192.168.59.101:3307@2,192.168.59.101:3307@3
		down_after_noalive : 32
	-
		name : relation

		# default max conns for mysql server
		max_conns_limit : 32

		# all mysql in a node must have the same user and password
		user :  "user"
		password : "pass"

		# master represents a real mysql master server
		master : relation:3306

		# slave represents a real mysql salve server,and the number after '@' is
		# read load weight of this slave.
		#slave : 192.168.59.101:3307@2,192.168.59.101:3307@3
		down_after_noalive : 32

	# schema defines sharding rules, the db is the sharding table database.
	schemas :
	-
		db : db_config_log
		nodes: [config_log]
		default: config_log
		shard:
		-
			table: log
			key: id
			nodes: [config_log]
			type: hash
			locations: [64]
	-
		db : db_relation
		nodes: [relation]
		default: relation
		shard:
		-
			table: relation
			key: uuid
			type: hash
			nodes: [relation]
			locations: [64]

**Comment by flike** [comment]
配置文件没有设置好。设置好配置文件后，先校验一下yaml格式是否正确。主页上我贴了校验的连接。
