### ISSUE TITLE
kingshard 两次查询结果不一致

### ISSUE THREAD

**Issue by Tieger** [flike/kingshard#415]
![581831958991554107](https://user-images.githubusercontent.com/9692484/36527009-4589ebda-17eb-11e8-9612-045d5bac356e.jpg)

通过kingshard 查询数据发现两次结果不一致,单独查询mysql 实例数据没有问题 未使用读写分离,发现问题的表不是shard表,重启 kingshard 后问题消失.
只有1个node节点,  
sys,log 无相关报错.
麻烦非哥了

**Comment by Tieger** [comment]
补充 , 会出错的都是 timestamp 字段

**Comment by longhairx** [comment]
看起来跟时区有关系啊～

**Comment by Tieger** [comment]
是的 ,通过kingshard 去查看 time_zone 参数 会在 system 和 +00:00 之间来回切换.  我对 9月 11月版本都进行了测试 问题依旧. 目前回退到了7月版本 还在观察

**Comment by Tieger** [comment]
7月版本也有这个问题.   蛋疼了

**Comment by flike** [comment]
能否给个稳定重现的步骤，有可能是kingshard未考虑到时区问题

**Comment by johnzhou2011** [comment]
用语句查看
show variables like "%time_zone%";
可以看到time_zone返回的值会变。

**Comment by flike** [comment]
我测试了连接单台或两台MySQL，并不会变化@johnzhou2011

**Comment by Tieger** [comment]
问题解决,程序配置有问题导致的,谢谢非哥
