### ISSUE TITLE
head版本auth错误，请检查

### ISSUE THREAD

**Issue by luaxlou** [flike/kingshard#433]
rt
切换到 3a842d60b4e3f23a9893b47d6b3c10d205263bd8可以连接

**Comment by flike** [comment]
现在kingshard引入了用户列表，配置文件也做了相应的调整。你是不是用的之前的配置？

**Comment by luaxlou** [comment]
是的，是之前的连接。看到配置文件变化了，感谢。但是没有看到change log 和tag。建议还是打下TAG，使用HEAD版本安装风险比较高。

**Comment by flike** [comment]
恩。我准备发一个新版本。谢谢建议。
