### ISSUE TITLE
在插入mysql数据时报错

### ISSUE THREAD

**Issue by yiranhouge** [flike/kingshard#434]
Could not retrieve transaction read-only status from server
用kingshard时，在插入数据时，偶尔报这个错，不知道什么原因，请问您知道是什么原因吗,其中mysql数据库版本为5.7

**Comment by flike** [comment]
请问如何复现？

**Comment by yiranhouge** [comment]
我们也不知道怎样复现，测试环境没有出现过这个问题，线上出现了这个问题，因为这个错误只有偶尔出现，我们的数据量一天在80万到90万之间，出现时间段也不固定，每天大概出现一次，每次也就10多条数据无法插入,以下是详细报错详细
### Error updating database. Cause: java.sql.SQLException: Could not retrieve transaction read-only status from server ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: INSERT INTO waybill_trace ...(1525)

**Comment by yiranhouge** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/26000182/40715254-8905058c-6437-11e8-9844-211946d1820a.png">

**Comment by flike** [comment]
对应的sql语句是什么

**Comment by yiranhouge** [comment]
<insert id="insertWaybillTraceInfo">
        INSERT INTO waybill_trace
        <trim prefix="(" suffix=")" suffixOverrides=",">
            <if test="createdAt != null">
                CREATED_AT,
            </if>
            <if test="updatedAt != null">
                UPDATED_AT,
            </if>
            <if test="time != null">
                `TIME`,
            </if>
            <if test="waybillNo != null">
                WAYBILL_NO,
            </if>
            <if test="orderTid != null">
                ORDER_TID,
            </if>
            <if test="currentPlace != null">
                CURRENT_PLACE,
            </if>
            <if test="currentStatus != null">
                CURRENT_STATUS,
            </if>
            <if test="lastStatus != null">
                LAST_STATUS,
            </if>
            <if test="operator != null">
                OPERATOR,
            </if>
            <if test="acceptAddress != null">
                ACCEPT_ADDRESS,
            </if>
            <if test="company != null">
                COMPANY,
            </if>
            <if test="operatorContact != null">
                OPERATOR_CONTACT,
            </if>
            <if test="context != null">
                CONTEXT,
            </if>
        </trim>
        <trim prefix="values (" suffix=")" suffixOverrides=",">
            <if test="createdAt != null">
                #{createdAt},
            </if>
            <if test="updatedAt != null">
                #{updatedAt},
            </if>
            <if test="time != null">
                #{time},
            </if>
            <if test="waybillNo != null">
                #{waybillNo},
            </if>
            <if test="orderTid != null">
                #{orderTid},
            </if>
            <if test="currentPlace != null">
                #{currentPlace},
            </if>
            <if test="currentStatus != null">
                #{currentStatus},
            </if>
            <if test="lastStatus != null">
                #{lastStatus},
            </if>
            <if test="operator != null">
                #{operator},
            </if>
            <if test="acceptAddress != null">
                #{acceptAddress},
            </if>
            <if test="company != null">
                #{company},
            </if>
            <if test="operatorContact != null">
                #{operatorContact},
            </if>
            <if test="context != null">
                #{context},
            </if>
        </trim>
    </insert>

**Comment by yiranhouge** [comment]
```  
<insert id="insertWaybillTraceInfo">
        INSERT INTO waybill_trace
        <trim prefix="(" suffix=")" suffixOverrides=",">
            <if test="createdAt != null">
                CREATED_AT,
            </if>
            <if test="updatedAt != null">
                UPDATED_AT,
            </if>
            <if test="time != null">
                `TIME`,
            </if>
            <if test="waybillNo != null">
                WAYBILL_NO,
            </if>
            <if test="orderTid != null">
                ORDER_TID,
            </if>
            <if test="currentPlace != null">
                CURRENT_PLACE,
            </if>
            <if test="currentStatus != null">
                CURRENT_STATUS,
            </if>
            <if test="lastStatus != null">
                LAST_STATUS,
            </if>
            <if test="operator != null">
                OPERATOR,
            </if>
            <if test="acceptAddress != null">
                ACCEPT_ADDRESS,
            </if>
            <if test="company != null">
                COMPANY,
            </if>
            <if test="operatorContact != null">
                OPERATOR_CONTACT,
            </if>
            <if test="context != null">
                CONTEXT,
            </if>
        </trim>
        <trim prefix="values (" suffix=")" suffixOverrides=",">
            <if test="createdAt != null">
                #{createdAt},
            </if>
            <if test="updatedAt != null">
                #{updatedAt},
            </if>
            <if test="time != null">
                #{time},
            </if>
            <if test="waybillNo != null">
                #{waybillNo},
            </if>
            <if test="orderTid != null">
                #{orderTid},
            </if>
            <if test="currentPlace != null">
                #{currentPlace},
            </if>
            <if test="currentStatus != null">
                #{currentStatus},
            </if>
            <if test="lastStatus != null">
                #{lastStatus},
            </if>
            <if test="operator != null">
                #{operator},
            </if>
            <if test="acceptAddress != null">
                #{acceptAddress},
            </if>
            <if test="company != null">
                #{company},
            </if>
            <if test="operatorContact != null">
                #{operatorContact},
            </if>
            <if test="context != null">
                #{context},
            </if>
        </trim>
    </insert>
```

**Comment by yiranhouge** [comment]
您好，为了方便交流这个问题，能够加个微信吗，18224531098

**Comment by yiranhouge** [comment]
您好，已解决，是我们使用ulb负载均衡导致的问题，现在单节点就没有问题了。
