### ISSUE TITLE
最新的git编译版本在客户端连接时报权限错误

### ISSUE THREAD

**Issue by luyaotang** [flike/kingshard#436]
最新的编译版本如下 ，发现覆盖之前的程序后，连接不上。会报ERROR 1045 (28000): Access denied for user 'xxxxxxxxx'@'127.0.0.1:45674' (using password: Yes)
== 当前的编译版本信息如果
Git commit:2018-05-31 09:25:48 +0800 @cff3b78
Build time:2018-06-06 11:50:10 +0800 by go version go1.10.2 linux/amd64

回滚此前的版本，一切正常
Git commit:2017-11-10 20:46:09 +0800 @d33d0d5
Build time:2017-11-15 10:35:57 +0800 by go version go1.9.2 linux/amd64

**Comment by luyaotang** [comment]
$ go version
go version go1.10.2 linux/amd64

**Comment by flike** [comment]
配置文件有变化，请更新一下配置文件。
