### ISSUE TITLE
不带ShardingKey 查询Sharding的表

### ISSUE THREAD

**Issue by fenngwd** [flike/kingshard#439]
Kingshard 对于Sharding的表的查询是否可以支持不带Sharding Key，就是全表查询?

**Comment by cx3ptr** [comment]
supported

**Comment by fenngwd** [comment]
那我在应用中使用时，kingshard报transcation in multi node。可能是什么原因？

**Comment by fenngwd** [comment]
感谢～你说的是对的，应用把autocommit disable，重新开启autocommit就可以了。
