### ISSUE TITLE
使用pymysql读取子表数据，提示“transaction in multi node”

### ISSUE THREAD

**Issue by zhou75** [flike/kingshard#440]
#查询非分表 一切正常
#查询分表 提示"transaction in multi node"
ERROR - conn_select.go:[114] - [ClientConn] "handleSelect" "transaction in multi node" 
#将条件修改为=，也是正常的，修改< 或者 >就不行了
sql='select * from test_shard_hash where id < %s' 
#直接使用mysql客户端都没有问题

**Comment by zhou75** [comment]
直接使用mysql客户端都没有问题

**Comment by flike** [comment]
产生了跨node的事务，kingshard是不支持的。你可以以非事务方式执行跨node的更新操作。
