### ISSUE TITLE
请问我windows下安装kingshard编译时报错，如何解？

### ISSUE THREAD

**Issue by lvjing0920** [flike/kingshard#444]
D:\Go\project\src\github.com\flike\kingshard>go build -o project/bin/kingshard.exe ./cmd/kingshard
# github.com/flike/kingshard/cmd/kingshard
cmd\kingshard\main.go:122:3: undefined: syscall.SIGUSR1
cmd\kingshard\main.go:135:21: undefined: syscall.SIGUSR1

**Comment by JodeZer** [comment]
syscall下的信号定义在windows系统下并没有
具体可以check golang源码syscall包下的windows文件

**Comment by lvjing0920** [comment]
@JodeZer 首先非常感谢您的指教，本人初次接触Go，能详细点的给讲解下我要如何处理吗，不胜感激~~

**Comment by JodeZer** [comment]
@lvjing0920 简单说就是不能在window上跑..

**Comment by lvjing0920** [comment]
@JodeZer 哦，好的，非常感谢~~

**Comment by xiaopiao5789** [comment]
把这两个信号去掉就可以编译，但是还没有测试能否运行

**Comment by iweixubin** [comment]
开发组就不能解决一下这个问题么，虽然部署环境是linux可以理解，但我现在只想在win搭个环境试试看，然后就被卡主了~无奈~

**Comment by chaegumi** [comment]
![Image](https://github.com/user-attachments/assets/12649196-5ab4-4587-9815-d85a3431c643)
我看源码，应该改为SIGKILL吧
