### ISSUE TITLE
transaction in multi node

### ISSUE THREAD

**Issue by dolores2018** [flike/kingshard#461]
配置文件
<pre>
addr: 0.0.0.0:3333
log_path: /var/log/kingshard
log_level: debug
log_sql: on
low_log_time: 100
proxy_charset: utf8mb4
web_addr: 127.0.0.1:8080
web_user: mashijie
web_password: mashijie320
user_list:
-
  user: dolores
  password : DoloreS2018

nodes:
-
  name: node1
  max_conns_limit: 128
  user:  dolores
  password: DoloreS2018
  master: rm-t4n4ogi0b7j23oy93.mysql.singapore.rds.aliyuncs.com:3306
  down_after_noalive: 32
-
  name: node2
  max_conns_limit: 128
  user:  dolores
  password: DoloreS2018
  master: rm-t4nz821ew95c68lul.mysql.singapore.rds.aliyuncs.com:3306
  down_after_noalive: 32

schema_list :
-
  user: dolores
  nodes: [node1, node2]
  default: node1
  shard:
  -
    db: dolores
    table: t_balance
    key: user_id
    nodes: [node1, node2]
    type: hash
    locations: [4, 4]
  -
    db: dolores
    table: t_order_active
    key: user_id
    nodes: [node1, node2]
    type: hash
    locations: [4, 4]
</pre>

当执行
<pre>
DELETE FROM t_order_active WHERE user_id = ?
</pre>
并且user_id = 198103时，报出transaction in multi node错误，经初步定位好像是路由有问题，请帮忙看一下原因。

**Comment by wankunde** [comment]
![image](https://user-images.githubusercontent.com/3626747/74079483-11e2eb80-4a73-11ea-8ccc-e12ec547b0a0.png)
I got the same error in superset query. Any one can help me?

**Comment by wankunde** [comment]
I have solve this problem.

We should set auto_commit off when query data through kingshard.
Superset configuration :

```
{
    "metadata_params": {},
    "engine_params": {"isolation_level":"AUTOCOMMIT"}
}
```
