### ISSUE TITLE
kingshard是否支持管理端api热更新master配置？

### ISSUE THREAD

**Issue by 527593036** [flike/kingshard#462]
kingshard 是否支持管理端api热更新master配置？

场景：
kingshard后面挂了多台主从的mysql

node1： 192.168.0.2(主)--->192.168.0.3(从)
node2： 192.168.0.4(主)--->192.168.0.5(从)
....

某天，192.168.0.4硬盘故障，导致写数据不可用，能否通过管理端api热更新配置，将node2的master指向192.168.0.5

**Comment by 527593036** [comment]
未来能否支持？这对快速切换故障有挺大帮助的，也丰富了管理api的功能。

**Comment by flike** [comment]
你更新配置肯定需要登录kingshard所在机器，所以通过信号发送也不是什么难事，感觉没必要再通过API来热加载配置的。不过API可以重置部分配置，详见：https://github.com/flike/kingshard/blob/master/doc/KingDoc/kingshard_admin_api.md
