### ISSUE TITLE
目前是stable版本吗？

### ISSUE THREAD

**Issue by leeyo** [flike/kingshard#464]
# master represents a real mysql master server
      master : 172.31.16.85:3306

    # slave represents a real mysql salve server,and the number after '@' is
    # read load weight of this slave.
    slave : 172.31.23.174:3306@1,172.31.19.76:3306@4

开头几次查询正常，查询多几次之后，连接就会卡住，不会超时并且没有响应，重启之后又正常。
以上3个节点均正常

**Comment by flike** [comment]
哪个版本？线上请使用1.6版本
