### ISSUE TITLE
新功能/特性支持请求

### ISSUE THREAD

**Issue by sanwv** [flike/kingshard#47]
**新特性请求**

- 支持后台伺服daemonize
- 平滑重启,查看状态,检测语法,重启等 如 kingshard reload/status/check/restat
- 支持动态加载移除node节点,添加分表schema等
- 支持join分表
- 并发控制

**Comment by sanwv** [comment]
谢谢评估支持

**Comment by flike** [comment]
你好，你提到的这些需求都非常中肯。这些需求我也想到了，后续会慢慢支持这些新特性的。优先级应该是这样的：

并发控制
支持后台伺服daemonize
平滑重启,查看状态,检测语法,重启等 如 kingshard reload/status/check/restat
支持动态加载移除node节点,添加分表schema等
支持join分表

**Comment by sanwv** [comment]
感谢

**Comment by orainxiong** [comment]
方便具体说明一下每个需求的细化要求吗?

**Comment by flike** [comment]
加群聊吧。
