### ISSUE TITLE
获取数据错误，对mysqlnd有要求吗

### ISSUE THREAD

**Issue by amilytan** [flike/kingshard#475]
环境如下：
系统版本  CentOS release 6.9 (Final)   2.6.32-696.3.1.el6.x86_64 
php版本  PHP 5.6.9 
php-mysql驱动版本 mysqlnd 5.0.11-dev - 20120503 
kingshard版本 最新
go版本    go1.11.1 

kingshard版本截图如下：
![image](https://user-images.githubusercontent.com/40881610/47415590-570fdb00-d7a6-11e8-987f-d15fd418cc22.png)

由于原来kingshard9月26日提交的版本出现连接无反应的问题问题，对kingshard升级至最新版。
升级后，连接问题得以解决，但出现了程序获取数据乱码现象

程序通过kingshard访问，获取数据乱码，截图如下：
![image](https://user-images.githubusercontent.com/40881610/47415668-8f171e00-d7a6-11e8-9221-65d5cc627905.png)

程序直接连接mysql访问，获取数据正常，截图如下：
![image](https://user-images.githubusercontent.com/40881610/47415718-b7068180-d7a6-11e8-9dc2-da95a703cf22.png)

请问，这是怎么回事呢？

**Comment by amilytan** [comment]
补充：mysql的版本是5.7.19-17

**Comment by chutian52** [comment]
@amilytan kingshard默认连接用的是UTF-8，确认下你的应用连接的jdbc-url使用的是utf8，后端存储也是用的UTF8

**Comment by amilytan** [comment]
@chutian52  你好，应用连接和后端存储都是使用utf8编码。接口返回的数据错乱，不止是编码问题，获取的值并不正确。

**Comment by amilytan** [comment]
@flike kinshard使用了默认的字符集，代码中都是用utf8编码读写。不止是字符集的问题，接口获取的字段和值都没对应，代码直连mysql获取是正确的。命令行无法重现，但数据显示格式有点不对齐，如下图：
![image](https://user-images.githubusercontent.com/40881610/48190961-f88a5580-e37e-11e8-932a-2dc6428754e5.png)

**Comment by chutian52** [comment]
@amilytan 这个mysql-server返回的时候还会用| 这种分隔吗？我觉得不会把？

**Comment by amilytan** [comment]
@chutian52  命令行操作是会的

**Comment by amilytan** [comment]
@chutian52  命令行直连mysql，格式显示如下：
![image](https://user-images.githubusercontent.com/40881610/48191653-a2b6ad00-e380-11e8-91e0-bb8c78e6d5ec.png)

**Comment by amilytan** [comment]
经过我们多次测试验证，读取数据错乱及乱码问题和kingshard无关，是程序本身处理问题，不好意思。
