### ISSUE TITLE
系统会每分钟调用 admin server(opt,k,v) values ('show','node','config')来查询状态，但发现1天大概会有几次报查询为空，而且耗时都为30秒。

### ISSUE THREAD

**Issue by luyaotang** [flike/kingshard#502]
==运行版本如下=====
    __   _                  __                   __
   / /__(_)___  ____ ______/ /_  ____ __________/ /
  / //_/ / __ \/ __ \/ ___/ __ \ / __\/ ___/ __  /
 / ,< / / / / / /_/ (__  ) / / / /_/ / /  / /_/ /
/_/|_/_/_/ /_/\__, /____/_/ /_/\__,_/_/   \__,_/
             /____/
Git commit:2017-11-10 20:46:09 +0800 @d33d0d5
Build time:2017-11-15 10:35:57 +0800 by go version go1.9.2 linux/amd64

==问题如下==
系统会每分钟调用 admin server(opt,k,v) values ('show','node','config')来查询状态，但发现1天大概会有几 次报查询为空，而且耗时都为30秒。初步排查为，不是连接超时，也不是查询错误。就是连接成功了，然后调用查询，卡住30秒，然后返回了一个空集（不是报错）。

**Comment by luyaotang** [comment]
ks的服务是用systemd来维护的，没有发现有重启过的迹象。同时查看sys.log也没有发现有相关的异常。

**Comment by codeloverforever** [comment]
https://dev.mysql.com/doc/internals/en/integer.html 这里官方有句话 Caution
If the first byte of a packet is a length-encoded integer and its byte value is 0xfe, you must check the length of the packet to verify that it has enough space for a 8-byte integer.
If not, it may be an EOF_Packet instead. 看了下最新的release的代码里  LengthEncodedInt 这个函数里貌似并没有处理这个情况
