### ISSUE TITLE
这个项目写的是分表和不分表支持join查询，我实际使用不能join查询

### ISSUE THREAD

**Issue by XvYong** [flike/kingshard#545]
关联查询怎么使用，有没有介绍的

**Comment by eastfisher** [comment]
kingshard关联查询不是很好用, 没有判断两张关联表的路由规则是否一致, 只按照第一个表的路由规则进行分表SQL改写.

**Comment by XvYong** [comment]
> kingshard关联查询不是很好用, 没有判断两张关联表的路由规则是否一致, 只按照第一个表的路由规则进行分表SQL改写.

我需要改什么配置吗？不然要改动很大范围的代码，感觉好难受哦

**Comment by flike** [comment]
需要严格按照文档中的格式，才可以执行
