### ISSUE TITLE
通过kingshard操作数据库，sql.log不记录日志，为什么？

### ISSUE THREAD

**Issue by Myshiner** [flike/kingshard#547]
我在mysql实例上创建的schema和表，然后通过kingshard登陆做的insert和select，可以查询和插入数据，但是sql并不会打到sql.log文件中，为什么？
我的log_sql为on，log_level是debug的, slow_log_time是1000

log_path : /data/logs/

# log level[debug|info|warn|error],default error
log_level : debug

# if set log_sql(on|off) off,the sql log will not output
log_sql: on
 
# only log the query that take more than slow_log_time ms
slow_log_time : 1000

**Comment by flike** [comment]
只有执行时间超过slow_log_time的SQL才会记录
