### ISSUE TITLE
节点指定和从库负载均衡问题

### ISSUE THREAD

**Issue by bigpyer** [flike/kingshard#55]
前提:使用最新版本的ks
问题一: 我指定节点查询时，/*node1*/select * from table，可以读到node1节点的slave，如果不指定node1,(配置中default node是node1)，则查询的是node1中的master

问题二 : 同一个节点内，master的地址不能配置到slave列表内，如果master的ip、port配知道slave，则启动时候报错
[main] "main" "not able to fi    ll the pool" "" conn_id=0

**Comment by flike** [comment]
问题1：需要在连接MySQL的时候加入 -c参数，否则注释会被客户端过滤掉。加上-c后，没有问题。
问题2：未重现。
