### ISSUE TITLE
使用go1.7后的go版本无法编译kingshard

### ISSUE THREAD

**Issue by voidint** [flike/kingshard#560]
- 从go1.8开始`go tool yacc`被移除了，Makefile中调用了该工具进行编译将会失败。

```shell
go tool yacc -o ./sqlparser/sql.go ./sqlparser/sql.y
go tool: no such tool "yacc"
make: *** [kingshard] Error 2
```

- 是否可以在Makefile中直接使用go实现的[yacc](https://github.com/golang/tools/blob/master/cmd/goyacc/yacc.go)？

**Comment by flike** [comment]
使用最新版本的Go
