### ISSUE TITLE
SQL log doesn't show any thing when queries

### ISSUE THREAD

**Issue by coolboyPT** [flike/kingshard#593]
Hi guy!
I'm trying to shard my database in mysql using kingshard. I did step by step in manual, but when I doing the queries, I don't see the results as for example. My log screen only has information like this:
![image](https://user-images.githubusercontent.com/30336207/100358169-d49e1900-3006-11eb-86dd-a3ce90ca2103.png)
Please tell me where i did wrong ?

**Comment by fenngwd** [comment]
It seems connection between kingshard and DB instance was bad. You could check network/firewall.

**Comment by coolboyPT** [comment]
The problem was resolved! Thank you
