### ISSUE TITLE
Add SQL sniffer for kingshard

### ISSUE THREAD

**Issue by Compasses** [flike/kingshard#61]
I have add a function that is SQL sniffer for kingshard in my local branch. which should be treat as new feature , the sniffer will record all the SQL request, request time for the same SQL, result length, and error info. 
it's help me a lot. it can find some unreasonable SQL requests and good for SQL performance optimize.

i just want to know whether it's reasonable to add it to kingshard. if you think so, i will give you the PR.

**Comment by flike** [comment]
yeah, This feature is much useful. I just want add the execution time of SQL in log, and this is good for SQL performance optimize. But other informations like: result length, I think it's not universal. :+1:

**Comment by Compasses** [comment]
OK. waiting your commit...
the other info maybe not universal, and it's just good for my own work. thanks.

**Comment by flike** [comment]
This feature has been supported

**Comment by Compasses** [comment]
Nice :)
