### ISSUE TITLE
Does sqlparser support `&` in WHERE

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#70]
Can't pass code snippet in `sql_test.go` like below:
```go
sql := "SELECT * FROM t_banner WHERE f_city_map & 8"
testParse(t, sql)
```

**Comment by flike** [comment]
OK, I'll check it, thank you for your feedback.

**Comment by flike** [comment]
I suggest you write this sql like "SELECT * FROM t_banner WHERE f_city_map & 8 = 1",or other pattern.
kingshard does not support this style sql which with no compare operation.

**Comment by simpleton** [comment]
Thanks for your workaround. It works for me.

PS: Should we implement boolExpr in `%type <boolExpr> where_expression_opt` supported single value expression?

**Comment by flike** [comment]
yes, you are right. But I think this function is insignificant .
