### ISSUE TITLE
Did Kingshard cache the stmt?

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#72]
I got a lot of  `Can't create more than max_prepared_stmt_count statements` error when I use kingshard in my production environment.

```go
conn.go:[281] - [server] "Run" "prepare error ERROR 1461 (42000): Can't create more than max_prepared_stmt_count statements (current value: 16382)" "" conn_id=11095
```

I wonder know does kingshard cache the stmt? 
If it cached, How could I modify it's cache size?

**Comment by flike** [comment]
No, this sql should be sent by mysql.

**Comment by flike** [comment]
this article(http://blog.csdn.net/niitlcj/article/details/8645859) may help you to solve you question, or you can offer more informations according to this article.

**Comment by simpleton** [comment]
@flike 问题是这样的。

用命令 show global status like '%com_stmt%';查看stmt相关值的状态，
```
Com_stmt_close              prepare语句关闭的次数
Com_stmt_execute            prepare语句执行的次数
Com_stmt_prepare            prepare语句创建的次数
```
发现Com_stmt_prepare的增长要大于Com_stmt_close，说明有leak。 然后去掉Kingshard，让beego直连rds发现2个参数增长一致，消除泄露。

English:

I found there is a leak in stmt prepare.

**Comment by flike** [comment]
好的，我仔细看一下代码。谢谢反馈。

**Comment by flike** [comment]
已修复，请确认一下，谢谢。

**Comment by simpleton** [comment]
Seems worked! Close now.

I'll reopen it when I find leak happened.
