### ISSUE TITLE
group by not support

### ISSUE THREAD

**Issue by dryangkun** [flike/kingshard#74]
ks.yaml配置：
![image](https://cloud.githubusercontent.com/assets/1642025/11385806/56c3745e-9357-11e5-8cb1-0f02ab130b2e.png)
表结构：
CREATE TABLE `test_shard_hash_0000` (
  `id` int(11) NOT NULL,
  `a` varchar(256) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
8张表，每张表一条记录

SQL：
select a,count(1) from test_shard_hash where id between 0 and 7 group by a
![image](https://cloud.githubusercontent.com/assets/1642025/11385848/a80c4e58-9357-11e5-8b22-5b5a54f6c241.png)

**Comment by flike** [comment]
是的。不支持group by。已经在开发计划之中了。

**Comment by flike** [comment]
group by 功能已经支持了。

**Comment by dryangkun** [comment]
amazing
