### ISSUE TITLE
底层用CGO如何？

### ISSUE THREAD

**Issue by dongzerun** [flike/kingshard#76]
感觉网络这块有些低效，考虑过把 vitess 底层连接 mysql 的cgo移植如何？

做成接口加载的方式，允许自由选择

**Comment by flike** [comment]
kingshard的性能已经达到了直连的80%以上（详情请看测试报告），性能已经不是问题了。而且移植过来之后，性能能不能提高还是个问题，并且会降低kingshard的稳定性。
