### ISSUE TITLE
show databases error

### ISSUE THREAD

**Issue by bigpyer** [flike/kingshard#78]
example like this:
mysql -h127.0.0.1 -P9696 -ukingshard -p
handshake successfully
mysql >show databases;

maybe you will get fault:
ERROR 1046 (3D000): No database selected

Error Log:
2015/12/05 14:36:08 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1046 (3D000): No database selected" "hasHandled=false" conn_id=0
2015/12/05 14:36:08 - ERROR - conn.go:[281] - [server] "Run" "ERROR 1046 (3D000): No database selected" "" conn_id=10245

**Comment by flike** [comment]
Thank you for your work!
