### ISSUE TITLE
这个不算是issue，应该是一个调整，关于分表

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#80]
目前的策略表名一定会被映射成tablename_####，但这个场景并不常见，绝大部分proxy工具也没有这么做，因为数据库的schema也需要维护开销，这样的做法会带给DBA更多的无趣的工作。在一个具体的database中把表名改成这样，我宁愿启动多个instance。

所以希望，
location中的数字是1的时候，使用yaml中配置的tablename，而不增加数字后缀。
或者增加一个选项可以忽略location，直接使用yaml中配置的tablename，而不增加数字后缀。

**Comment by flike** [comment]
在你提到的这种需求下，提供表名更合适一些。
