### ISSUE TITLE
发生过多次，ks进程正常，mysql正常，但ks已经无法正常工作

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#83]
怀疑是跟连接池处理有关。

2015/12/08 06:27:17 - ERROR - conn.go:[286] - [server] "Run" "connection was bad" "" conn_id=10004
2015/12/08 06:27:17 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "connection was bad" "hasHandled=false" conn_id=0
2015/12/08 06:27:17 - ERROR - conn.go:[286] - [server] "Run" "connection was bad" "" conn_id=10004
2015/12/08 06:27:18 - ERROR - conn_query.go:[110] - [server] "getBackendConn" "ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)" "" conn_id=0
2015/12/08 06:27:18 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)" "hasHandled=false" conn_id=0
2015/12/08 06:27:18 - ERROR - conn.go:[286] - [server] "Run" "ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)" "" conn_id=10004

**Comment by flike** [comment]
看log提示权限有问题，还有就是connection was bad 的提示，表示这个连接失效了，是不是你隔离很久没有请求过来？
Ps：能不能给出更详细的信息，方便定位问题？

**Comment by miao606** [comment]
是有很久没有连接进来。建议连接池定时执行select user();类似的命令，以确保所有链接池中的链接可用。目前ks日志就这么多。mysql服务正常，所以没有错误日志提供分析，系统也正常。ks也在设定的端口监听，只是不予许客户端连接。

**Comment by flike** [comment]
今天我会提交一个patch解决这个问题，谢谢反馈。

**Comment by miao606** [comment]
数据库服务器有这些记录。但ks启动后，肯定是没问题的，因为我是测试，所以没有具体的sql执行，一段时间后即发生。
ks在连接上后：
# mysql -u kingshard -p -h 127.0.0.1 -P 3307 -c -D mantisbt
Logging to file '/opt/mysql/logs/query.log'
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10003
Server version: 5.6.20-kingshard

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

[kingshard@127.0.0.1]-[mantisbt]>show tables;
ERROR 1105 (HY000): connection was bad
[kingshard@127.0.0.1]-[mantisbt]>show tables;
ERROR 1105 (HY000): connection was bad

再次连接
# mysql -u kingshard -p -h 127.0.0.1 -P 3307 -c -D mantisbt
Logging to file '/opt/mysql/logs/query.log'
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10005
Server version: 5.6.20-kingshard

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

[kingshard@127.0.0.1]-[mantisbt]>show tables;
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)

稍后片刻再次连接：
# mysql -u kingshard -p -h 127.0.0.1 -P 3307 -c -D mantisbt
Logging to file '/opt/mysql/logs/query.log'
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)


mysqld.log中记录：
2015-12-08 23:01:13 139833937807104 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)
2015-12-08 23:01:13 139833938347776 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)
2015-12-08 23:01:22 139833938482944 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)
2015-12-08 23:01:23 139833938888448 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)
2015-12-08 23:01:23 139833938077440 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)

**Comment by flike** [comment]
已经提交了patch，请重新下载源码后，再试试。新的patch会清除失效的连接。记得反馈一下，谢谢。

**Comment by miao606** [comment]
问题依然存在。群中提了一些建议

- 连接池增加一些属性，如连接创建时间、执行SQL次数、最近使用时间、空闲时间(可以根据最近使用算出来)、是否正在使用
- 增加连接池检测线程，对于当前没有被使用的连接执行检测
   - 如果执行的SQL次数大于某一阈值，则直接销毁重建
   - 否则执行如select user();、select @@version;之类的命令，不能执行（即提示连接关闭）的销毁重建
   - 以上可以通过异步销毁、执行命令，避免在连接检查的线程中操作

- 从连接池获取连接，如果执行用户SQL出现连接错，可以尝试多次重连，超过某一阈值，则标记node失效，如果是master则挂起服务，同时有定时器在后台继续检测


以上如果可以实现的话，可以顺带增加管理命令，如
admin server(opt,k,v)values('show','connections','config');
列出所有连接池连接的情况（id、创建时间、执行SQL次数，最后一次执行时间，空闲时长等）

**Comment by flike** [comment]
空闲连接的问题，现在已经修复了一部分。你提到的方案考虑的很周到，但是在某些场景下，重建连接会导致数据不一致。所以目前的做法是取连接的时候，尽量保证连接的有效性，其他阶段发现连接失效，则直接报错，让客户端感知到。

**Comment by flike** [comment]
Fixed

**Comment by franklwel1990** [comment]
Encountered the same problem： Error 1105: prepare error connection was bad
