### ISSUE TITLE
新需求，关于ks启动过程的建议

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#84]
目前ks启动时，如果配置的节点无法连接，则ks拒绝启动。建议：

ks进程正常启动，写错误日志（或者写等待节点上线，然后.....，就好象mysql启动一样），定时检查节点状态，当节点状态支持ks提供数据访问服务时提供proxy服务，否则对于所有的客户端连接给错误提示。

**Comment by flike** [comment]
这个需求我感觉是一种容错，但是不是更好，真不好说。
