### ISSUE TITLE
SQL执行结果错误，ks有数据返回，mysql没有

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#86]
仅用一个节点做测试：

错误描述，where a.id=b.id应该等效内连接，ks有结果返回，mysql没有

/*左表（分区）全部数据*/
[root@127.0.0.1]-[test]>select * from test_shard_hash a where 1 = 1;
+----+------+------+-------+-----+------+
| id | str  | f    | e     | u   | i    |
+----+------+------+-------+-----+------+
|  1 | abc1 | 3.14 | test1 | 255 | -127 |
|  2 | abc2 | 3.14 | test2 | 255 | -127 |
|  3 | abc3 | 3.14 | test3 | 255 | -127 |
|  4 | abc4 | 3.14 | test4 | 255 | -127 |
|  5 | abc5 | 3.14 | test5 | 255 | -127 |
+----+------+------+-------+-----+------+
5 rows in set (0.01 sec)

/*右表全部数据*/
[root@127.0.0.1]-[test]>select * from test_bug;
Empty set (0.01 sec)

/*ks执行*/
[root@127.0.0.1]-[test]>select * from test_shard_hash a,test_bug b where a.id = b.id;
+----+------+------+-------+-----+------+
| id | str  | f    | e     | u   | i    |
+----+------+------+-------+-----+------+
|  1 | abc1 | 3.14 | test1 | 255 | -127 |
|  2 | abc2 | 3.14 | test2 | 255 | -127 |
|  3 | abc3 | 3.14 | test3 | 255 | -127 |
|  4 | abc4 | 3.14 | test4 | 255 | -127 |
|  5 | abc5 | 3.14 | test5 | 255 | -127 |
+----+------+------+-------+-----+------+
5 rows in set (0.01 sec)

/*mysql执行*/
[root@127.0.0.1]-[test]>select * from test_shard_hash_0000 a,test_bug b where a.id = b.id;
Empty set (0.01 sec)

**Comment by flike** [comment]
目前ks对join的支持还不够完善。

**Comment by flike** [comment]
fixed
