### ISSUE TITLE
JOIN语法支持

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#87]
ks目前不支持所有的join语法

[root@127.0.0.1]-[test]>select * from test_shard_hash_0000 a inner join test_bug b on a.id = b.id;
Empty set (0.00 sec)

[root@127.0.0.1]-[test]>select a.* from test_shard_hash_0000 a left join test_bug b on a.id = b.id;
+----+------+------+-------+-----+------+
| id | str  | f    | e     | u   | i    |
+----+------+------+-------+-----+------+
|  1 | abc1 | 3.14 | test1 | 255 | -127 |
|  2 | abc2 | 3.14 | test2 | 255 | -127 |
|  3 | abc3 | 3.14 | test3 | 255 | -127 |
|  4 | abc4 | 3.14 | test4 | 255 | -127 |
|  5 | abc5 | 3.14 | test5 | 255 | -127 |
+----+------+------+-------+-----+------+
5 rows in set (0.01 sec)

[root@127.0.0.1]-[test]>select a.* from test_shard_hash_0000 a right join test_bug b on a.id = b.id;
Empty set (0.01 sec)

[root@127.0.0.1]-[test]>select a.* from test_shard_hash_0000 a cross join test_bug b on a.id = b.id;
Empty set (0.00 sec)

[root@127.0.0.1]-[test]>select * from test_shard_hash a inner join test_bug b on a.id = b.id;
ERROR 1146 (42S02): Table 'test.test_shard_hash' doesn't exist
[root@127.0.0.1]-[test]>select * from test_shard_hash a left join test_bug b on a.id = b.id;
ERROR 1146 (42S02): Table 'test.test_shard_hash' doesn't exist
[root@127.0.0.1]-[test]>select * from test_shard_hash a right join test_bug b on a.id = b.id;
ERROR 1146 (42S02): Table 'test.test_shard_hash' doesn't exist
[root@127.0.0.1]-[test]>select * from test_shard_hash a cross join test_bug b on a.id = b.id;
ERROR 1146 (42S02): Table 'test.test_shard_hash' doesn't exist
[root@127.0.0.1]-[test]>

**Comment by flike** [comment]
join做到了部分支持，后续我更新一下文档

**Comment by miao606** [comment]
Mycat有一种父子关系的表，比如orders和order_details，通过父子关系设定，可以使得某一个订单和订单明细可以分配到同一个node，这样就可以支持jion。

在有Mycat会设定全局表（ks可能默认全局吧），Mycat配置中没有提供的表印象中不能访问，全局表通常是数据字典表或者Lookup表，这个也能jion和更新/删除/新增，Mycat会发送到所有节点。

**Comment by flike** [comment]
好的，后续会把join尽量支持好。现在还有其他几个优先级较高的功能需要开发。谢谢你的建议。
PS：你们线上也用了kingshard吗？

**Comment by miao606** [comment]
暂时没有，ks还有一些亟待解决的问题。

**Comment by flike** [comment]
fixed
