### ISSUE TITLE
GROUP BY结果不正确，或者不支持？

### ISSUE THREAD

**Issue by miao606** [flike/kingshard#88]
[root@127.0.0.1]-[test]>select * from test_shard_range where 1 = 1;
+----+------+------+-------+-----+------+
| id | str  | f    | e     | u   | i    |
+----+------+------+-------+-----+------+
|  1 | abc1 | 3.14 | test1 | 255 | -127 |
|  2 | abc2 | 3.14 | test2 | 255 | -127 |
|  3 | abc3 | 3.14 | test3 | 255 | -127 |
|  4 | abc4 | 3.14 | test4 | 255 | -127 |
|  5 | abc5 | 3.14 | test5 | 255 | -127 |
|  6 | abc6 | 3.14 | test6 | 255 | -127 |
|  7 | abc7 | 3.14 | test7 | 255 | -127 |
+----+------+------+-------+-----+------+
7 rows in set (0.01 sec)

[root@127.0.0.1]-[test]>select id, count(*) from test_shard_hash where 1 = 1 group by id;
+----+----------+
| id | count(*) |
+----+----------+
|  1 |        7 |
|  2 |        7 |
|  3 |        7 |
|  4 |        7 |
|  5 |        7 |
|  6 |        7 |
|  7 |        7 |
+----+----------+
7 rows in set (0.02 sec)

[root@127.0.0.1]-[test]>select id, count(*) from test_shard_hash_0000 where 1 = 1 group by id;
+----+----------+
| id | count(*) |
+----+----------+
|  1 |        1 |
|  2 |        1 |
|  3 |        1 |
|  4 |        1 |
|  5 |        1 |
|  6 |        1 |
|  7 |        1 |
+----+----------+
7 rows in set (0.01 sec)

**Comment by bigpyer** [comment]
见issuehttps://github.com/flike/kingshard/issues/74

**Comment by flike** [comment]
分表下的group by还未支持，已经列入了开发计划。

**Comment by flike** [comment]
group by 功能已经支持。
