### ISSUE TITLE
kingshard 从hash切换range报错

### ISSUE THREAD

**Issue by samCbh** [flike/kingshard#89]
ks.yaml配置

  table: user
        key: id
        nodes: [node1, node2]
        type: range
        locations: [2,2]

本地，以及虚拟机mysql已经手动建好表user_0000,user_0001,user_0002,user_0003.
type:hash时候，代码运行没有报错。但是type:range报错：
2015/12/10 02:11:08 - OK - 0.2ms - 192.168.114.1:56657->127.0.0.1:3306:SET PROFILING = 1
2015/12/10 02:11:08 - OK - 0.2ms - 192.168.114.1:56657->127.0.0.1:3306:SET profiling_history_size = 0
2015/12/10 02:11:08 - OK - 0.1ms - 192.168.114.1:56657->127.0.0.1:3306:SET profiling_history_size = 15
2015/12/10 02:11:08 - OK - 1.4ms - 192.168.114.1:56657->127.0.0.1:3306:SHOW STATUS
2015/12/10 02:11:08 - ERROR - router.go:[293] - [Route] "BuildInsertPlan" "shard key not in key range" "" conn_id=0
2015/12/10 02:11:08 - ERROR - conn.go:[281] - [server] "Run" "shard key not in key range" "" conn_id=10001

myslq错误：
错误代码： 1105
shard key not in key range

**Comment by bigpyer** [comment]
不可以先hash分表，然后改成range分表，只能自始至终选择一种方式。

**Comment by samCbh** [comment]
表的数据已经清空，跟这个没有关系

**Comment by flike** [comment]
table: user
key: id
nodes: [node1, node2]
type: range
locations: [2,2]
#缺少这个配置
table_row_limit: 10000

**Comment by samCbh** [comment]
感谢，已经解决
