### ISSUE TITLE
kingshard 空闲连接时间

### ISSUE THREAD

**Issue by samCbh** [flike/kingshard#91]
过了一个晚上没有连接kingshard,程序再连接会报connection was bad。必须重新启动kingshard才能程序正常运行

**Comment by bigpyer** [comment]
可以拉取最新的代码，详情见如下issue，尽量不要提相似的issue，另外这个问题在群里多次讨论过，可以加群交流 147926796
https://github.com/flike/kingshard/issues/83

**Comment by flike** [comment]
同意楼上的观点。
