### ISSUE TITLE
should support sql commands that depend on the same connection between mysql and apps

### ISSUE THREAD

**Issue by bigpyer** [flike/kingshard#93]
example one：connect directly to mysql
1.insert into table1 values …
2.select LAST_INSERT_ID() as id
3.insert into table2 values …（success）

example two：connect to kingshard
1.insert into table1 values …
2.select LAST_INSERT_ID() as id (get wrong id, maybe)
3.insert into table2 values …（fail）

**Comment by wangcn** [comment]
请问这个fix有时间表吗？

**Comment by flike** [comment]
周末有空考虑修复一下这个问题。
