### ISSUE TITLE
Kingshard sqlparse didn't support table alias

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#97]
Here is the testcase:
```go
sql := "UPDATE `table` Q SET Q.`title` = 1 WHERE Q.`ID` = 101"
testParse(t, sql)
```

**Comment by flike** [comment]
Yeah, kingshard doesn't support alias in DML  SQL, only support alias in SELECT SQL. This feature is low priority, because you can write this sql in other way. :)
